/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:32:28 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/libexec/aosnotifyd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface AOSRealmSupport : NSObject
+(void)_updateRealmPrefs;
+(id)redirectedHostForHost:(id)arg1 withContext:(id)arg2 ;
+(void)setRedirectedHost:(id)arg1 forHost:(id)arg2 withContext:(id)arg3 ;
+(void)clearCachedHostsWithContext:(id)arg1 ;
+(void)_printCache;
+(void)initialize;
@end

