/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:37 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/PersistentAddressBookAddress.h>
#import <Maps/SyncingHistoryItem.h>
#import <Maps/HistoryItem.h>
#import <Maps/NSCopying.h>

@class NSString, NSData, NSDictionary;

@interface AddressBookAddress : PersistentAddressBookAddress <SyncingHistoryItem, HistoryItem, NSCopying> {

	void* _uncommittedRecord;
	void* _addressBook;
	NSString* _lastValidatedAddress;
	double _timestamp;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy) NSString * syncIdentifier; 
@property (nonatomic,readonly) NSData * syncData; 
@property (assign,nonatomic) double position; 
@property (nonatomic,readonly) char isValid; 
@property (nonatomic,copy,readonly) NSString * singleLineAddress; 
@property (nonatomic,copy,readonly) NSString * singleLineAddressWithHomeCountry; 
@property (nonatomic,copy,readonly) NSString * compositeName; 
@property (nonatomic,copy,readonly) NSString * phoneticName; 
@property (nonatomic,readonly) int addressType; 
@property (nonatomic,readonly) char isMeCard; 
@property (nonatomic,copy,readonly) NSDictionary * addressDictionary; 
@property (nonatomic,copy) NSString * lastValidatedAddress;                                   //@synthesize lastValidatedAddress=_lastValidatedAddress - In the implementation block
@property (nonatomic,readonly) char hasStreetAddress; 
@property (nonatomic,readonly) double timestamp;                                              //@synthesize timestamp=_timestamp - In the implementation block
+(char)addressBookAllowed;
+(id)singleAddressForPerson:(void*)arg1 ;
+(id)meCardHomeAddress;
+(void*)safeAddressBookRef;
+(void)refreshAddressBookIfNeeded:(void*)arg1 ;
+(char)meCardExists;
+(void)setSafeAddressBookCanBeRefreshed:(char)arg1 ;
+(char)safeAddressBookCanBeRefreshed;
+(void)_resetSharedAddressBookNeedsRefresh;
-(id)initWithRecordID:(int)arg1 addressID:(int)arg2 ;
-(char)updateFromSyncData:(id)arg1 ;
-(void*)_record;
-(id)initWithRecordID:(int)arg1 addressID:(int)arg2 addressBook:(void*)arg3 ;
-(NSString *)singleLineAddressWithHomeCountry;
-(NSString *)lastValidatedAddress;
-(void)setLastValidatedAddress:(NSString *)arg1 ;
-(void)_checkValid;
-(id)_initWithUncommittedRecord:(void*)arg1 addressID:(int)arg2 addressBook:(void*)arg3 ;
-(char)hasStreetAddress;
-(id)compositeNameMatchesForSearchString:(id)arg1 ;
-(char)isMeCard;
-(NSString *)singleLineAddress;
-(void)dealloc;
-(id)init;
-(unsigned)hash;
-(double)timestamp;
-(char)isValid;
-(int)type;
-(id)initWithData:(id)arg1 ;
-(NSString *)compositeName;
-(NSDictionary *)addressDictionary;
-(NSString *)phoneticName;
-(int)addressType;
-(NSData *)syncData;
@end

