/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:41 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSSet;

@interface AudioOutputSetting : NSObject {

	NSSet* _pickableRoutes;
	char _selected;
	char _selectedForSystem;
	char _hfpPreference;

}

@property (nonatomic,readonly) char hfpPreference; 
@property (assign,nonatomic) char selectedForSystem;              //@synthesize selectedForSystem=_selectedForSystem - In the implementation block
+(id)macAddressForRoute:(id)arg1 ;
+(char)isBluetoothRoute:(id)arg1 ;
-(char)settingForBluetoothDevice;
-(char)settingSupportsBluetoothHFP;
-(char)settingForBluetoothComboDevice;
-(char)hfpPreference;
-(id)initWithPickableRoutes:(id)arg1 ;
-(id)pickableRouteForHFPPreference:(char)arg1 ;
-(char)_isHFPRoute:(id)arg1 ;
-(char)selectedForRouteSelection:(int)arg1 ;
-(char)_isPicked:(id)arg1 ;
-(void)setHfpPreference:(char)arg1 ;
-(void)setSelected:(char)arg1 shouldSetHFPPreference:(char)arg2 ;
-(id)initWithPickableRoute:(id)arg1 ;
-(char)containsPickableRoute:(id)arg1 ;
-(char)isEqualToSetting:(id)arg1 ;
-(char)settingForDefaultRoute;
-(char)allowHFPPreferenceSelectionForRouteSelection:(int)arg1 ;
-(char)pickedStateConsistentWithHFPPreference;
-(char)selectedForSystem;
-(void)setSelectedForSystem:(char)arg1 ;
-(void)setPicked:(char)arg1 ;
-(char)_pickRoute:(id)arg1 ;
-(id)routeUID;
-(char)isPicked;
-(id)description;
-(void)setSelected:(char)arg1 ;
-(id)displayName;
-(id)macAddress;
@end

