/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:38 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/NMMapsAppXPCInterface.h>
#import <Maps/DirectionsManagerObserver.h>
#import <Maps/DirectionsManagerDelegate.h>
#import <Maps/MNNavigationModeControllerDelegate.h>
#import <Maps/SteppingModeDelegate.h>

@protocol DirectionsControllerDelegate;
@class DirectionsManager, MNNavigationModeController, MNRoute, SearchPinsManager, SelectedRouteStepAnnotation, NSMutableSet, FullscreenGuidanceModeController, SteppingModeController, UIActionSheet, NSXPCConnection, DirectionsAnnotationsManager, UIImageView, MKMapView, DirectionsHistoryItem, GEOComposedRouteStep, GEORouteMatch, NSString;

@interface DirectionsController : NSObject <NMMapsAppXPCInterface, DirectionsManagerObserver, DirectionsManagerDelegate, MNNavigationModeControllerDelegate, SteppingModeDelegate> {

	id<DirectionsControllerDelegate> _delegate;
	DirectionsManager* _directionsManager;
	MNNavigationModeController* _navViewController;
	unsigned _transportType;
	MNRoute* _selectedRoute;
	int _stepIndex;
	char _isShowingNavigationDisplay;
	char _needToShowRoute;
	char _pansAndZoomsToRouteOverview;
	char _showsAlternateRoutes;
	SearchPinsManager* _pinsManager;
	int _searchMode;
	char _isShowingAlternateRouteAnnotationMarkers;
	SCD_Struct_RA2 _routePositionViewCoordinate;
	SelectedRouteStepAnnotation* _selectedRouteStepAnnotation;
	NSMutableSet* _guidanceOutputs;
	int _lastDirectionsStartOptions;
	char _isShowingNavOnTopOfStepping;
	FullscreenGuidanceModeController* _fullscreenMode;
	SteppingModeController* _coveredSteppingController;
	UIActionSheet* _simulationPrompt;
	NSXPCConnection* _companionProxyConnection;
	MNRoute* _lastPreviewedRoute;
	char _showingRoute;
	DirectionsAnnotationsManager* _directionsAnnotationsManager;
	UIImageView* _routePositionView;
	MKMapView* _mapView;
	DirectionsHistoryItem* _currentHistoryItem;

}

@property (assign,nonatomic) char isShowingNavigationDisplay;                                                 //@synthesize isShowingNavigationDisplay=_isShowingNavigationDisplay - In the implementation block
@property (assign,nonatomic) char needToShowRoute;                                                            //@synthesize needToShowRoute=_needToShowRoute - In the implementation block
@property (assign,nonatomic) char pansAndZoomsToRouteOverview;                                                //@synthesize pansAndZoomsToRouteOverview=_pansAndZoomsToRouteOverview - In the implementation block
@property (assign,nonatomic) char showingRoute;                                                               //@synthesize showingRoute=_showingRoute - In the implementation block
@property (assign,nonatomic) char showsAlternateRoutes;                                                       //@synthesize showsAlternateRoutes=_showsAlternateRoutes - In the implementation block
@property (assign,nonatomic,__weak) DirectionsAnnotationsManager * directionsAnnotationsManager;              //@synthesize directionsAnnotationsManager=_directionsAnnotationsManager - In the implementation block
@property (assign,nonatomic,__weak) id<DirectionsControllerDelegate> delegate;                                //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) unsigned transportType;                                                          //@synthesize transportType=_transportType - In the implementation block
@property (assign,nonatomic,__weak) MKMapView * mapView;                                                      //@synthesize mapView=_mapView - In the implementation block
@property (assign,nonatomic) int stepIndex;                                                                   //@synthesize stepIndex=_stepIndex - In the implementation block
@property (assign,nonatomic) unsigned selectedRouteIndex; 
@property (assign,nonatomic) int searchMode;                                                                  //@synthesize searchMode=_searchMode - In the implementation block
@property (assign,nonatomic,__weak) SearchPinsManager * pinsManager;                                          //@synthesize pinsManager=_pinsManager - In the implementation block
@property (nonatomic,readonly) DirectionsManager * directionsManager;                                         //@synthesize directionsManager=_directionsManager - In the implementation block
@property (nonatomic,readonly) GEOComposedRouteStep * step; 
@property (nonatomic,retain) MNRoute * selectedRoute;                                                         //@synthesize selectedRoute=_selectedRoute - In the implementation block
@property (nonatomic,readonly) GEORouteMatch * currentRouteMatch; 
@property (nonatomic,retain) UIImageView * routePositionView;                                                 //@synthesize routePositionView=_routePositionView - In the implementation block
@property (nonatomic,readonly) DirectionsHistoryItem * currentHistoryItem;                                    //@synthesize currentHistoryItem=_currentHistoryItem - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(DirectionsAnnotationsManager *)directionsAnnotationsManager;
-(int)searchMode;
-(void)startDirectionsToPreviewRouteWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)clearPreviewRouteWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)stopDirections;
-(void)updateDroppedPin:(id)arg1 ;
-(void)updateHistoryItem:(id)arg1 ;
-(void)setSearchMode:(int)arg1 ;
-(void)directionsManagerWillReset:(id)arg1 ;
-(void)directionsManagerDidReset:(id)arg1 ;
-(id)navigationSession;
-(id)directionsSession;
-(void)directionsManagerDidFailToLoad:(id)arg1 withError:(id)arg2 ;
-(void)directionsManagerDidStartLoad:(id)arg1 ;
-(void)directionsManagerUpdatedETA:(id)arg1 ;
-(void)directionsManagerUpdatedTrafficIncidents:(id)arg1 ;
-(void)directionsManagerUpdatedMatchedLocation:(id)arg1 matchedLocation:(id)arg2 ;
-(void)directionsManager:(id)arg1 didChangeNavigatorState:(int)arg2 ;
-(void)directionsManager:(id)arg1 didLoadRoute:(id)arg2 ;
-(void)directionsManagerDidFailToReceiveRoute:(id)arg1 ;
-(void)directionsManagerWillRecalculateRoute:(id)arg1 ;
-(void)directionsManagerDidSwitchToNewRoute:(id)arg1 route:(id)arg2 ;
-(void)directionsManagerDidCancelLoad:(id)arg1 ;
-(void)directionsManagerDidUpdateToStepIndex:(id)arg1 stepIndex:(id)arg2 ;
-(void)directionsManager:(id)arg1 proceedToRouteDistance:(double)arg2 displayString:(id)arg3 remainingTime:(double)arg4 remainingDistance:(double)arg5 ;
-(void)directionsManager:(id)arg1 remainingTime:(double)arg2 remainingDistance:(double)arg3 ;
-(void)directionsManager:(id)arg1 displayPrimaryStepManeuverType:(int)arg2 junctionType:(int)arg3 junctionElements:(SCD_Struct_Di11*)arg4 count:(unsigned long)arg5 instructions:(id)arg6 shorterAlternativeInstructions:(id)arg7 shieldType:(int)arg8 shieldText:(id)arg9 drivingSide:(int)arg10 ;
-(void)directionsManager:(id)arg1 displaySecondaryStepManeuverType:(int)arg2 junctionType:(int)arg3 junctionElements:(SCD_Struct_Di11*)arg4 count:(unsigned long)arg5 instructions:(id)arg6 shorterAlternativeInstructions:(id)arg7 shieldType:(int)arg8 shieldText:(id)arg9 drivingSide:(int)arg10 ;
-(void)directionsManagerHideSecondaryStep:(id)arg1 ;
-(void)directionsManagerHasArrived:(id)arg1 ;
-(void)directionsManagerHasReachedEndOfLeg:(id)arg1 willContinueGuidance:(char)arg2 ;
-(void)directionsManager:(id)arg1 needsPromptToSimulateForOptions:(int)arg2 ;
-(void)directionsManager:(id)arg1 displayDirectionsToSelectedRouteWithNavigationOfType:(int)arg2 options:(int)arg3 ;
-(void)directionsManager:(id)arg1 displayDirectionsToSelectedRouteWithoutNavigationWithOptions:(int)arg2 ;
-(void)directionsManager:(id)arg1 didStartNavigationSessionOfType:(int)arg2 options:(int)arg3 ;
-(char)isShowingNavigationDisplay;
-(GEORouteMatch *)currentRouteMatch;
-(id)currentNavigator;
-(void)navigationModeWillDismiss:(id)arg1 isNavigationEnding:(char)arg2 ;
-(void)navigationModeDidFinish:(id)arg1 ;
-(void)navigationModeChoseEnd:(id)arg1 ;
-(void)willStartNavigation;
-(void)willPauseNavigation;
-(void)willResumeNavigation;
-(void)willEndNavigation;
-(void)navigationModeDidSwitchToNewRoute:(id)arg1 ;
-(void)navigationModeTransportTypeChanged:(id)arg1 transportType:(int)arg2 ;
-(void)setPinsManager:(SearchPinsManager *)arg1 ;
-(void)setDirectionsAnnotationsManager:(DirectionsAnnotationsManager *)arg1 ;
-(char)showingRoute;
-(void)setDirectionsEnabled:(char)arg1 animated:(char)arg2 completion:(/*^block*/id)arg3 ;
-(void)showRoutingAppsFromOrigin:(id)arg1 toDestination:(id)arg2 ;
-(void)presentNavigationController;
-(void)goToRouteStepAnimated:(char)arg1 ;
-(void)goToRemainingRouteAnimated:(char)arg1 completion:(/*^block*/id)arg2 ;
-(void)goToMainRoutesAnimated:(char)arg1 onCompletion:(/*^block*/id)arg2 ;
-(DirectionsManager *)directionsManager;
-(void)setShowsAlternateRoutes:(char)arg1 ;
-(char)isDirectionsSessionActive;
-(void)willStartDirections;
-(void)startPresentingFullscreenGuidanceInsteadOfNavigation;
-(void)stopPresentingFullscreenGuidanceInsteadOfNavigation;
-(void)presentNavigationControllerAnimated:(char)arg1 ;
-(void)_createCompanionProxyConnection;
-(void)setSelectedRouteNoNotify:(id)arg1 ;
-(void)_setShowingRoutes:(char)arg1 animated:(char)arg2 ;
-(void)_showRoutePickingModeWithProvider:(id)arg1 forDirectionsManager:(id)arg2 replaceCurrentMode:(char)arg3 defaultToRoutingApps:(char)arg4 ;
-(void)switchToTransportType:(int)arg1 ;
-(DirectionsHistoryItem *)currentHistoryItem;
-(void)_showRoutePickingModeWithProvider:(id)arg1 forDirectionsManager:(id)arg2 ;
-(char)_shouldCreateHistoryItemOnRouteLoad;
-(void)_createHistoryItemForFailure:(char)arg1 ;
-(id)_historyItemForSelectedRouteWithTimestamp:(double)arg1 ;
-(void)setCurrentHistoryItem:(id)arg1 forFailure:(char)arg2 ;
-(void)setIsShowingNavigationDisplay:(char)arg1 ;
-(void)_didChangeSelectedRouteIndex:(unsigned)arg1 ;
-(SCD_Struct_RA6)_mapRectForRemainingRoute:(id)arg1 ;
-(void)goToRouteStepAnimated:(char)arg1 onCompletion:(/*^block*/id)arg2 ;
-(char)pansAndZoomsToRouteOverview;
-(SCD_Struct_RA6)_mapRectForStep:(id)arg1 inRoute:(id)arg2 ;
-(char)needToShowRoute;
-(void)setNeedToShowRoute:(char)arg1 ;
-(void)_showPreparedRouteAnimated:(char)arg1 ;
-(void)setShowingRoute:(char)arg1 ;
-(id)directionsRecorder;
-(void)_dismissSimulationPrompt;
-(void)_presentTransportType:(int)arg1 useSimulation:(char)arg2 animated:(char)arg3 ;
-(void)_createNavigationModeControllerForType:(int)arg1 ;
-(void)directionsManagerDidFailToRecalculateRoute:(id)arg1 ;
-(void)steppingModeChoseEnd:(id)arg1 ;
-(void)steppingModeChoseOverview:(id)arg1 ;
-(void)steppingModeChoseGuideMe:(id)arg1 withTransportType:(int)arg2 leg:(id)arg3 ;
-(char)_needsToPanRoutePositionView;
-(CGRect)mapFrame;
-(id)navigationMapView;
-(void)setPansAndZoomsToRouteOverview:(char)arg1 ;
-(SearchPinsManager *)pinsManager;
-(UIImageView *)routePositionView;
-(void)setRoutePositionView:(UIImageView *)arg1 ;
-(char)showsAlternateRoutes;
-(id)_displayedRoutes;
-(void)setSelectedRoute:(MNRoute *)arg1 ;
-(MNRoute *)selectedRoute;
-(void)setMapView:(MKMapView *)arg1 ;
-(MKMapView *)mapView;
-(void)dealloc;
-(void)setDelegate:(id<DirectionsControllerDelegate>)arg1 ;
-(id)init;
-(id<DirectionsControllerDelegate>)delegate;
-(int)stepIndex;
-(char)isNavigating;
-(void)endNavigation;
-(void)setTransportType:(unsigned)arg1 ;
-(void)setStepIndex:(int)arg1 ;
-(GEOComposedRouteStep *)step;
-(unsigned)selectedRouteIndex;
-(void)setSelectedRouteIndex:(unsigned)arg1 ;
-(unsigned)transportType;
@end

