/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:43 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/MNBTAJobDelegate.h>
#import <Maps/GEORoutePreloadSessionDelegate.h>

@protocol GEORoutePreloadSession;
@class MNBTAJob, NSString;

@interface MapsRoutePreloadSession : NSObject <MNBTAJobDelegate, GEORoutePreloadSessionDelegate> {

	id<GEORoutePreloadSession> _preloadSession;
	MNBTAJob* _wifiJob;
	MNBTAJob* _goodCellularJob;

}

@property (readonly) id<GEORoutePreloadSession> preloadSession;              //@synthesize preloadSession=_preloadSession - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id<GEORoutePreloadSession>)preloadSession;
-(id)initWithRoute:(id)arg1 traits:(id)arg2 ;
-(void)routePreloadSessionPausedLoading:(id)arg1 ;
-(void)routePreloadSessionBeganLoading:(id)arg1 ;
-(void)routePreloadSessionStoppedLoading:(id)arg1 wasEnabledAndNotPaused:(char)arg2 ;
-(void)btaJob:(id)arg1 updatedState:(id)arg2 ;
-(void)_createBTAJobs;
-(void)_destroyBTAJobs;
-(void)dealloc;
@end

