/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:38 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/MNLocationTrackerDelegate.h>
#import <Maps/MNNavigationAudioSessionDelegate.h>
#import <Maps/MNExternalGuidanceSource.h>
#import <Maps/MKLocationManagerObserver.h>
#import <Maps/MNRouteManagerDelegate.h>

@class MNLocationTracker, MNRouteManager, MNThermalLogger, MNMotionContext, MNNavigationAudioSession, MNCoreMotionContextProvider, MNLocation, MNNavigator, GEOComposedWaypoint, NSString;

@interface MNNavigationSession : NSObject <MNLocationTrackerDelegate, MNNavigationAudioSessionDelegate, MNExternalGuidanceSource, MKLocationManagerObserver, MNRouteManagerDelegate> {

	MNLocationTracker* _locationTracker;
	MNRouteManager* _routeManager;
	MNThermalLogger* _thermalLogger;
	MNMotionContext* _motionContext;
	MNNavigationAudioSession* _audioSession;
	MNCoreMotionContextProvider* _coreMotionProvider;
	MNLocation* _lastMatchedLocation;
	char _guidanceEnabled;
	int _defaultTransportType;
	char _started;
	char _isActiveSession;
	char _announcingArrival;

}

@property (nonatomic,readonly) MNNavigator * navigator; 
@property (nonatomic,readonly) MNRouteManager * routeManager;                                       //@synthesize routeManager=_routeManager - In the implementation block
@property (nonatomic,readonly) MNMotionContext * motionContext;                                     //@synthesize motionContext=_motionContext - In the implementation block
@property (nonatomic,readonly) MNNavigationAudioSession * audioSession;                             //@synthesize audioSession=_audioSession - In the implementation block
@property (nonatomic,readonly) GEOComposedWaypoint * destination; 
@property (nonatomic,readonly) MNLocation * lastMatchedLocation;                                    //@synthesize lastMatchedLocation=_lastMatchedLocation - In the implementation block
@property (nonatomic,readonly) int navigationState; 
@property (nonatomic,readonly) int currentTransportType; 
@property (nonatomic,readonly) char isNavigating; 
@property (assign,getter=isGuidanceEnabled,nonatomic) char guidanceEnabled;                         //@synthesize guidanceEnabled=_guidanceEnabled - In the implementation block
@property (nonatomic,readonly) unsigned lastMatchedStepIndex; 
@property (nonatomic,readonly) unsigned lastMatchedLegIndex; 
@property (getter=isStarted,nonatomic,readonly) char started;                                       //@synthesize started=_started - In the implementation block
@property (nonatomic,readonly) id<MNNavigationSessionTestingDelegate> testingDelegate; 
@property (assign,nonatomic) char isActiveSession;                                                  //@synthesize isActiveSession=_isActiveSession - In the implementation block
@property (assign,nonatomic) char announcingArrival;                                                //@synthesize announcingArrival=_announcingArrival - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(MNNavigator *)navigator;
-(MNRouteManager *)routeManager;
-(unsigned)lastMatchedStepIndex;
-(unsigned)lastMatchedLegIndex;
-(void)startNavigatorWithGuidance:(char)arg1 ;
-(void)setGuidanceEnabled:(char)arg1 ;
-(int)currentTransportType;
-(MNMotionContext *)motionContext;
-(MNNavigationAudioSession *)audioSession;
-(MNLocation *)lastMatchedLocation;
-(char)isGuidanceEnabled;
-(char)repeatCurrentGuidance;
-(void)routeManagerDidChangeState:(id)arg1 newRouteState:(int)arg2 ;
-(void)routeManager:(id)arg1 didChangeRoutePreloadSession:(id)arg2 ;
-(void)routeManager:(id)arg1 recordRouteRequest:(id)arg2 ;
-(void)routeManagerDidCancelRoute:(id)arg1 errorCode:(int)arg2 ;
-(void)routeManagerWillRequestRoute:(id)arg1 traceRecorderFailed:(char)arg2 ;
-(void)routeManagerDidFailToRecalculateRoute:(id)arg1 previousRoute:(id)arg2 errorCode:(int)arg3 ;
-(void)routeManagerWillRecalculateRoute:(id)arg1 ;
-(void)routeManager:(id)arg1 didSwitchToNewRoute:(id)arg2 alreadyOnRoute:(char)arg3 forcedSwitch:(char)arg4 ;
-(void)routeManager:(id)arg1 recordRouteResponse:(id)arg2 ;
-(void)routeManager:(id)arg1 didReceiveRouteSet:(id)arg2 ;
-(void)routeManager:(id)arg1 didRecalculateNewRoute:(id)arg2 ;
-(id<MNNavigationSessionTestingDelegate>)testingDelegate;
-(void)routeManagerDidFailToReceiveRoute:(id)arg1 error:(id)arg2 ;
-(void)routeManager:(id)arg1 failedWithError:(id)arg2 ;
-(void)routeManagerUpdatedETA:(id)arg1 ;
-(void)routeManagerUpdatedTrafficIncidents:(id)arg1 ;
-(void)routeManager:(id)arg1 recommendsNewRoute:(id)arg2 etaRoute:(id)arg3 oldEstimatedTime:(unsigned)arg4 newEstimatedTime:(unsigned)arg5 ;
-(void)stopNavigatorAfterArrivalAnnouncement:(char)arg1 ;
-(void)switchToTransportType:(int)arg1 ;
-(void)stopNavigator;
-(void)resumeNavigator;
-(void)setIsActiveSession:(char)arg1 ;
-(id)_newNavigatorForTransportType:(int)arg1 ;
-(void)_willStartSessionForRoute:(id)arg1 ;
-(void)_startLocationTracking;
-(void)_startSteppingLocationTracker;
-(void)_willEndSession;
-(void)_stopSteppingLocationTracker;
-(void)_endAudioSession;
-(void)setAnnouncingArrival:(char)arg1 ;
-(void)_stopLocationTracking;
-(void)_willStartNavigatorForRoute:(id)arg1 ;
-(void)_updateLocationManagerForTurnByTurn:(char)arg1 ;
-(void)_setupDefaultNavigator;
-(char)_calculateGuidanceEnabled;
-(void)_didStartNavigator;
-(void)_willStopNavigator;
-(void)_endActiveNavigationState;
-(char)announcingArrival;
-(void)_transportTypeChanged:(int)arg1 ;
-(void)switchToNewRoute:(id)arg1 etaRoute:(id)arg2 ;
-(void)_switchToCorrectNavigatorForStep:(id)arg1 ;
-(id)routeRepresentation;
-(void)resetForTracePlayerAtLocation:(id)arg1 ;
-(void)locationTrackerWillPause:(id)arg1 ;
-(void)locationTrackerWillResumeFromPause:(id)arg1 ;
-(void)locationTracker:(id)arg1 didEnableGuidance:(char)arg2 ;
-(void)locationTracker:(id)arg1 updatedMatchedLocation:(id)arg2 ;
-(void)locationTracker:(id)arg1 didChangeState:(int)arg2 ;
-(void)locationTracker:(id)arg1 failedWithErrorCode:(int)arg2 ;
-(void)locationTracker:(id)arg1 startingStepIndex:(unsigned)arg2 ;
-(void)locationTracker:(id)arg1 updatePointOfInterest:(SCD_Struct_RA2)arg2 focusStyle:(int)arg3 ;
-(void)locationTracker:(id)arg1 proceedToRouteDistance:(double)arg2 displayString:(id)arg3 remainingTime:(double)arg4 remainingDistance:(double)arg5 closestStepIndex:(unsigned)arg6 ;
-(void)locationTracker:(id)arg1 remainingTime:(double)arg2 remainingDistance:(double)arg3 ;
-(void)locationTracker:(id)arg1 currentStepIndex:(unsigned)arg2 distanceUntilManeuver:(double)arg3 timeUntilManeuver:(double)arg4 ;
-(void)locationTracker:(id)arg1 displayPrimaryStepManeuverType:(int)arg2 junctionType:(int)arg3 junctionElements:(SCD_Struct_Di11*)arg4 count:(unsigned long)arg5 instructions:(id)arg6 shorterAlternativeInstructions:(id)arg7 shieldType:(int)arg8 shieldText:(id)arg9 drivingSide:(int)arg10 maneuverStepIndex:(unsigned)arg11 isSynthetic:(char)arg12 ;
-(void)locationTracker:(id)arg1 displayManeuverAlertForAnnouncementStage:(unsigned)arg2 ;
-(void)locationTracker:(id)arg1 displaySecondaryStepManeuverType:(int)arg2 junctionType:(int)arg3 junctionElements:(SCD_Struct_Di11*)arg4 count:(unsigned long)arg5 instructions:(id)arg6 shorterAlternativeInstructions:(id)arg7 shieldType:(int)arg8 shieldText:(id)arg9 drivingSide:(int)arg10 ;
-(void)locationTrackerHideSecondaryStep:(id)arg1 ;
-(void)locationTrackerHasArrived:(id)arg1 ;
-(void)locationTrackerHasReachedEndOfLeg:(id)arg1 ;
-(void)locationTrackerDetectedNewTransportType:(id)arg1 newTransportType:(int)arg2 ;
-(void)locationTracker:(id)arg1 matchedToStepIndex:(unsigned)arg2 legIndex:(unsigned)arg3 ;
-(void)audioSessionWillAnnounceArrival:(id)arg1 ;
-(void)audioSessionDidFinishAnnouncingArrival:(id)arg1 ;
-(id)initWithRouteManager:(id)arg1 transportType:(int)arg2 ;
-(void)startNavigator;
-(char)_currentRouteLegTypeOnRoute:(id)arg1 matchesNavigatorType:(id)arg2 ;
-(void)_switchToCorrectNavigatorForRoute:(id)arg1 ;
-(void)_didStartSession;
-(void)locationManagerUpdatedLocation:(id)arg1 ;
-(void)locationManagerFailedToUpdateLocation:(id)arg1 withError:(id)arg2 ;
-(void)locationManagerDidReset:(id)arg1 ;
-(char)locationManagerShouldPauseLocationUpdates:(id)arg1 ;
-(void)locationManager:(id)arg1 didUpdateVehicleSpeed:(double)arg2 timestamp:(id)arg3 ;
-(void)locationManager:(id)arg1 didUpdateVehicleHeading:(double)arg2 timestamp:(id)arg3 ;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(GEOComposedWaypoint *)destination;
-(void)endSession;
-(char)isStarted;
-(char)isActiveSession;
-(int)navigationState;
-(char)isNavigating;
-(void)locationManagerDidPauseLocationUpdates:(id)arg1 ;
-(void)locationManagerDidResumeLocationUpdates:(id)arg1 ;
-(void)startSession;
@end

