/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:38 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MNVoiceControllerObserver <NSObject>
@required
-(void)voiceController:(id)arg1 didStartSpeakingPrompt:(id)arg2;
-(void)voiceController:(id)arg1 didActivateAudioSession:(char)arg2;

@end

