/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:40 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UISearchBar.h>

@protocol UITextFieldDelegate;
@class UIColor;

@interface PassthruSearchBar : UISearchBar {

	id<UITextFieldDelegate> _textFieldDelegate;
	UIColor* _textColor;

}

@property (assign,nonatomic,__weak) id<UITextFieldDelegate> textFieldDelegate;              //@synthesize textFieldDelegate=_textFieldDelegate - In the implementation block
@property (nonatomic,retain) UIColor * textColor;                                           //@synthesize textColor=_textColor - In the implementation block
-(void)setTextColor:(UIColor *)arg1 ;
-(UIColor *)textColor;
-(char)textFieldShouldBeginEditing:(id)arg1 ;
-(void)textFieldDidBeginEditing:(id)arg1 ;
-(char)textFieldShouldEndEditing:(id)arg1 ;
-(void)textFieldDidEndEditing:(id)arg1 ;
-(char)textFieldShouldClear:(id)arg1 ;
-(char)textFieldShouldReturn:(id)arg1 ;
-(void)setTextFieldDelegate:(id<UITextFieldDelegate>)arg1 ;
-(id<UITextFieldDelegate>)textFieldDelegate;
@end

