/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:36 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/RAPQuestion.h>

@class RAPPlaceCorrectableString, VKLabelMarker, RAPCommentQuestion, RAPReportContext, NSString;

@interface RAPLabelCorrectionsQuestion : RAPQuestion {

	RAPPlaceCorrectableString* _correctableName;
	VKLabelMarker* _labelMarker;
	RAPCommentQuestion* _commentQuestion;
	RAPReportContext* _labelMarkerPickingMapContext;

}

@property (nonatomic,retain) VKLabelMarker * labelMarker;                                    //@synthesize labelMarker=_labelMarker - In the implementation block
@property (nonatomic,retain) RAPReportContext * labelMarkerPickingMapContext;                //@synthesize labelMarkerPickingMapContext=_labelMarkerPickingMapContext - In the implementation block
@property (nonatomic,readonly) RAPPlaceCorrectableString * correctableName;                  //@synthesize correctableName=_correctableName - In the implementation block
@property (nonatomic,readonly) NSString * localizedLabelMarkerPickingPrompt; 
@property (nonatomic,readonly) SCD_Struct_RA6 initialLabelMarkerPickingMapRect; 
@property (nonatomic,readonly) RAPCommentQuestion * commentQuestion;                         //@synthesize commentQuestion=_commentQuestion - In the implementation block
+(int)mapServiceAction;
-(RAPCommentQuestion *)commentQuestion;
-(void)_fillSubmittableProblem:(id)arg1 ;
-(VKLabelMarker *)labelMarker;
-(RAPReportContext *)labelMarkerPickingMapContext;
-(RAPPlaceCorrectableString *)correctableName;
-(int)_geoHandleTypeFrom:(int)arg1 ;
-(NSString *)localizedLabelMarkerPickingPrompt;
-(SCD_Struct_RA6)initialLabelMarkerPickingMapRect;
-(void)setLabelMarker:(VKLabelMarker *)arg1 ;
-(void)setLabelMarkerPickingMapContext:(RAPReportContext *)arg1 ;
-(id)_alternateMapViewContext;
-(char)isComplete;
@end

