/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:36 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class NSString;


@protocol RAPPlaceCorrectableItem <NSObject>
@property (nonatomic,readonly) NSString * localizedTitle; 
@property (getter=isEdited,nonatomic,readonly) char edited; 
@property (nonatomic,readonly) int kind; 
@property (assign,getter=isMarkedWrong,nonatomic) char markedWrong; 
@required
-(void)addObserver:(id)arg1 changeHandler:(/*^block*/id)arg2;
-(char)isEdited;
-(void)setMarkedWrong:(char)arg1;
-(void)revertCorrections;
-(char)isMarkedWrong;
-(void)removeObserver:(id)arg1;
-(int)kind;
-(NSString *)localizedTitle;

@end

