/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:43 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UITextField.h>

@protocol RAPTextFieldInputAccessoryViewDelegate;
@class UIBarButtonItem, NSString;

@interface ReportAProblemTextField : UITextField {

	id<RAPTextFieldInputAccessoryViewDelegate> _inputAccessoryViewDelegate;
	int _disabledDirection;
	UIBarButtonItem* _previousFieldBarItem;
	UIBarButtonItem* _nextFieldBarItem;
	UIBarButtonItem* _markAsIncorrectBarItem;
	char _halfWidth;
	char _markedWrongButtonEnabled;
	int _correctableItemKind;
	NSString* _originalText;

}

@property (nonatomic,retain) NSString * originalText;                                                                   //@synthesize originalText=_originalText - In the implementation block
@property (assign,nonatomic) char halfWidth;                                                                            //@synthesize halfWidth=_halfWidth - In the implementation block
@property (assign,nonatomic) int correctableItemKind;                                                                   //@synthesize correctableItemKind=_correctableItemKind - In the implementation block
@property (assign,nonatomic,__weak) id<RAPTextFieldInputAccessoryViewDelegate> inputAccessoryViewDelegate;              //@synthesize inputAccessoryViewDelegate=_inputAccessoryViewDelegate - In the implementation block
@property (assign,nonatomic) char markedWrongButtonEnabled;                                                             //@synthesize markedWrongButtonEnabled=_markedWrongButtonEnabled - In the implementation block
@property (assign,nonatomic) int addressType; 
-(void)disableDirectionButtonWithDirection:(int)arg1 ;
-(void)setCorrectableItemKind:(int)arg1 ;
-(void)setMarkedWrongButtonEnabled:(char)arg1 ;
-(int)correctableItemKind;
-(void)setInputAccessoryViewDelegate:(id<RAPTextFieldInputAccessoryViewDelegate>)arg1 ;
-(void)fieldChanged:(id)arg1 ;
-(char)markedWrongButtonEnabled;
-(void)updateInputAccessoryView;
-(void)editingBegan:(id)arg1 ;
-(void)editingEnded:(id)arg1 ;
-(void)_updateRAPTextColor;
-(void)_previousFieldBarItemTapped;
-(void)_nextFieldBarItemTapped;
-(void)markAsWrongPressed:(id)arg1 ;
-(void)doneButtonPressed:(id)arg1 ;
-(id)_newSmallSpace;
-(void)_updateNextPreviousButton;
-(void)_updateMarkAsWrongButton;
-(id<RAPTextFieldInputAccessoryViewDelegate>)inputAccessoryViewDelegate;
-(char)halfWidth;
-(void)setHalfWidth:(char)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(id)description;
-(void)setText:(id)arg1 ;
-(NSString *)originalText;
-(int)addressType;
-(void)setAddressType:(int)arg1 ;
-(void)setOriginalText:(NSString *)arg1 ;
@end

