/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:42 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UILabel.h>

@interface RoutePickingLoadingLabel : UILabel {

	char _hasSetUpFont;
	char _isUsingSmallerFont;
	char _dimmed;
	char _darkUI;

}

@property (getter=isDimmed) char dimmed;              //@synthesize dimmed=_dimmed - In the implementation block
@property (getter=isUIDark) char darkUI;              //@synthesize darkUI=_darkUI - In the implementation block
-(void)setDarkUI:(char)arg1 ;
-(char)isUIDark;
-(void)setDimmed:(char)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(char)isDimmed;
@end

