/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:36 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/RouteStepLabelListView.h>

@interface RouteMiddleStepLabelListView : RouteStepLabelListView
+(id)stringsForRoute:(id)arg1 step:(id)arg2 tableMode:(char)arg3 ;
+(id)fontsForStrings:(id)arg1 route:(id)arg2 step:(id)arg3 tableMode:(char)arg4 ;
+(id)voiceOverStringsForRoute:(id)arg1 step:(id)arg2 tableMode:(char)arg3 ;
+(id)stringsForRoute:(id)arg1 step:(id)arg2 tableMode:(char)arg3 isPrinting:(char)arg4 ;
+(id)stringsForRoute:(id)arg1 step:(id)arg2 tableMode:(char)arg3 isPrinting:(char)arg4 forAccessibility:(char)arg5 ;
@end

