/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:36 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSArray;

@interface SearchBarSearchResultSet : NSObject {

	NSArray* _results;
	unsigned _count;

}

@property (nonatomic,readonly) NSArray * results;              //@synthesize results=_results - In the implementation block
@property (nonatomic,readonly) unsigned count;                 //@synthesize count=_count - In the implementation block
-(id)initWithResults:(id)arg1 maxCount:(unsigned)arg2 ;
-(unsigned)count;
-(NSArray *)results;
@end

