/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:37 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MapKit/MKPinAnnotationView.h>

@class SearchResult;

@interface SearchResultPinAnnotation : MKPinAnnotationView {

	int _selectionBehavior;

}

@property (nonatomic,retain) SearchResult * searchResult; 
@property (assign,nonatomic) int selectionBehavior;                    //@synthesize selectionBehavior=_selectionBehavior - In the implementation block
+(id)keyPathsForValuesAffectingAppearance;
-(void)_updatePinColorForSearchResult;
-(id)initWithSearchResult:(id)arg1 reuseIdentifier:(id)arg2 ;
-(void)setSelectionBehavior:(int)arg1 ;
-(int)selectionBehavior;
-(void)dealloc;
-(void)prepareForReuse;
-(void)setSelected:(char)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)setAnnotation:(id)arg1 ;
-(void)setSearchResult:(SearchResult *)arg1 ;
-(SearchResult *)searchResult;
-(id)initWithAnnotation:(id)arg1 reuseIdentifier:(id)arg2 ;
-(void)setDragState:(unsigned)arg1 ;
-(char)isDraggable;
@end

