/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:40 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/SettingsTableViewControllerDelegate.h>
#import <UIKit/UINavigationControllerDelegate.h>

@class MainChromeViewController, SettingsTableViewController, MapsRadarComposerPresenter, AdaptivePresenter, NSSet, NSString;

@interface SettingsController : NSObject <SettingsTableViewControllerDelegate, UINavigationControllerDelegate> {

	MainChromeViewController* _owner;
	SettingsTableViewController* _table;
	char _showsEnvironments;
	char _showsRadarComposer;
	MapsRadarComposerPresenter* _radarComposerPresenter;
	AdaptivePresenter* _tablePresenter;
	AdaptivePresenter* _reportAProblemPresenter;
	char _userDesiresTraffic;
	char _viewModeSwitchingAvailable;
	NSSet* _disallowedViewModes;

}

@property (getter=isDisplayingSettings,nonatomic,readonly) char displayingSettings; 
@property (assign,nonatomic) char userDesiresTraffic;                                            //@synthesize userDesiresTraffic=_userDesiresTraffic - In the implementation block
@property (assign,nonatomic) char viewModeSwitchingAvailable;                                    //@synthesize viewModeSwitchingAvailable=_viewModeSwitchingAvailable - In the implementation block
@property (nonatomic,retain) NSSet * disallowedViewModes;                                        //@synthesize disallowedViewModes=_disallowedViewModes - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setUserDesiresTraffic:(char)arg1 ;
-(void)dropPin;
-(char)canDisplayTraffic;
-(char)userDesiresTraffic;
-(char)isDisplayingSettings;
-(NSSet *)disallowedViewModes;
-(void)setDisallowedViewModes:(NSSet *)arg1 ;
-(void)_userDefaultsDidChange;
-(void)setViewModeSwitchingAvailable:(char)arg1 ;
-(void)update3DMode;
-(void)presentFromView:(id)arg1 animated:(char)arg2 completion:(/*^block*/id)arg3 ;
-(char)showsEnvironments;
-(char)viewModeSwitchingAvailable;
-(char)showsDropPin;
-(char)canShow3DMode;
-(char)is3DModeEnabled;
-(char)isTrafficDisplayed;
-(void)toggle3D;
-(void)proceedToEnvironmentsSelector;
-(void)proceedToReportAProblem;
-(void)setTrafficDisplayed:(char)arg1 ;
-(void)presentAttributions;
-(void)_clearTableIfNeeded;
-(char)showsRadarComposer;
-(id)initWithOwner:(id)arg1 ;
-(void)dealloc;
-(void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(char)arg3 ;
-(void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(char)arg3 ;
-(int)viewMode;
-(void)_done;
-(id)mapAttribution;
-(void)dismissAnimated:(char)arg1 completion:(/*^block*/id)arg2 ;
-(void)setViewMode:(int)arg1 ;
@end

