/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:43 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/MKMapViewDelegatePrivate.h>
#import <Maps/StarkIndirectPanControllerDelegate.h>
#import <Maps/StarkMapBrowsingTrackingDelegate.h>
#import <Maps/StarkRouteGeniusModeDelegate.h>
#import <Maps/StarkChromeModeController.h>

@protocol MapsChromeViews, StarkMapBrowsingMode;
@class UINavigationItem, StarkUserTrackingButton, StarkIndirectPanController, UITapGestureRecognizer, UIBarButtonItem, MapsChromeViewController, StarkMapBrowsingTrackingController, NSString, ChromeViewController;

@interface StarkMapBrowsingModeController : NSObject <MKMapViewDelegatePrivate, StarkIndirectPanControllerDelegate, StarkMapBrowsingTrackingDelegate, StarkRouteGeniusModeDelegate, StarkChromeModeController> {

	char _didSetInitialTracking;
	id<MapsChromeViews> _views;
	UINavigationItem* _navigationItem;
	StarkUserTrackingButton* _trackingButton;
	StarkIndirectPanController* _panController;
	UITapGestureRecognizer* _exitPanRecognizer;
	char _inPanMode;
	char _freezeOverlayForNavigationStartup;
	UIBarButtonItem* _threeDItem;
	UIBarButtonItem* _zoomInItem;
	UIBarButtonItem* _zoomOutItem;
	UIBarButtonItem* _destinationsItem;
	id<StarkMapBrowsingMode> _currentMode;
	MapsChromeViewController* _chromeViewController;
	StarkMapBrowsingTrackingController* _trackingController;

}

@property (nonatomic,retain) StarkMapBrowsingTrackingController * trackingController;              //@synthesize trackingController=_trackingController - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) ChromeViewController * chromeViewController; 
-(void)willProvideAnnotationView:(id)arg1 forAnnotation:(id)arg2 ;
-(id)_searchPinsManager;
-(char)shouldTimeoutAfterDisconnect;
-(ChromeViewController *)chromeViewController;
-(id)starkChromeViewController;
-(id)overlayItemsForState:(id)arg1 ;
-(void)layoutForUnobscuredBoundsChange;
-(id)preferredFocusItem;
-(void)setChromeViewController:(ChromeViewController *)arg1 ;
-(void)becomeCurrentModeWithViews:(id)arg1 animated:(char)arg2 state:(id)arg3 fromMode:(id)arg4 ;
-(void)resignCurrentModeAnimated:(char)arg1 toMode:(id)arg2 ;
-(void)modeDidAppear:(char)arg1 ;
-(void)layoutForInteractionModelChange;
-(char)wheelChangedWithEvent:(id)arg1 ;
-(char)starkTopBarModifiesInsets;
-(void)modeWasSelected;
-(void)_handleBack:(id)arg1 ;
-(void)routeGeniusModeExpandedSign:(id)arg1 ;
-(void)routeGeniusLoadingDidFinish:(id)arg1 withError:(id)arg2 ;
-(void)trackingController:(id)arg1 changedToForcedTrackingMode:(int)arg2 ;
-(void)startRouteGeniusAnimated:(char)arg1 withProvider:(id)arg2 ;
-(void)stopRouteGeniusAnimated:(char)arg1 forNavigation:(char)arg2 ;
-(void)_updateAutohideBehavior;
-(void)_mapViewGestured;
-(void)_idleTimeoutWithNotification:(id)arg1 ;
-(void)_update3DButtonAnimated:(char)arg1 ;
-(void)_setInitialTrackingIfNeededAndPossible;
-(void)_updateZoomButtons;
-(void)_endPan;
-(void)_presentDestinations;
-(void)_toggle3D;
-(void)_startPan;
-(char)_inRouteGenius;
-(id)_currentRouteGeniusMode;
-(StarkMapBrowsingTrackingController *)trackingController;
-(void)_zoomByFactor:(float)arg1 onUserLocation:(char)arg2 ;
-(void)_startNavigationToLikelyRouteUpdater:(id)arg1 WithGuidance:(char)arg2 ;
-(void)setCurrentMode:(id)arg1 animated:(char)arg2 ;
-(void)panControllerWillBeginAnimating:(id)arg1 ;
-(void)panControllerDidEndAnimating:(id)arg1 ;
-(void)willEnterPanModeWithAnimation:(id)arg1 ;
-(void)startRouteGeniusAnimated:(char)arg1 withTracePlayer:(id)arg2 ;
-(void)setTrackingController:(StarkMapBrowsingTrackingController *)arg1 ;
-(void)mapView:(id)arg1 canEnter3DModeDidChange:(char)arg2 ;
-(void)mapView:(id)arg1 didChangeUserTrackingMode:(int)arg2 animated:(char)arg3 fromTrackingButton:(char)arg4 ;
-(void)mapView:(id)arg1 willStartRespondingToGesture:(int)arg2 animated:(char)arg3 ;
-(void)mapView:(id)arg1 didStopRespondingToGesture:(int)arg2 zoomDirection:(int)arg3 didDecelerate:(char)arg4 ;
-(void)mapView:(id)arg1 didBecomePitched:(char)arg2 ;
-(void)mapView:(id)arg1 canZoomInDidChange:(char)arg2 ;
-(void)mapView:(id)arg1 canZoomOutDidChange:(char)arg2 ;
-(void)_zoomIn;
-(void)_zoomOut;
-(void)mapView:(id)arg1 regionDidChangeAnimated:(char)arg2 ;
-(id)mapView:(id)arg1 viewForAnnotation:(id)arg2 ;
-(void)mapView:(id)arg1 didUpdateUserLocation:(id)arg2 ;
-(void)_updateNavigationItemAnimated:(char)arg1 ;
-(void)dealloc;
-(id)init;
-(id)navigationItem;
-(id)viewState;
@end

