/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:15 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/SiriViewService.app/SiriViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SVSTreeNodePropertyListSerialization : NSObject
-(id)_propertyListWithTreeNode:(id)arg1 itemPropertyListCreation:(/*^block*/ id)arg2 ;
-(id)_treeNodeWithPropertyList:(id)arg1 error:(id*)arg2 itemCreation:(/*^block*/ id)arg3 ;
-(id)propertyListWithTreeNode:(id)arg1 itemPropertyListCreation:(/*^block*/ id)arg2 ;
-(id)treeNodeWithPropertyList:(id)arg1 error:(id*)arg2 itemCreation:(/*^block*/ id)arg3 ;
@end

