/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:33:46 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreMotion/CLNotifierServiceAdapter.h>
#import <locationd/CLClientManagerProtocol.h>

@interface CLClientManagerAdapter : CLNotifierServiceAdapter <CLClientManagerProtocol>
+(id)getSilo;
-(void)setClients:(id)arg1 regionOfType:(int)arg2 to:(bool)arg3 ;
-(void)setClients:(id)arg1 significantLocationChangeTo:(bool)arg2 ;
-(id)initInSilo:(id)arg1 ;
-(void)heartAttack;
-(void)beginService;
-(void)endService;
@end

