/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:34:06 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <CoreMotion/CLIntersiloService.h>
#import <CoreMotion/CLNotifierServiceProtocol.h>

@interface CLNotifierServiceAdapter : CLIntersiloService <CLNotifierServiceProtocol> {

	map<unsigned long, int, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, int> > >* _clients;
	CLNotifierBase* _notifier;

}

@property (nonatomic,readonly) CLNotifierBase* notifier;              //@synthesize notifier=_notifier - In the implementation block
-(void)register:(R)arg1 forNotification:(id)arg2 registrationInfo:(int)arg3 :(id)arg4 ;
-(id)initInSilo:(id)arg1 ;
-(void)setAdaptedNotifier:(CLNotifierBase*)arg1 ;
-(void)unregister:(R)arg1 forNotification:(id)arg2 :(int)arg3 ;
-(void)forget:(R)arg1 :(id)arg2 ;
-(CLNotifierBase*)notifier;
-(int)notifierClientNumForCoparty:(id)arg1 ;
-(id)debugDescription;
-(void)invalidate;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

