/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:52 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PHAudioPlayerDataSource, PHAudioPlayerDelegate;
@class PHVoicemailAudioController, NSNumber, NSObject, NSString, NSTimer;

@interface PHAudioPlayer : NSObject {

	PHVoicemailAudioController* _audioController;
	NSNumber* _seekToTime;
	char _isPlaying;
	char _isPlayable;
	char _progressiveDurationAvailable;
	NSObject*<PHAudioPlayerDataSource> _dataSource;
	float _elapsedTime;
	float _playableTime;
	float _totalTime;
	id<PHAudioPlayerDelegate> _audioPlayerDelegate;
	float _progressBarWidth;
	NSString* _selectedRoute;
	NSString* _selectedRouteUID;
	NSTimer* _delayedPlaybackTimer;
	NSTimer* _progressUpdateTimer;
	unsigned long long _currentFileSize;
	unsigned long long _expectedFileSize;

}

@property (assign) char isPlaying;                                                       //@synthesize isPlaying=_isPlaying - In the implementation block
@property (assign) char isPlayable;                                                      //@synthesize isPlayable=_isPlayable - In the implementation block
@property (nonatomic,retain) NSObject*<PHAudioPlayerDataSource> dataSource;              //@synthesize dataSource=_dataSource - In the implementation block
@property (assign) float elapsedTime;                                                    //@synthesize elapsedTime=_elapsedTime - In the implementation block
@property (assign) float playableTime;                                                   //@synthesize playableTime=_playableTime - In the implementation block
@property (assign) float totalTime;                                                      //@synthesize totalTime=_totalTime - In the implementation block
@property (readonly) PHVoicemailAudioController * audioController; 
@property (assign,nonatomic) id<PHAudioPlayerDelegate> audioPlayerDelegate;              //@synthesize audioPlayerDelegate=_audioPlayerDelegate - In the implementation block
@property (assign,nonatomic) float progressBarWidth;                                     //@synthesize progressBarWidth=_progressBarWidth - In the implementation block
@property (nonatomic,copy) NSString * selectedRoute;                                     //@synthesize selectedRoute=_selectedRoute - In the implementation block
@property (nonatomic,copy) NSString * selectedRouteUID;                                  //@synthesize selectedRouteUID=_selectedRouteUID - In the implementation block
@property (assign,nonatomic) NSTimer * delayedPlaybackTimer;                             //@synthesize delayedPlaybackTimer=_delayedPlaybackTimer - In the implementation block
@property (assign,nonatomic) NSTimer * progressUpdateTimer;                              //@synthesize progressUpdateTimer=_progressUpdateTimer - In the implementation block
@property (assign) unsigned long long currentFileSize;                                   //@synthesize currentFileSize=_currentFileSize - In the implementation block
@property (assign) unsigned long long expectedFileSize;                                  //@synthesize expectedFileSize=_expectedFileSize - In the implementation block
@property (assign) char progressiveDurationAvailable;                                    //@synthesize progressiveDurationAvailable=_progressiveDurationAvailable - In the implementation block
+(id)sharedAudioPlayer;
-(void)setAudioPlayerDelegate:(id<PHAudioPlayerDelegate>)arg1 ;
-(id<PHAudioPlayerDelegate>)audioPlayerDelegate;
-(void)setProgressBarWidth:(float)arg1 ;
-(void)setSelectedRouteUID:(NSString *)arg1 ;
-(NSString *)selectedRouteUID;
-(id)initForVoicemail;
-(id)initForVoicemailGreeting;
-(void)_setupProgressUpdateTimer;
-(char)_fileExists:(id)arg1 ;
-(void)setIsPlayable:(char)arg1 ;
-(void)_handlePlayableDurationChanged:(id)arg1 ;
-(void)setPlayableTime:(float)arg1 ;
-(void)setProgressiveDurationAvailable:(char)arg1 ;
-(void)_forceUpdateProgressiveDataLengths;
-(void)_updateDurations;
-(void)setIsPlaying:(char)arg1 ;
-(void)setDelayedPlaybackTimer:(NSTimer *)arg1 ;
-(NSTimer *)delayedPlaybackTimer;
-(char)_createVoicemailAVItemIfNecessary:(id*)arg1 ;
-(void)_stopPlayingWithError:(id)arg1 ;
-(char)_updateElapsedTime;
-(void)_avControllerTimeJumped:(id)arg1 ;
-(void)_avControllerPlaybackStateDidChangeItem:(id)arg1 ;
-(void)_avControllerPlaybackDidEnd:(id)arg1 ;
-(void)_avControllerPlaybackRateChanged:(id)arg1 ;
-(void)_avControllerPlaybackInterrupted:(id)arg1 ;
-(void)_avControllerDied:(id)arg1 ;
-(NSTimer *)progressUpdateTimer;
-(float)progressBarWidth;
-(void)setProgressUpdateTimer:(NSTimer *)arg1 ;
-(float)playableTime;
-(void)setCurrentFileSize:(unsigned long long)arg1 ;
-(void)setExpectedFileSize:(unsigned long long)arg1 ;
-(char)progressiveDurationAvailable;
-(unsigned long long)currentFileSize;
-(unsigned long long)expectedFileSize;
-(void)_updateProgress;
-(void)setSelectedRoute:(NSString *)arg1 ;
-(NSString *)selectedRoute;
-(void)dealloc;
-(void)setDataSource:(NSObject*<PHAudioPlayerDataSource>)arg1 ;
-(id)init;
-(NSObject*<PHAudioPlayerDataSource>)dataSource;
-(void)stop;
-(void)_start;
-(void)start;
-(float)elapsedTime;
-(PHVoicemailAudioController *)audioController;
-(float)totalTime;
-(void)setTotalTime:(float)arg1 ;
-(void)_proximityStateChanged:(id)arg1 ;
-(char)isPlayable;
-(void)seekToTime:(float)arg1 ;
-(char)isPlaying;
-(void)setElapsedTime:(float)arg1 ;
@end

