/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:52 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobilePhone/MobilePhone-Structs.h>
#import <UIKit/UIView.h>
#import <MobilePhone/DialerLCDFieldProtocol.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol DialerLCDFieldDelegate;
@class UIButton, PHHandsetDialerNameLabelView, UILabel, NSString, UILongPressGestureRecognizer, NSLayoutConstraint, NSArray;

@interface PHHandsetDialerLCDView : UIView <DialerLCDFieldProtocol, UIGestureRecognizerDelegate> {

	char _addContactButtonVisible;
	char _deleteButtonVisible;
	char _highlighted;
	char _inCallMode;
	int _dialerType;
	UIButton* _deleteButton;
	UIButton* _addContactButton;
	id<DialerLCDFieldDelegate> _delegate;
	PHHandsetDialerNameLabelView* _nameAndLabelView;
	UILabel* _numberLabel;
	NSString* _unformattedText;
	UILongPressGestureRecognizer* _longPressRecognizer;
	NSLayoutConstraint* _numberLabelVerticalConstraint;
	NSLayoutConstraint* _nameAndLabelViewConstraint;
	NSArray* _numberLabelHorizontalConstraints;

}

@property (assign,nonatomic) int dialerType;                                                  //@synthesize dialerType=_dialerType - In the implementation block
@property (retain) UIButton * deleteButton;                                                   //@synthesize deleteButton=_deleteButton - In the implementation block
@property (retain) UIButton * addContactButton;                                               //@synthesize addContactButton=_addContactButton - In the implementation block
@property (assign,nonatomic) id<DialerLCDFieldDelegate> delegate;                             //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) char highlighted;                                                //@synthesize highlighted=_highlighted - In the implementation block
@property (assign,nonatomic) char inCallMode;                                                 //@synthesize inCallMode=_inCallMode - In the implementation block
@property (retain) PHHandsetDialerNameLabelView * nameAndLabelView;                           //@synthesize nameAndLabelView=_nameAndLabelView - In the implementation block
@property (nonatomic,retain) UILabel * numberLabel;                                           //@synthesize numberLabel=_numberLabel - In the implementation block
@property (retain) NSString * unformattedText;                                                //@synthesize unformattedText=_unformattedText - In the implementation block
@property (nonatomic,retain) UILongPressGestureRecognizer * longPressRecognizer;              //@synthesize longPressRecognizer=_longPressRecognizer - In the implementation block
@property (retain) NSLayoutConstraint * numberLabelVerticalConstraint;                        //@synthesize numberLabelVerticalConstraint=_numberLabelVerticalConstraint - In the implementation block
@property (retain) NSLayoutConstraint * nameAndLabelViewConstraint;                           //@synthesize nameAndLabelViewConstraint=_nameAndLabelViewConstraint - In the implementation block
@property (retain) NSArray * numberLabelHorizontalConstraints;                                //@synthesize numberLabelHorizontalConstraints=_numberLabelHorizontalConstraints - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setInCallMode:(char)arg1 ;
-(void)setText:(id)arg1 needsFormat:(char)arg2 ;
-(void)deleteCharacter;
-(char)inCallMode;
-(id)initWithFrame:(CGRect)arg1 forDialerType:(int)arg2 ;
-(UIButton *)addContactButton;
-(void)setAddContactButton:(UIButton *)arg1 ;
-(int)dialerType;
-(void)setDialerType:(int)arg1 ;
-(void)setName:(id)arg1 numberLabel:(id)arg2 ;
-(void)setText:(id)arg1 needsFormat:(char)arg2 name:(id)arg3 label:(id)arg4 ;
-(NSString *)unformattedText;
-(UILabel *)numberLabel;
-(id)lcdColor;
-(id)newNameAndLabelView;
-(id)newDeleteButton;
-(id)newAddContactButton;
-(void)applyLayoutConstraints;
-(void)updateNumberLabelHorizontalConstraints;
-(float)numberLabelMaximumFontSize;
-(PHHandsetDialerNameLabelView *)nameAndLabelView;
-(float)addContactButtonLeftPadding;
-(float)deleteButtonRightPadding;
-(id)numberLabelFont;
-(float)numberLabelMinimumFontSize;
-(void)setNameAndLabelView:(PHHandsetDialerNameLabelView *)arg1 ;
-(UILongPressGestureRecognizer *)longPressRecognizer;
-(void)setUnformattedText:(NSString *)arg1 ;
-(void)updateAddAndDeleteButtonForText:(id)arg1 name:(id)arg2 animated:(char)arg3 ;
-(void)_requestMakeCutCopyPasteCalloutVisible:(char)arg1 ;
-(void)_setHighlighted:(char)arg1 ;
-(void)_menuWillHide:(id)arg1 ;
-(void)_menuDidHide:(id)arg1 ;
-(void)_makeCalloutVisible:(char)arg1 ;
-(void)_displayCallout;
-(float)nameAndLabelFontSize;
-(NSLayoutConstraint *)nameAndLabelViewConstraint;
-(float)spacingBetweenNumberBaseLineAndNameTop;
-(void)setNumberLabelVerticalConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)numberLabelVerticalConstraint;
-(float)deleteButtonYOffset;
-(float)addContactButtonYOffset;
-(void)setNameAndLabelViewConstraint:(NSLayoutConstraint *)arg1 ;
-(NSArray *)numberLabelHorizontalConstraints;
-(id)generateNumberLabelHorizontalConstraints;
-(void)setNumberLabelHorizontalConstraints:(NSArray *)arg1 ;
-(void)setNumberLabel:(UILabel *)arg1 ;
-(void)setLongPressRecognizer:(UILongPressGestureRecognizer *)arg1 ;
-(void)handleLongPress:(id)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id<DialerLCDFieldDelegate>)arg1 ;
-(id<DialerLCDFieldDelegate>)delegate;
-(char)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(char)canPerformAction:(SEL)arg1 withSender:(id)arg2 ;
-(char)resignFirstResponder;
-(id)text;
-(char)canBecomeFirstResponder;
-(CGSize)intrinsicContentSize;
-(void)setHighlighted:(char)arg1 ;
-(void)copy:(id)arg1 ;
-(void)paste:(id)arg1 ;
-(char)highlighted;
-(UIButton *)deleteButton;
-(void)setDeleteButton:(UIButton *)arg1 ;
@end

