/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:52 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UIImageView;

@interface PHStarkGenericTableViewCell : UITableViewCell {

	char _showsChevron;
	char _hidesChevronWhenUnhighlighted;
	UIImageView* _chevronImageView;

}

@property (assign,nonatomic) char showsChevron;                               //@synthesize showsChevron=_showsChevron - In the implementation block
@property (assign,nonatomic) char hidesChevronWhenUnhighlighted;              //@synthesize hidesChevronWhenUnhighlighted=_hidesChevronWhenUnhighlighted - In the implementation block
@property (retain) UIImageView * chevronImageView;                            //@synthesize chevronImageView=_chevronImageView - In the implementation block
-(void)setShowsChevron:(char)arg1 ;
-(char)showsChevron;
-(UIImageView *)chevronImageView;
-(void)setHidesChevronWhenUnhighlighted:(char)arg1 ;
-(char)hidesChevronWhenUnhighlighted;
-(void)setChevronImageView:(UIImageView *)arg1 ;
-(void)dealloc;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
@end

