/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:11 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Setup/BuddyTableViewController.h>
#import <Setup/PSMagnifyControllerDelegate.h>
#import <Setup/BuddyController.h>

@protocol BuddyControllerDelegate;
@class UILabel, UIButton, UIImageView, PSMagnifyController, NSString;

@interface BuddyMagnifyController : BuddyTableViewController <PSMagnifyControllerDelegate, BuddyController> {

	UILabel* _zoomDescriptionLabel;
	UIButton* _chooseButton;
	UIImageView* _exampleImageView;
	UILabel* _standardExampleLabel;
	UILabel* _zoomedExampleLabel;
	UIButton* _standardButton;
	UIButton* _zoomedButton;
	PSMagnifyController* _magnifyController;
	id<BuddyControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<BuddyControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)controllerNeedsToRun;
+(void)commitMagnifyModeIfNeeded;
+(void)skip;
-(char)wantsNextButton;
-(void)nextPressed:(id)arg1 ;
-(void)tappedImage:(id)arg1 ;
-(void)showMagnifyControllerWithZoomedSelected:(char)arg1 ;
-(void)setDelegate:(id<BuddyControllerDelegate>)arg1 ;
-(id)init;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id<BuddyControllerDelegate>)delegate;
-(void)viewDidLayoutSubviews;
-(void)viewWillAppear:(char)arg1 ;
-(void)controllerDone;
-(void)magnifyController:(id)arg1 didFinishWithDisplayMode:(id)arg2 ;
@end

