/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:45 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSOperationQueue, NSMutableSet;

@interface _BackgroundViewRenderManager : NSObject {

	NSOperationQueue* _queue;
	NSMutableSet* _viewsInQueue;

}
+(id)sharedManager;
-(void)addViewToQueue:(id)arg1 ;
-(void)removeViewFromQueue:(id)arg1 ;
-(void)cancelAllRendering;
-(id)init;
@end

