/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:46 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <MobileCal/YearMonthView.h>

@interface LargeYearMonthView : YearMonthView
+(float)heightForInterfaceOrientation:(int)arg1 ;
-(id)dayNumberFont;
-(float)yInset;
-(char)showWeekDayInitials;
-(float)weekDayInitialsAdjustLeft;
-(float)weekDayInitialsAdjustTop;
-(float)daysXAdjustLeft;
-(float)daysYAdjustTop;
-(float)xSpacing;
-(float)ySpacing;
-(id)todayNumberFont;
-(float)circleSizeForDoubleDigit;
-(float)circleFrameYAdjustment;
-(float)todayNumberKerning;
-(float)headerXAdjust;
-(float)headerFontMaxSize;
-(float)headerFontMinSize;
-(float)headerFontKerning;
-(id)weekDayInitialsFont;
-(float)dayTextSize;
-(float)todayTextSize;
-(float)xInset;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id)headerFont;
-(float)circleSize;
@end

