/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:46 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileCal/MainViewControllerContainer.h>

@class CompactListViewController;

@interface ListViewContainerViewController : MainViewControllerContainer {

	CompactListViewController* _compactController;

}

@property (nonatomic,retain) CompactListViewController * compactController;              //@synthesize compactController=_compactController - In the implementation block
-(id)currentChildViewController;
-(id)childViewControllerForCompactWidthRegularHeight;
-(id)childViewControllerForUnknownTraits;
-(Class)childViewControllerClassForTraits:(id)arg1 ;
-(char)shouldRemoveSelfFromNavigationStackIfTraitCollectionIsUnsupported;
-(id)childViewControllerForCompactWidthCompactHeight;
-(CompactListViewController *)compactController;
-(void)setCompactController:(CompactListViewController *)arg1 ;
@end

