/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:44 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MainViewController <NSObject>
@property (assign,nonatomic) char shouldPresentEventDetailsForSelectedOccurrence; 
@optional
-(void)updateBackButtonToDate:(id)arg1;
-(void)enableGestureRecognizers;
-(void)disableGestureRecognizers;
-(float)leftBarButtonBlankFixedSpaceWidth;
-(void)updatePalette:(id)arg1;
-(id)bestDateForNewEvent;
-(char)showEventDetailsWhenNewEventAdded;
-(id)toolBarTintColor;
-(int)supportedToggleMode;
-(id)navigationBarDisplayedDateString;
-(void)updateNavigationBarDisplayedDateString;
-(void)invalidateBackButtonDate;
-(char)shouldUpdateOwnBackButtonWhenTopViewController;
-(id)updateBackButtonWhileTopViewControllerToDate:(id)arg1;
-(id)popoverSourceViewForEventDetails:(id)arg1;
-(CGRect*)popoverSourceRectForEventDetails:(id)arg1;
-(char)shouldRespondToApplicationDidBecomeActiveStateChange;
-(void)setShouldRespondToApplicationDidBecomeActiveStateChange:(char)arg1;
-(void)showNowAnimated:(char)arg1;
-(char)shouldPresentEventDetailsForSelectedOccurrence;
-(void)setShouldPresentEventDetailsForSelectedOccurrence:(char)arg1;
-(id)navigationBarTintColor;

@required
-(void)showEvent:(id)arg1 animated:(char)arg2 showDetails:(char)arg3;
-(void)showEvent:(id)arg1 animated:(char)arg2 showDetails:(char)arg3 showComments:(char)arg4;
-(void)selectDate:(id)arg1 animated:(char)arg2;
-(void)showEvent:(id)arg1 animated:(char)arg2;
-(char)allowsOverriddenRightNavigationBarItems;
-(char)allowsOverriddenToolbarItems;
-(char)isTodayVisible;
-(char)shouldPushNextLevelViewControllerWhenTodayIsVisible;
-(void)presentDetailsViewWhenReady:(id)arg1 animated:(char)arg2;

@end

