/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:44 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <UIKit/UIView.h>

@class UILabel, EKCalendarDate;

@interface MonthTitleView : UIView {

	UILabel* _titleLabel;
	EKCalendarDate* _calendarDate;

}

@property (nonatomic,retain) EKCalendarDate * calendarDate;              //@synthesize calendarDate=_calendarDate - In the implementation block
-(void)animateVisible:(char)arg1 duration:(double)arg2 completion:(/*^block*/id)arg3 ;
-(void)setCalendarDate:(EKCalendarDate *)arg1 ;
-(EKCalendarDate *)calendarDate;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setFont:(id)arg1 ;
-(id)backgroundImage;
@end

