/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:45 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <UIKit/UIView.h>

@class _UINavigationControllerPalette, WeekDayInitialsHeaderView, DayNavigationViewController;

@interface PaletteView : UIView {

	_UINavigationControllerPalette* _containingPalette;
	WeekDayInitialsHeaderView* _dayInitialsHeaderView;
	char _freezeSize;
	char _weekdayHeaderVisible;
	char _weekdayHeaderFillsHalfWidth;
	char _useCustomDayFrames;
	DayNavigationViewController* _dayScrubberController;

}

@property (nonatomic,readonly) char hasContent; 
@property (assign,nonatomic) char freezeSize;                                                  //@synthesize freezeSize=_freezeSize - In the implementation block
@property (assign,nonatomic) char weekdayHeaderVisible;                                        //@synthesize weekdayHeaderVisible=_weekdayHeaderVisible - In the implementation block
@property (assign,nonatomic) char weekdayHeaderFillsHalfWidth;                                 //@synthesize weekdayHeaderFillsHalfWidth=_weekdayHeaderFillsHalfWidth - In the implementation block
@property (nonatomic,retain) DayNavigationViewController * dayScrubberController;              //@synthesize dayScrubberController=_dayScrubberController - In the implementation block
@property (assign,nonatomic) char useCustomDayFrames;                                          //@synthesize useCustomDayFrames=_useCustomDayFrames - In the implementation block
-(void)layoutWithoutResizingPalette;
-(void)setDayHeaderFrames:(id)arg1 ;
-(void)setWeekdayHeaderVisible:(char)arg1 ;
-(void)setWeekdayHeaderFillsHalfWidth:(char)arg1 ;
-(void)setDayScrubberController:(DayNavigationViewController *)arg1 ;
-(void)setUseCustomDayFrames:(char)arg1 ;
-(char)useCustomDayFrames;
-(DayNavigationViewController *)dayScrubberController;
-(void)setFreezeSize:(char)arg1 ;
-(id)initWithNavigationPalette:(id)arg1 ;
-(void)removeAllContent;
-(void)invalidateForWindowSizeParadigmChange;
-(float)sideMargin;
-(char)weekdayHeaderVisible;
-(char)freezeSize;
-(char)weekdayHeaderFillsHalfWidth;
-(id)_generateWeekDayInitialsHeaderView;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(char)hasContent;
-(void)_localeChanged:(id)arg1 ;
@end

