/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:26 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Contacts.app/Contacts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Contacts/Contacts-Structs.h>
#import <UIKit/UIResponder.h>
#import <UIKit/UIApplicationTestingDelegate.h>
#import <Contacts/ABUnknownPersonViewControllerDelegate.h>
#import <UIKit/UIApplicationDelegate.h>

@class UIWindow, UIViewController, ContactsSplitViewController, ABPeoplePickerNavigationController, CNContact, NSMutableArray, NSDate, NSString;

@interface AppDelegate : UIResponder <UIApplicationTestingDelegate, ABUnknownPersonViewControllerDelegate, UIApplicationDelegate> {

	UIWindow* _window;
	UIViewController* _rootViewController;
	ContactsSplitViewController* _splitViewController;
	ABPeoplePickerNavigationController* _peoplePicker;
	CNContact* _restoredContact;
	CNContact* _restoredUnsavedContact;
	NSMutableArray* _receivedContactsQueue;
	NSDate* _userActivityStartDate;

}

@property (nonatomic,retain) UIWindow * window;                                              //@synthesize window=_window - In the implementation block
@property (nonatomic,retain) UIViewController * rootViewController;                          //@synthesize rootViewController=_rootViewController - In the implementation block
@property (nonatomic,retain) ContactsSplitViewController * splitViewController;              //@synthesize splitViewController=_splitViewController - In the implementation block
@property (nonatomic,retain) ABPeoplePickerNavigationController * peoplePicker;              //@synthesize peoplePicker=_peoplePicker - In the implementation block
@property (nonatomic,retain) CNContact * restoredContact;                                    //@synthesize restoredContact=_restoredContact - In the implementation block
@property (nonatomic,retain) CNContact * restoredUnsavedContact;                             //@synthesize restoredUnsavedContact=_restoredUnsavedContact - In the implementation block
@property (nonatomic,retain) NSMutableArray * receivedContactsQueue;                         //@synthesize receivedContactsQueue=_receivedContactsQueue - In the implementation block
@property (nonatomic,retain) NSDate * userActivityStartDate;                                 //@synthesize userActivityStartDate=_userActivityStartDate - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setSplitViewController:(ContactsSplitViewController *)arg1 ;
-(char)_showContactWithRecordID:(int)arg1 ;
-(CNContact *)restoredUnsavedContact;
-(CNContact *)restoredContact;
-(void)setRestoredContact:(CNContact *)arg1 ;
-(id)_vCardDataFromURL:(id)arg1 ;
-(void)_enqueueContact:(id)arg1 ;
-(void)setRestoredUnsavedContact:(CNContact *)arg1 ;
-(void)setUserActivityStartDate:(NSDate *)arg1 ;
-(NSDate *)userActivityStartDate;
-(void)_showContactCardForRecord:(void*)arg1 ;
-(NSMutableArray *)receivedContactsQueue;
-(void)setReceivedContactsQueue:(NSMutableArray *)arg1 ;
-(void)_presentNextContact;
-(void)cancelModalUnknownPerson:(id)arg1 ;
-(void)saveUnknownPerson:(id)arg1 ;
-(id)_dequeueContact;
-(void)_dismissContactAndPresentNext;
-(UIWindow *)window;
-(char)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4 ;
-(void)applicationDidBecomeActive:(id)arg1 ;
-(char)application:(id)arg1 shouldSaveApplicationState:(id)arg2 ;
-(char)application:(id)arg1 shouldRestoreApplicationState:(id)arg2 ;
-(char)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2 ;
-(char)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 ;
-(void)setWindow:(UIWindow *)arg1 ;
-(void)setRootViewController:(UIViewController *)arg1 ;
-(UIViewController *)rootViewController;
-(char)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(/*^block*/id)arg3 ;
-(char)application:(id)arg1 willContinueUserActivityWithType:(id)arg2 ;
-(void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3 ;
-(void)application:(id)arg1 willEncodeRestorableStateWithCoder:(id)arg2 ;
-(void)application:(id)arg1 didDecodeRestorableStateWithCoder:(id)arg2 ;
-(ContactsSplitViewController *)splitViewController;
-(char)application:(id)arg1 runTest:(id)arg2 options:(id)arg3 ;
-(ABPeoplePickerNavigationController *)peoplePicker;
-(void)setPeoplePicker:(ABPeoplePickerNavigationController *)arg1 ;
-(void)unknownPersonViewController:(id)arg1 didResolveToPerson:(void*)arg2 ;
@end

