/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:29 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Feedback Assistant iOS.app/Feedback Assistant iOS
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Feedback Assistant iOS/Feedback Assistant iOS-Structs.h>
#import <Feedback Assistant iOS/ACMiTunesSignInDialog.h>

@interface ACMiTunesSignInDialog_Legacy : ACMiTunesSignInDialog
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2 ;
-(void)loadView;
-(void)willPresentAlertView:(id)arg1 ;
-(CGRect)userNameFrame;
-(CGRect)passwordFrame;
-(void)handleRotation;
-(void)handleTextFieldShouldReturnOnNonPasswordField;
@end

