/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:29 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Feedback Assistant iOS.app/Feedback Assistant iOS
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Feedback Assistant iOS/ACMSignInDialogSimple.h>

@interface ACMSignInDialogSimple_Modern : ACMSignInDialogSimple {

	float _backgroundHorizontalParallaxValue;
	float _backgroundVerticalParallaxValue;

}
-(void)dealloc;
-(void)setBackgroundColor:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)backgroundColor;
-(id)init;
-(void)didReceiveMemoryWarning;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)loadView;
-(id)cancelButton;
-(void)updateViewConstraints;
-(id)imageView;
-(id)passwordField;
-(id)accountNameField;
-(id)loginButton;
-(void)setupBackgroundViewIfNeeded;
-(void)setupParallaxParameters;
-(void)setParallaxEffectForView:(id)arg1 ;
-(void)setupView;
-(void)centerHorizontallyView:(id)arg1 relativeToView:(id)arg2 ;
-(id)buttonsContainerView;
-(id)defaultBackgroundPatternImage;
@end

