/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:28 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Feedback Assistant iOS.app/Feedback Assistant iOS
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface FBALog : NSObject
+(void)logWarn:(id)arg1 ;
+(void)logDebug:(id)arg1 ;
+(int)logLevel;
+(void)logError:(id)arg1 ;
+(void)logInfo:(id)arg1 ;
+(void)log:(id)arg1 ;
@end

