/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:34:50 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/sbin/BTServer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileCoreServices/LSApplicationWorkspaceObserver.h>

@protocol UninstallObserverProtocol;
@class NSObject;

@interface UninstallObserver : LSApplicationWorkspaceObserver {

	NSObject<UninstallObserverProtocol>* _delegate;

}

@property (assign,nonatomic) NSObject<UninstallObserverProtocol> * delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)applicationsDidUninstall:(id)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(id)delegate;
@end

