/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:51 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary, NSDate;

@interface NotesRefreshController : NSObject {

	NSMutableDictionary* _lastNotesRefreshDates;
	NSDate* _lastStoresListRefreshDate;

}
+(id)sharedInstance;
-(char)notesNeedRefreshForCollectionWithId:(id)arg1 ;
-(void)refreshNotesForCollectionWithId:(id)arg1 ;
-(void)refreshAllNotesIfNeeded;
-(char)storesListNeedsRefresh;
-(void)refreshStoresList;
-(void)refreshOrphanedAccounts;
-(char)notesNeedRefresh;
-(id)_accountStore;
@end

