/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:58:58 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/FieldTest.app/FieldTest
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FieldTest/LogGenerator.h>

@class NSMutableData;

@interface EURLogGenerator : LogGenerator {

	NSMutableData* _binData;

}
-(id)getSaveContentsFromState:(id)arg1 ;
-(id)generateDlfFromState:(id)arg1 ;
-(void)dealloc;
-(id)init;
@end

