/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:58:58 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/Game Center~iphone.app/Game Center~iphone
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Game Center~iphone/Game Center~iphone-Structs.h>
#import <UIKit/UIView.h>

@class UICollectionView;

@interface _GKCollectionViewWrapperAdaptorView : UIView {

	UICollectionView* _sizingCollectionView;

}

@property (assign,nonatomic) UICollectionView * sizingCollectionView;              //@synthesize sizingCollectionView=_sizingCollectionView - In the implementation block
-(void)setSizingCollectionView:(id)arg1 ;
-(id)sizingCollectionView;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setBounds:(CGRect)arg1 ;
-(CGSize)intrinsicContentSize;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
@end

