/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:08 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileNotes/MobileNotes-Structs.h>
#import <UIKit/UIInputView.h>

@class UILabel, UISegmentedControl, UISearchBar, UIBarButtonItem;

@interface NotesFindInputView : UIInputView {

	UILabel* _resultsLabel;
	UISegmentedControl* _nextPreviousControl;
	UISearchBar* _searchBar;
	UIBarButtonItem* _controlBarButtonItem;
	UIBarButtonItem* _labelBarButtonItem;
	UIBarButtonItem* _doneBarButtonItem;
	UIBarButtonItem* _searchBarButtonItem;
	UIBarButtonItem* _leftFixedSpaceBarButtonItem;

}

@property (retain) UISearchBar * searchBar;              //@synthesize searchBar=_searchBar - In the implementation block
+(id)toolbarWithItems:(id)arg1 ;
-(void)setSegmentedControlTarget:(id)arg1 action:(SEL)arg2 ;
-(void)setDoneButtonTarget:(id)arg1 action:(SEL)arg2 ;
-(void)setSegmentedControlEnabled:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(id)searchBar;
-(void)setSearchBar:(id)arg1 ;
-(void)didEndSplitTransition;
-(void).cxx_destruct;
-(void)setLabelText:(id)arg1 ;
@end

