/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:58 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIView.h>

@class NSMutableArray, NSDateFormatter;

@interface AlarmScheduleHeaderView : UIView {

	NSMutableArray* _dateLabels;
	NSDateFormatter* _formatter;
	int _firstDayOfWeek;
	int _currentDayOfWeek;
	float _leftMargin;
	float _columnWidth;

}

@property (assign,nonatomic) int firstDayOfWeek;                //@synthesize firstDayOfWeek=_firstDayOfWeek - In the implementation block
@property (assign,nonatomic) int currentDayOfWeek;              //@synthesize currentDayOfWeek=_currentDayOfWeek - In the implementation block
@property (assign,nonatomic) float leftMargin;                  //@synthesize leftMargin=_leftMargin - In the implementation block
@property (assign,nonatomic) float columnWidth;                 //@synthesize columnWidth=_columnWidth - In the implementation block
+(float)defaultHeight;
-(void)handleLocaleChange;
-(int)currentDayOfWeek;
-(void)setCurrentDayOfWeek:(int)arg1 ;
-(void)updateDayLabelValues;
-(id)newDateLabel;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setBackgroundColor:(id)arg1 ;
-(void)layoutSubviews;
-(float)columnWidth;
-(void)setColumnWidth:(float)arg1 ;
-(void)setFirstDayOfWeek:(int)arg1 ;
-(int)firstDayOfWeek;
-(float)leftMargin;
-(void)setLeftMargin:(float)arg1 ;
@end

