/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:12 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>
#import <MobileTimer/StopWatchLapCell.h>

@class UILabel, UIView;

@interface LapPadTableViewCell : UITableViewCell <StopWatchLapCell> {

	int _lap;
	double _time;
	double _runningTotal;
	UILabel* _lapLabel;
	UILabel* _runningTotalLabel;
	UILabel* _timeLabel;
	UIView* _keylineView;
	int _cellPosition;

}

@property (assign,nonatomic) int lap;                          //@synthesize lap=_lap - In the implementation block
@property (assign,nonatomic) double time;                      //@synthesize time=_time - In the implementation block
@property (assign,nonatomic) double runningTotal;              //@synthesize runningTotal=_runningTotal - In the implementation block
@property (assign,nonatomic) int cellPosition;                 //@synthesize cellPosition=_cellPosition - In the implementation block
+(float)rightLabelCenterXToTrailing;
+(float)leftLabelCenterXToLeading;
+(float)rowHeight;
-(void)handleLocaleChange;
-(void)setLap:(int)arg1 ;
-(void)setRunningTotal:(double)arg1 ;
-(void)internalSetBackgroundColor:(id)arg1 ;
-(void)setupLapFormatter;
-(void)resetLapFormatter;
-(id)_accessibilityFormatTime:(double)arg1 showHours:(BOOL*)arg2 showSubseconds:(BOOL)arg3 ;
-(int)lap;
-(double)runningTotal;
-(void)setCellPosition:(int)arg1 ;
-(int)cellPosition;
-(void)dealloc;
-(void)setBackgroundColor:(id)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(void)prepareForReuse;
-(void)setTime:(double)arg1 ;
-(double)time;
@end

