/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:10 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSTimer, NSDate, NSError;

@interface PageLoadTestStatistics : NSObject {

	int _framesToLoad;
	int _onloadEventsHandled;
	BOOL _pendingResourceLoad;
	NSTimer* _waitForNewPageLoadEventsTimer;
	NSDate* _firstVisualLayoutDate;
	NSDate* _loadStartDate;
	NSDate* _lastOnloadEventDate;
	NSDate* _mainFrameLoadDate;
	NSDate* _lastResourceLoadDate;
	NSDate* _lastPageLoadEventDate;
	NSError* _loadError;
	/*^block*/ id _callbackBlock;

}

@property (nonatomic,retain) NSDate * pageLoadFirstVisualLayoutDate;              //@synthesize firstVisualLayoutDate=_firstVisualLayoutDate - In the implementation block
@property (nonatomic,retain) NSDate * pageLoadStartDate;                          //@synthesize loadStartDate=_loadStartDate - In the implementation block
@property (nonatomic,retain) NSDate * pageLoadLastOnloadEventDate;                //@synthesize lastOnloadEventDate=_lastOnloadEventDate - In the implementation block
@property (nonatomic,retain) NSDate * pageLoadMainFrameLoadDate;                  //@synthesize mainFrameLoadDate=_mainFrameLoadDate - In the implementation block
@property (nonatomic,retain) NSDate * pageLoadLastResourceLoadDate;               //@synthesize lastResourceLoadDate=_lastResourceLoadDate - In the implementation block
@property (nonatomic,retain) NSDate * pageLoadLastPageLoadEventDate;              //@synthesize lastPageLoadEventDate=_lastPageLoadEventDate - In the implementation block
@property (nonatomic,retain) NSError * pageLoadError;                             //@synthesize loadError=_loadError - In the implementation block
@property (nonatomic,copy) id pageLoadTestStatisticsCallbackBlock;                //@synthesize callbackBlock=_callbackBlock - In the implementation block
+(void)setRestInterval:(double)arg1 ;
-(id)pageLoadError;
-(id)pageLoadStartDate;
-(id)pageLoadLastPageLoadEventDate;
-(id)pageLoadFirstVisualLayoutDate;
-(void)_cancelWaitForNewPageLoadEventsTimer;
-(void)_maybePageLoadFinishedForTests;
-(void)handledOnloadEvents;
-(void)_pageLoadFinishedForTests;
-(BOOL)_pageLoadEventsAreStillPending;
-(void)_scheduleWaitForNewPageLoadEventsTimer;
-(void)_waitForNewPageLoadEventsTimerFired:(id)arg1 ;
-(void)finishedFirstVisualLayout;
-(void)finishedLoadingMainFrame;
-(void)finishedLoadingResources;
-(void)startedLoadingResources;
-(void)startedPageLoad;
-(void)startedLoadingFrame:(BOOL)arg1 ;
-(void)finishedLoadingFrameWithError:(id)arg1 isMainFrame:(BOOL)arg2 ;
-(void)setPageLoadFirstVisualLayoutDate:(id)arg1 ;
-(void)setPageLoadStartDate:(id)arg1 ;
-(id)pageLoadLastOnloadEventDate;
-(void)setPageLoadLastOnloadEventDate:(id)arg1 ;
-(id)pageLoadMainFrameLoadDate;
-(void)setPageLoadMainFrameLoadDate:(id)arg1 ;
-(id)pageLoadLastResourceLoadDate;
-(void)setPageLoadLastResourceLoadDate:(id)arg1 ;
-(void)setPageLoadLastPageLoadEventDate:(id)arg1 ;
-(void)setPageLoadError:(id)arg1 ;
-(/*^block*/ id)pageLoadTestStatisticsCallbackBlock;
-(void)setPageLoadTestStatisticsCallbackBlock:(/*^block*/ id)arg1 ;
-(void)dealloc;
-(id)initWithCallback:(/*^block*/ id)arg1 ;
@end

