/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:11 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol WebClipDelegate
@optional
-(void)webClip:(id)arg1 iconRequestDidFinishWithImage:(id)arg2 precomposed:(BOOL)arg3;
-(void)webClip:(id)arg1 startupImageRequestDidFinishWithImage:(id)arg2;
-(void)webClip:(id)arg1 startupLandscapeImageRequestDidFinishWithImage:(id)arg2;
@end

