/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:17 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Videos.app/Videos
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Videos/VideosDetailViewController.h>

@class VideosTVEpisodesTableViewController, VideosDetailsTextViewController, VideosRelatedStoreItemsCollectionViewController, MPUNotificationObserver, NSArray, MPMediaItem;

@interface VideosTVSeasonDetailViewController : VideosDetailViewController {

	VideosTVEpisodesTableViewController* _episodesViewController;
	VideosDetailsTextViewController* _detailsViewController;
	VideosRelatedStoreItemsCollectionViewController* _relatedViewController;
	MPUNotificationObserver* _detailsTextViewContentSizeObserver;
	NSArray* _segments;
	MPMediaItem* _representativeItem;

}

@property (nonatomic,retain) VideosTVEpisodesTableViewController * episodesViewController;                         //@synthesize episodesViewController=_episodesViewController - In the implementation block
@property (nonatomic,retain) VideosDetailsTextViewController * detailsViewController;                              //@synthesize detailsViewController=_detailsViewController - In the implementation block
@property (nonatomic,retain) VideosRelatedStoreItemsCollectionViewController * relatedViewController;              //@synthesize relatedViewController=_relatedViewController - In the implementation block
@property (nonatomic,retain) MPUNotificationObserver * detailsTextViewContentSizeObserver;                         //@synthesize detailsTextViewContentSizeObserver=_detailsTextViewContentSizeObserver - In the implementation block
@property (nonatomic,copy) NSArray * segments;                                                                     //@synthesize segments=_segments - In the implementation block
@property (nonatomic,retain) MPMediaItem * representativeItem;                                                     //@synthesize representativeItem=_representativeItem - In the implementation block
+(char)shouldShowDownloadProgress;
-(void)_allowsStorePurchaseDidChange:(id)arg1 ;
-(void)_updateDetailsViewController;
-(void)reloadSegments;
-(VideosDetailsTextViewController *)detailsViewController;
-(VideosRelatedStoreItemsCollectionViewController *)relatedViewController;
-(void)_updateRelatedViewController;
-(id)localizedTitleForSegment:(unsigned)arg1 ;
-(id)viewControllerForSegment:(unsigned)arg1 ;
-(void)setDetailsViewController:(VideosDetailsTextViewController *)arg1 ;
-(void)setRelatedViewController:(VideosRelatedStoreItemsCollectionViewController *)arg1 ;
-(void)setRepresentativeItem:(MPMediaItem *)arg1 ;
-(VideosTVEpisodesTableViewController *)episodesViewController;
-(void)setEpisodesViewController:(VideosTVEpisodesTableViewController *)arg1 ;
-(MPUNotificationObserver *)detailsTextViewContentSizeObserver;
-(void)setDetailsTextViewContentSizeObserver:(MPUNotificationObserver *)arg1 ;
-(MPMediaItem *)representativeItem;
-(void)dealloc;
-(void)reloadData;
-(void)viewDidLayoutSubviews;
-(unsigned)numberOfSegments;
-(id)initWithDataSource:(id)arg1 ;
-(NSArray *)segments;
-(void)setSegments:(NSArray *)arg1 ;
@end

