/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:16 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Videos.app/Videos
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MediaPlayer/MPQueryPlaybackContext.h>

@interface VideosPlaybackContext : MPQueryPlaybackContext {

	double _startTimeForFirstItem;

}

@property (assign,nonatomic) double startTimeForFirstItem;              //@synthesize startTimeForFirstItem=_startTimeForFirstItem - In the implementation block
+(Class)queueFeederClass;
-(double)startTimeForFirstItem;
-(void)setStartTimeForFirstItem:(double)arg1 ;
-(id)initWithMediaItem:(id)arg1 ;
-(id)initWithQuery:(id)arg1 ;
@end

