/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:16 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Videos.app/Videos
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <Videos/Videos-Structs.h>
@class NSObject, NSString;

@interface VideosUserNotification : NSObject {

	/*^block*/id _completionHandler;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	CFDictionaryRef _notificationDictionary;
	CFUserNotificationRef _userNotification;

}

@property (nonatomic,copy) NSString * title; 
@property (nonatomic,copy) NSString * message; 
@property (nonatomic,copy) id completionHandler; 
-(void)_setValue:(id)arg1 forUserNotificationKey:(CFStringRef)arg2 ;
-(void)_redisplayIfNeeded;
-(void)_dismissWithResponseDictionary:(id)arg1 flags:(unsigned long)arg2 ;
-(id)buttonTitleForKey:(CFStringRef)arg1 ;
-(void)setButtonTitle:(id)arg1 forKey:(CFStringRef)arg2 ;
-(void)cancel;
-(void)show;
-(void)dealloc;
-(id)init;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)title;
-(id)completionHandler;
-(NSString *)message;
-(void)setMessage:(NSString *)arg1 ;
-(void)setCompletionHandler:(id)arg1 ;
-(void)_cancelUserNotification;
@end

