/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:17 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Videos.app/Videos
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MediaPlayerUI/MPUExtrasRootViewController.h>
#import <Videos/VideosTraitsOverridingEnvironment.h>
#import <Videos/VideosPlaybackOrientationOverride.h>

@class UITraitCollection, NSString;

@interface VideosExtrasRootViewController : MPUExtrasRootViewController <VideosTraitsOverridingEnvironment, VideosPlaybackOrientationOverride> {

	UITraitCollection* _overrideTraitCollection;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy) UITraitCollection * overrideTraitCollection; 
@property (nonatomic,copy) UITraitCollection * overrideTraitCollection;              //@synthesize overrideTraitCollection=_overrideTraitCollection - In the implementation block
-(unsigned)overrideOrientationsForPlaybackViewController:(id)arg1 ;
-(id)traitCollection;
-(UITraitCollection *)overrideTraitCollection;
-(void)setOverrideTraitCollection:(UITraitCollection *)arg1 ;
@end

