/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:09 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Preferences.app/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSListController.h>
#import <Preferences/EAAccessoryDelegate.h>

@class EAAccessory, NSString;

@interface AccessoryDetailsController : PSListController <EAAccessoryDelegate> {

	EAAccessory* _accessory;
	char _shouldEscape;
	char _finishedAppearing;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_accessoryDidUpdate:(id)arg1 ;
-(void)findAppForAccessory;
-(void)accessoryDidDisconnect:(id)arg1 ;
-(id)firmwareRevision;
-(id)hardwareRevision;
-(id)bonjourName;
-(void)dealloc;
-(id)init;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)viewDidAppear:(char)arg1 ;
-(void)connect;
-(void)disconnect;
-(id)modelNumber;
-(id)manufacturer;
-(id)serialNumber;
-(id)specifiers;
@end

