/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:09 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Preferences.app/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSListController.h>
#import <Preferences/FMFSessionDelegate.h>

@class NSDictionary, NSMutableArray, NSArray, UIActionSheet, UIAlertView, NSMutableDictionary, NSDate, ACAccountStore, ACAccount, NSOperationQueue, FMFSession, FMFDevice, NSNumber, NSString;

@interface LocationServicesListController : PSListController <FMFSessionDelegate> {

	NSDictionary* _locationEntitiesDetails;
	NSMutableArray* _coalescedSystemServices;
	NSArray* _ignoredLocationEntities;
	UIActionSheet* _locationConfirmationSheet;
	UIAlertView* _locationConfirmationAlert;
	char _locationSwitchedAlertButtons;
	char _deferredRefreshDueToConfirm;
	char _locationNotificationsEnabled;
	char _locationDetailSpecifiersGroupOptional;
	NSMutableDictionary* _coalesceAppKeys;
	NSDate* _twentyFourHoursAgo;
	ACAccountStore* _accountStore;
	ACAccount* _primaryAccount;
	NSOperationQueue* _locationSharingOperationQueue;
	FMFSession* _locationSharingSession;
	FMFDevice* _locationSharingDevice;
	NSNumber* _locationSharingEnabled;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)isLocationRestricted;
+(char)isCoreRoutineAuthorized;
+(void)setCoreRoutineAuthorized:(char)arg1 ;
-(void)updateRecentlyUsedDate;
-(void)updateForApplicationDidBecomeActive:(id)arg1 ;
-(void)profileNotification:(id)arg1 ;
-(void)stopLocationStatusUpdates;
-(int)locationUsageForEntity:(id)arg1 ;
-(void)setUsage:(int)arg1 forCell:(id)arg2 ;
-(void)setAuthLevel:(unsigned)arg1 forCell:(id)arg2 ;
-(int)locationUsageBasedOnDetails:(id)arg1 ;
-(void)_setLocationServicesEnabled:(char)arg1 ;
-(char)isFindMyFriendsModificationAllowed;
-(void)refreshLinkStatusInParent;
-(void)_cancelConfirmDisableForSpecifier:(id)arg1 ;
-(id)locationSharingSpecifiers;
-(id)locationDetailSpecifiers;
-(void)updateLocationSharingSpecifiersWithReload:(char)arg1 ;
-(void)updateFindMyFriendsStateBasedOnRestriction;
-(void)confirmationClickedButtonAtIndex:(int)arg1 ;
-(void)disableLocationServicesAfterConfirm:(id)arg1 ;
-(void)confirmationActionWithSpecifier:(id)arg1 ;
-(char)_isFindMyDeviceSpecifier:(id)arg1 ;
-(void)disableAfterLoginConfirmation:(id)arg1 ;
-(void)_setEntityAuthorized:(char)arg1 specifier:(id)arg2 ;
-(void)updateSpecifiersForImposedSettingsWithReload:(char)arg1 ;
-(void)updateMutableStateBasedOnRestriction;
-(void)updateMutableStateForLocationSharing;
-(id)isLocationServicesEnabled:(id)arg1 ;
-(void)updateSpecifiersForImposedSettings;
-(id)hiddenBundleIdentifiers;
-(id)localizedDisplayNameForBundleID:(id)arg1 ;
-(void)startLocationStatusUpdates;
-(char)_shouldEnableLocationSharingSpecifier;
-(void)_locationSharingSpecifierWasTapped:(id)arg1 ;
-(char)isLocationSharingEnabled;
-(id)locationSharingDevice;
-(char)isLocationSharingModificationAllowed;
-(void)setLocationServicesEnabled:(id)arg1 specifier:(id)arg2 ;
-(id)locationSharingOperationQueue;
-(id)locationSharingSession;
-(unsigned long long)locationSharingTimeout;
-(void)mainThreadDidChangeActiveLocationSharingDevice:(id)arg1 ;
-(void)mainThreadConnectionError:(id)arg1 ;
-(void)mainThreadDidUpdateHidingStatus:(char)arg1 ;
-(void)updateLocationUsage;
-(id)isEntityAuthorized:(id)arg1 ;
-(void)setEntityAuthorized:(id)arg1 specifier:(id)arg2 ;
-(void)showLocationPrivacyPage;
-(void)dealloc;
-(id)init;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)viewWillAppear:(char)arg1 ;
-(id)primaryAccount;
-(id)accountStore;
-(void)connectionError:(id)arg1 ;
-(void)didUpdateHidingStatus:(char)arg1 ;
-(void)didChangeActiveLocationSharingDevice:(id)arg1 ;
-(id)specifiers;
-(void)willBecomeActive;
@end

