/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:09 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Preferences.app/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/LocationIndicatorExplanationView.h>

@class UILabel;

@interface LocationIndicatorSystemExplanationView : LocationIndicatorExplanationView {

	UILabel* _additionalInfoLabel;

}
-(void)layoutForWidth:(float)arg1 inTableView:(id)arg2 ;
-(id)initWithSpecifier:(id)arg1 ;
-(void)dealloc;
-(float)preferredHeightForWidth:(float)arg1 inTableView:(id)arg2 ;
@end

