/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:21 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ADBooksJSO_Bindings <JSExport>
@optional
-(void)addPDF:(id)arg1 replyTo:(id)arg2 __JS_EXPORT_AS__addPDF:(id)arg3;

@required
-(void)addPDF:(id)arg1 replyTo:(id)arg2;

@end

