/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:22 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableArray;

@interface ADResourceDownloader : NSObject {

	char _allowsConcurrentDownloads;
	NSMutableArray* _activeJobs;
	NSMutableArray* _downloadQueue;

}

@property (assign,nonatomic) char allowsConcurrentDownloads;              //@synthesize allowsConcurrentDownloads=_allowsConcurrentDownloads - In the implementation block
@property (nonatomic,retain) NSMutableArray * activeJobs;                 //@synthesize activeJobs=_activeJobs - In the implementation block
@property (nonatomic,retain) NSMutableArray * downloadQueue;              //@synthesize downloadQueue=_downloadQueue - In the implementation block
-(void)downloadRequestJob:(id)arg1 ;
-(NSMutableArray *)activeJobs;
-(char)allowsConcurrentDownloads;
-(void)_processNextJob;
-(id)jobForConnection:(id)arg1 ;
-(void)setAllowsConcurrentDownloads:(char)arg1 ;
-(void)insertJobBarrier:(/*^block*/id)arg1 ;
-(void)cancelRequestForURL:(id)arg1 ;
-(void)setActiveJobs:(NSMutableArray *)arg1 ;
-(void)setDownloadQueue:(NSMutableArray *)arg1 ;
-(void)dealloc;
-(id)init;
-(void)connection:(id)arg1 didFailWithError:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 ;
-(void)connectionDidFinishLoading:(id)arg1 ;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2 ;
-(NSMutableArray *)downloadQueue;
-(void)cancelRequest:(id)arg1 ;
-(id)connection:(id)arg1 willCacheResponse:(id)arg2 ;
-(void)cancelAllRequests;
-(void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 ;
@end

