/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:21 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/AdSheet.app/AdSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class NSNumber, NSString, NSArray;


@protocol ADStoreItemJSO_Bindings <JSExport>
@property (nonatomic,readonly) NSNumber * adamId; 
@property (nonatomic,readonly) NSString * title; 
@property (nonatomic,readonly) NSArray * offers; 
@property (nonatomic,readonly) NSArray * previews; 
@required
-(NSArray *)previews;
-(NSArray *)offers;
-(NSString *)title;
-(NSNumber *)adamId;

@end

