/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:48 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <MobileMail/GenericSource.h>

@class MFMailMessageStore, NSString, NSArray;

@interface MailboxSource : GenericSource {

	MFMailMessageStore* _store;
	NSString* _uniqueID;
	NSString* _originalPath;
	CFDictionaryRef _messageCache;
	CFSetRef _messagesRemovedByUser;
	unsigned _protectedDataIsAvailable : 1;
	unsigned _shouldThread : 1;
	NSArray* _generalObservationTokens;
	NSArray* _storeObservationTokens;

}

@property (nonatomic,retain) MFMailMessageStore * store;              //@synthesize store=_store - In the implementation block
-(char)representsMailboxUid:(id)arg1 ;
-(int)correspondingType;
-(char)supportsSearch;
-(id)mailboxUids;
-(char)isBaseSource;
-(void)setLastViewedMessage:(id)arg1 ;
-(char)supportsDeleteAll;
-(char)deleteMovesToTrash;
-(char)supportsMarkAll;
-(id)accountForAutoFetch;
-(void)markAllMessagesAsViewed;
-(void)markAllMessagesAsNotViewed;
-(void)markAllMessagesAsFlagged;
-(void)markAllMessagesAsNotFlagged;
-(char)shouldShowUnreadCount;
-(char)shouldCompactOnFetch;
-(id)lastViewedMessage;
-(id)messageForMessageID:(id)arg1 ;
-(id)uniqueIDForStorage;
-(char)representsMailboxID:(unsigned)arg1 ;
-(void)reloadPreferences;
-(void)setProtectedDataAvailable:(char)arg1 ;
-(void)_conversationHasMerged:(id)arg1 ;
-(void)emptyTrashAsNeeded;
-(unsigned)currentFetchWindow;
-(int)fetchMobileSynchronously:(unsigned)arg1 preservingUID:(id)arg2 options:(unsigned)arg3 error:(id*)arg4 ;
-(CFDictionaryRef)copySendersByLibraryIDForConversation:(long long)arg1 ;
-(id)messageForMessageInfo:(id)arg1 cacheIfNotAlready:(char)arg2 ;
-(id)cachedMessageForMessageInfo:(id)arg1 ;
-(id)bulletinsContext;
-(unsigned)remoteMessageCount;
-(unsigned)onlyRemoteUnreadCount;
-(unsigned)remoteAndLocalUnreadCount;
-(void)markAllMessagesAsDeletedOrArchived:(unsigned)arg1 withObserver:(id)arg2 ;
-(char)needsFetch;
-(char)shouldThreadConversations;
-(void)registerForGeneralNotifications;
-(void)unregisterForStoreNotifications;
-(void)unregisterForGeneralNotifications;
-(void)_resetSourceAfterAccountsChange;
-(void)_conversationFlagsChanged:(id)arg1 ;
-(void)_storeMessageFlagsChanged:(id)arg1 ;
-(void)_storeAddedMessages:(id)arg1 ;
-(void)_storeRemovedMessages:(id)arg1 ;
-(void)_forwardNotification:(id)arg1 ;
-(void)registerForNotificationsForStore:(id)arg1 ;
-(id)_copyObjectsByApplyingPendingChangesToObjects:(id)arg1 ;
-(id)_copyMessageInfosByApplyingPendingChangesToMessageInfos:(id)arg1 ;
-(id)_messageWithLibraryID:(unsigned)arg1 ;
-(unsigned)_messageCountForFetch;
-(void)_reallyDeleteAllMessagesWithObserver:(id)arg1 ;
-(void)_addAllMessageChangeSetWithOperation:(id)arg1 ;
-(void)_forwardNotification:(id)arg1 userInfo:(id)arg2 ;
-(void)_updateCachedMessage:(id)arg1 ;
-(id)_copyMessagesByApplyingPendingChangesToMessages:(id)arg1 ;
-(id)copyMessageInfosForConversationsContainingMessagesMatchingCriterion:(id)arg1 ;
-(int)fetchNumOlderMessages:(unsigned)arg1 preservingUID:(id)arg2 ;
-(id)remoteIDsUsingSearchContext:(id)arg1 limit:(unsigned)arg2 error:(id*)arg3 ;
-(id)equivalentCriterion;
-(id)uniqueIDForStatus;
-(char)supportsFlagging;
-(id)noMessagesLabelText;
-(char)shouldIncludeWholeThreads;
-(char)shouldPlayNewMailSound;
-(char)canLoadOlderMessages;
-(MFMailMessageStore *)store;
-(void)setStore:(MFMailMessageStore *)arg1 ;
-(unsigned)messageCount;
-(void)dealloc;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(char)isProtectedDataAvailable;
-(void)close;
-(id)_store;
-(void)applyChanges;
-(void)open;
-(void)flushCaches;
-(id)diagnosticDescription;
-(id)lastViewedMessageDate;
-(char)supportsArchiving;
-(char)shouldArchiveByDefault;
-(char)shouldGrowFetchWindow;
-(id)copyMessagesWithRemoteIDs:(id)arg1 options:(unsigned)arg2 ;
-(char)canFetchSearchResults;
-(int)fetchMessagesMatchingCriterion:(id)arg1 limit:(unsigned)arg2 ;
-(char)supportsThreadNotifications;
-(id)initWithMailbox:(id)arg1 ;
-(id)mailboxName;
-(id)copyMessageInfosMatchingCriterion:(id)arg1 ;
-(long long)oldestKnownConversation;
@end

