/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:47 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/MessageViewController.h>

@protocol MFAttachmentDataProvider;
@interface MFMessageAttachmentViewController : MessageViewController {

	id<MFAttachmentDataProvider> _provider;

}

@property (nonatomic,retain) id<MFAttachmentDataProvider> provider;              //@synthesize provider=_provider - In the implementation block
-(void)dealloc;
-(void)viewDidDisappear:(char)arg1 ;
-(id<MFAttachmentDataProvider>)provider;
-(void)setProvider:(id<MFAttachmentDataProvider>)arg1 ;
@end

