/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:49 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/NSXPCListenerDelegate.h>

@class NSLock, NSMutableArray, MFWeakReferenceHolder, NSXPCListener, NSArray, NSString;

@interface MFXPCEndpointListener : NSObject <NSXPCListenerDelegate> {

	NSLock* _lock;
	NSMutableArray* _clientInfos;
	MFWeakReferenceHolder* _endpointHolder;
	NSXPCListener* _listener;

}

@property (nonatomic,retain) NSXPCListener * listener;                //@synthesize listener=_listener - In the implementation block
@property (nonatomic,retain,readonly) NSArray * clients; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithEndpointInfo:(id)arg1 ;
-(void)removeClientInfo:(id)arg1 ;
-(void)addClientInfo:(id)arg1 ;
-(void)dealloc;
-(NSString *)description;
-(char)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
-(NSXPCListener *)listener;
-(void)setListener:(NSXPCListener *)arg1 ;
-(id)endpointInfo;
-(NSArray *)clients;
@end

