/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:47 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSArray, MFMessageCriterion;

@interface SearchOrderMessageContext : NSObject {

	unsigned _rankValue;
	int _generation;
	unsigned _options;
	NSArray* _primaryTerms;
	MFMessageCriterion* _dateCriterion;
	MFMessageCriterion* _unreadCriterion;
	unsigned _hasTerms : 1;
	unsigned _cached : 1;

}

@property (nonatomic,copy,readonly) NSArray * primaryTerms;                              //@synthesize primaryTerms=_primaryTerms - In the implementation block
@property (nonatomic,readonly) unsigned options;                                         //@synthesize options=_options - In the implementation block
@property (nonatomic,retain,readonly) MFMessageCriterion * dateCriterion;                //@synthesize dateCriterion=_dateCriterion - In the implementation block
@property (nonatomic,retain,readonly) MFMessageCriterion * unreadCriterion;              //@synthesize unreadCriterion=_unreadCriterion - In the implementation block
-(NSArray *)primaryTerms;
-(MFMessageCriterion *)dateCriterion;
-(MFMessageCriterion *)unreadCriterion;
-(void)dealloc;
-(unsigned)options;
@end

