/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:34:29 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/libexec/routined
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSUUID, NSDate;

@interface RTStateTransitionRouteHistogramElement : NSObject {

	NSUUID* _routeUUID;
	int _visitCount;
	NSDate* _lastUsed;

}

@property (nonatomic,retain) NSUUID * routeUUID;              //@synthesize routeUUID=_routeUUID - In the implementation block
@property (assign,nonatomic) int visitCount;                  //@synthesize visitCount=_visitCount - In the implementation block
@property (nonatomic,retain) NSDate * lastUsed;               //@synthesize lastUsed=_lastUsed - In the implementation block
-(id)routeUUID;
-(void)setRouteUUID:(id)arg1 ;
-(void)setLastUsed:(id)arg1 ;
-(id)initWithRoute:(id)arg1 lastUsed:(id)arg2 ;
-(id)lastUsed;
-(void).cxx_destruct;
-(void)setVisitCount:(int)arg1 ;
-(int)visitCount;
@end

