/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:13 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/Preferences.app/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface AlertStyleView : UIView {

	UIImageView* _selectionImage;
	UILabel* _alertName;
	BOOL _isSelected;
	UIImageView* _alertStyleImageContentView;

}

@property (nonatomic,retain) UIImageView * alertStyleImageContentView;              //@synthesize alertStyleImageContentView=_alertStyleImageContentView - In the implementation block
@property (nonatomic,retain) UIImageView * selectionImage;                          //@synthesize selectionImage=_selectionImage - In the implementation block
@property (nonatomic,retain) UILabel * alertName;                                   //@synthesize alertName=_alertName - In the implementation block
@property (assign,nonatomic) BOOL isSelected;                                       //@synthesize isSelected=_isSelected - In the implementation block
+(id)selectionImageForView:(id)arg1 ;
-(id)alertStyleImageContentView;
-(void)setAlertStyleImageContentView:(id)arg1 ;
-(id)selectionImage;
-(void)setSelectionImage:(id)arg1 ;
-(id)alertName;
-(void)setAlertName:(id)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithType:(id)arg1 ;
-(void)sizeToFit;
-(BOOL)isSelected;
-(void)setIsSelected:(BOOL)arg1 ;
@end

