/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:13 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/Preferences.app/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/LocationServicesListController.h>

@class PSSpecifier, RTRoutineManager;

@interface LocationCoreRoutineListController : LocationServicesListController {

	PSSpecifier* _coreRoutineSpecifier;
	id _coreRoutineSettings;
	id _cachedParentController;
	RTRoutineManager* _routineManager;

}

@property (retain) id cachedParentController;                                //@synthesize cachedParentController=_cachedParentController - In the implementation block
@property (nonatomic,retain) RTRoutineManager * routineManager;              //@synthesize routineManager=_routineManager - In the implementation block
-(void)updateSpecifiersForImposedSettings;
-(void)stopLocationStatusUpdates;
-(void)startLocationStatusUpdates;
-(void)updateLocationUsage;
-(void)setStatusEnabled:(id)arg1 specifier:(id)arg2 ;
-(id)isStatusEnabled:(id)arg1 ;
-(void)setCachedParentController:(id)arg1 ;
-(id)cachedParentController;
-(void)setCoreRoutineEnabled:(id)arg1 specifier:(id)arg2 ;
-(id)isCoreRoutineEnabled:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)setRoutineManager:(id)arg1 ;
-(id)routineManager;
-(id)specifiers;
@end

