/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:14 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/Preferences.app/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/PSListController.h>

@class PSSpecifier;

@interface SettingsNetworkRoamingController : PSListController {

	PSSpecifier* _voiceRoamingSpecifier;
	PSSpecifier* _dataRoamingSpecifier;
	PSSpecifier* _cdmaRoamingSpecifier;

}
-(id)getDataRoamingStatus:(id)arg1 ;
-(void)setDataRoamingEnabled:(id)arg1 specifier:(id)arg2 ;
-(void)setCDMARoamingEnabled:(id)arg1 specifier:(id)arg2 ;
-(id)getCDMARoamingStatus:(id)arg1 ;
-(id)_voiceRoamingFooterTextWithVoiceRoamingOn:(BOOL)arg1 ;
-(void)setVoiceRoamingEnabled:(id)arg1 specifier:(id)arg2 ;
-(id)getVoiceRoamingStatus:(id)arg1 ;
-(id)dataRoamingSpecifiers;
-(id)cdmaRoamingSpecifiers;
-(void)reloadRoamingStatus;
-(void)dealloc;
-(id)init;
-(void)newCarrierNotification;
-(id)specifiers;
@end

