/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:03 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface InterruptibleAnimation : NSObject {

	/*^block*/ id _completionBlock;

}
-(void)performWithDuration:(double)arg1 animations:(/*^block*/ id)arg2 completion:(/*^block*/ id)arg3 ;
-(void)interrupt;
-(void)dealloc;
-(void).cxx_destruct;
@end

