/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:01 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/AudioOutputSettingsManagerObserver.h>
#import <Maps/MNVoiceControllerObserver.h>

@interface MNNavigationAudioFeedbackCollector : NSObject <AudioOutputSettingsManagerObserver, MNVoiceControllerObserver> {

	SCD_Struct_MN27* _audioFeedback;
	BOOL _viewingAudioSettings;
	BOOL _sessionDidStart;

}
-(void)updateViewingAudioSettings:(BOOL)arg1 ;
-(void)updateCurrentAudioRouteChanged;
-(void)updateHFPPreferenceChanged:(BOOL)arg1 ;
-(void)voiceController:(id)arg1 didStartSpeakingPrompt:(id)arg2 ;
-(void)voiceController:(id)arg1 didActivateAudioSession:(BOOL)arg2 ;
-(void)_updateAvailableRoutesProperties;
-(void)_updateRoutesPropertiesAtEndOfSession;
-(void)audioOutputSettingsManager:(id)arg1 updatedSettings:(id)arg2 ;
-(SCD_Struct_MN27*)audioFeedback;
-(void)dealloc;
-(void)endSession;
-(void)startSession;
@end

