/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:02 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/MNGuidanceManager.h>

@interface MNWalkGuidanceManager : MNGuidanceManager
-(double)_adjustedDistanceToRoute:(id)arg1 ;
-(id)_combinedGuidanceForStep:(id)arg1 withType:(int)arg2 ;
-(void)_updatePrepareForNextStep;
-(BOOL)_updateConsiderExecuteAnnouncement:(id)arg1 location:(id)arg2 ;
-(double)_adjustedVehicleSpeed:(id)arg1 ;
-(int)transportType;
@end

