/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:00 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/MapPageRenderer.h>

@class SearchManager, NSMutableArray;

@interface SearchResultsPageRenderer : MapPageRenderer {

	SearchManager* _searchManager;
	NSMutableArray* _searchResultCells;
	SCD_Struct_Si13 topLeftCorner;
	SCD_Struct_Si13 mlMapPoint;
	SCD_Struct_Si13 mrMapPoint;

}

@property (nonatomic,retain) SearchManager * searchManager;              //@synthesize searchManager=_searchManager - In the implementation block
-(id)initWithSearchManager:(id)arg1 mapView:(id)arg2 ;
-(void)drawTopContentInRect:(CGRect)arg1 forPageAtIndex:(int)arg2 ;
-(CGRect)overviewRect;
-(void)_preparePageContent;
-(float)_zoomLevelForCoordinateRegion:(SCD_Struct_Se14)arg1 clampTo:(float)arg2 ;
-(int)searchResultsPerPage;
-(void)_drawPinsInRect:(CGRect)arg1 zoomLevel:(float)arg2 ;
-(int)numberOfPages;
-(void).cxx_destruct;
-(void)prepareForDrawingPages:(NSRange)arg1 ;
-(void)drawContentForPageAtIndex:(int)arg1 inRect:(CGRect)arg2 ;
-(id)searchManager;
-(void)setSearchManager:(id)arg1 ;
@end

