/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:58:59 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface StarkChromeState : NSObject {

	BOOL _topBarIsShowing;
	int _interactionModel;

}

@property (assign,nonatomic) BOOL topBarIsShowing;              //@synthesize topBarIsShowing=_topBarIsShowing - In the implementation block
@property (assign,nonatomic) int interactionModel;              //@synthesize interactionModel=_interactionModel - In the implementation block
-(BOOL)topBarIsShowing;
-(BOOL)shouldReloadInUnobscuredBoundsChangeForPreviousState:(id)arg1 ;
-(void)setTopBarIsShowing:(BOOL)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned)hash;
-(void)setInteractionModel:(int)arg1 ;
-(int)interactionModel;
@end

