/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:01 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIKeyboardImplGeometryDelegate
@property (assign,getter=isMinimized,nonatomic) BOOL minimized; 
@required
-(BOOL)isActive;
-(BOOL)shouldSaveMinimizationState;
-(BOOL)isMinimized;
-(void)prepareForImplBoundsHeightChange:(float)arg1 suppressNotification:(BOOL)arg2;
-(void)implBoundsHeightChangeDone:(float)arg1 suppressNotification:(BOOL)arg2;
-(void)setMinimized:(BOOL)arg1;
-(BOOL)canDismiss;
@end

