/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:06 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <QuartzCore/CALayer.h>

@interface AEHighlightLineLayer : CALayer {

	int _blendMode;

}

@property (assign,nonatomic) int blendMode;              //@synthesize blendMode=_blendMode - In the implementation block
+(id)layer;
-(int)blendMode;
-(void)setBlendMode:(int)arg1 ;
-(void)renderInContext:(CGContextRef)arg1 ;
@end

