/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:06 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Podcasts/Podcasts-Structs.h>
@class NSMutableDictionary, NSArray;

@interface AEMarginNotesController : NSObject {

	NSMutableDictionary* mMarginNoteLayers;
	CGRect mOwnerFrame;

}

@property (assign,setter=imaxSetAccessibilityDelegate:,nonatomic) id<AEMarginNotesControllerAccessibilityDelegate> imaxAccessibilityDelegate; 
@property (assign,nonatomic) CGSize ownerSize; 
@property (assign,nonatomic) CGRect ownerFrame; 
@property (nonatomic,readonly) NSArray * layers; 
@property (nonatomic,retain) NSMutableDictionary * marginNoteLayers; 
-(void)setMarginNoteLayers:(NSMutableDictionary *)arg1 ;
-(CGRect)ownerFrame;
-(void)setOwnerFrame:(CGRect)arg1 ;
-(NSMutableDictionary *)marginNoteLayers;
-(id)marginNoteAtPoint:(CGPoint)arg1 ;
-(id)p_imageForMarginNote:(id)arg1 ;
-(CGSize)ownerSize;
-(void)p_updateLayerLayout;
-(id)p_highlightedImageForMarginNote:(id)arg1 ;
-(void)setOwnerSize:(CGSize)arg1 ;
-(char)hasMarginNoteAtPoint:(CGPoint)arg1 ;
-(void)addMarginNote:(id)arg1 ;
-(void)removeMarginNote:(id)arg1 ;
-(void)highlightLayerOfNote:(id)arg1 ;
-(void)unhighlightLayerOfNote:(id)arg1 ;
-(id<AEMarginNotesControllerAccessibilityDelegate>)imaxAccessibilityDelegate;
-(void)imaxSetAccessibilityDelegate:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(NSArray *)layers;
@end

