/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:03 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/IMGridViewCell.h>
#import <UIKit/UIScrollViewDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol MTDownloadGridCellDelegate, MTDownloadGridCellGridViewDelegate;
@class UIScrollView, UIView, UITapGestureRecognizer, UIButton, UIImageView, UILabel, MTItemOfferButton, NSString;

@interface MTDownloadGridCell : IMGridViewCell <UIScrollViewDelegate, UIGestureRecognizerDelegate> {

	UIScrollView* _scrollView;
	UIView* _rightSeparator;
	UIView* _bottomSeparator;
	UIView* _deleteContainer;
	char _showsDeleteButton;
	char _ignoringScroll;
	char _animatingScroll;
	char _updatingAccessory;
	float _revealedWidth;
	UITapGestureRecognizer* _toggleTapGesture;
	UITapGestureRecognizer* _editingTapGesture;
	char _placeholder;
	char _pausable;
	char _otherCellSwiping;
	UIButton* _deleteButton;
	id<MTDownloadGridCellDelegate> _delegate;
	UIImageView* _podcastImageView;
	UILabel* _statusLabel;
	MTItemOfferButton* _downloadButton;
	UILabel* _podcastTitleLabel;
	id<MTDownloadGridCellGridViewDelegate> _gridViewDelegate;
	MTDownloadGridCell* _swipeToDeleteCell;

}

@property (nonatomic,retain) UIButton * deleteButton;                                                     //@synthesize deleteButton=_deleteButton - In the implementation block
@property (assign,nonatomic,__weak) id<MTDownloadGridCellDelegate> delegate;                              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UIImageView * podcastImageView;                                              //@synthesize podcastImageView=_podcastImageView - In the implementation block
@property (nonatomic,retain) UILabel * statusLabel;                                                       //@synthesize statusLabel=_statusLabel - In the implementation block
@property (nonatomic,retain) MTItemOfferButton * downloadButton;                                          //@synthesize downloadButton=_downloadButton - In the implementation block
@property (nonatomic,retain) UILabel * podcastTitleLabel;                                                 //@synthesize podcastTitleLabel=_podcastTitleLabel - In the implementation block
@property (assign,getter=isPlaceholder,nonatomic) char placeholder;                                       //@synthesize placeholder=_placeholder - In the implementation block
@property (assign,getter=isPausable,nonatomic) char pausable;                                             //@synthesize pausable=_pausable - In the implementation block
@property (assign,nonatomic,__weak) id<MTDownloadGridCellGridViewDelegate> gridViewDelegate;              //@synthesize gridViewDelegate=_gridViewDelegate - In the implementation block
@property (assign,nonatomic,__weak) MTDownloadGridCell * swipeToDeleteCell;                               //@synthesize swipeToDeleteCell=_swipeToDeleteCell - In the implementation block
@property (assign,nonatomic) char otherCellSwiping;                                                       //@synthesize otherCellSwiping=_otherCellSwiping - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)tapped:(id)arg1 ;
-(UIImageView *)podcastImageView;
-(void)setGridViewDelegate:(id<MTDownloadGridCellGridViewDelegate>)arg1 ;
-(void)setOtherCellSwiping:(char)arg1 ;
-(MTItemOfferButton *)downloadButton;
-(UILabel *)podcastTitleLabel;
-(void)updatePauseButton:(char)arg1 ;
-(void)togglePauseState:(id)arg1 ;
-(void)setOpen:(char)arg1 animated:(char)arg2 ;
-(void)updateAccessoryAnimated:(char)arg1 ;
-(void)updateButtonFrame;
-(void)enterEditing;
-(void)leaveEditing;
-(CGRect)buttonFrame;
-(void)endScroll:(id)arg1 ;
-(void)changeEditing:(char)arg1 ;
-(void)setPodcastImageView:(UIImageView *)arg1 ;
-(void)setDownloadButton:(MTItemOfferButton *)arg1 ;
-(void)setPodcastTitleLabel:(UILabel *)arg1 ;
-(id<MTDownloadGridCellGridViewDelegate>)gridViewDelegate;
-(char)otherCellSwiping;
-(void)setPausable:(char)arg1 ;
-(char)isPausable;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<MTDownloadGridCellDelegate>)arg1 ;
-(void)layoutSubviews;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(char)arg2 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(id<MTDownloadGridCellDelegate>)delegate;
-(char)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(void)setSwipeToDeleteCell:(MTDownloadGridCell *)arg1 ;
-(void)setEditing:(char)arg1 animated:(char)arg2 ;
-(MTDownloadGridCell *)swipeToDeleteCell;
-(void)prepareForReuse;
-(void)setPlaceholder:(char)arg1 ;
-(void)delete:(id)arg1 ;
-(UIButton *)deleteButton;
-(void)setDeleteButton:(UIButton *)arg1 ;
-(UILabel *)statusLabel;
-(void)setStatusLabel:(UILabel *)arg1 ;
-(char)isPlaceholder;
@end

