/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:03 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MTDownloadGridCellDelegate
@required
-(void)gridCell:(id)arg1 didChangeEditing:(char)arg2;
-(void)gridCellDidTogglePause:(id)arg1;
-(void)gridCellDidPressDelete:(id)arg1;

@end

