/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:03 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIButton.h>

@interface MTOTGPlaylistDetailListAddButton : UIButton {

	char _empty;
	char _trueEnabled;

}

@property (assign,nonatomic) char empty;                    //@synthesize empty=_empty - In the implementation block
@property (assign,nonatomic) char trueEnabled;              //@synthesize trueEnabled=_trueEnabled - In the implementation block
-(void)setTrueEnabled:(char)arg1 ;
-(char)trueEnabled;
-(void)setEmpty:(char)arg1 ;
-(void)setEnabled:(char)arg1 ;
-(char)empty;
@end

