/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:08 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UIColor.h>
#import <Podcasts/NSCopying.h>

@class UIColor;

@interface TKColor : UIColor <NSCopying> {

	float _red;
	float _blue;
	float _green;
	float _alpha;

}

@property (assign) float red;                             //@synthesize red=_red - In the implementation block
@property (assign) float blue;                            //@synthesize blue=_blue - In the implementation block
@property (assign) float green;                           //@synthesize green=_green - In the implementation block
@property (assign) float alpha;                           //@synthesize alpha=_alpha - In the implementation block
@property (retain,readonly) UIColor * color; 
-(void)setRed:(float)arg1 ;
-(void)setBlue:(float)arg1 ;
-(void)setGreen:(float)arg1 ;
-(float)alpha;
-(void)setAlpha:(float)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithRed:(float)arg1 green:(float)arg2 blue:(float)arg3 alpha:(float)arg4 ;
-(UIColor *)color;
-(float)red;
-(float)green;
-(float)blue;
-(id)hexValue;
@end

