/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:08 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/TKBaseComponent.h>

@class NSString;

@interface TKLoadingComponent : TKBaseComponent {

	char _accountForTopGuideline;
	char _accountForBottomGuideline;
	NSString* _text;

}

@property (retain) NSString * text;                             //@synthesize text=_text - In the implementation block
@property (assign) char accountForTopGuideline;                 //@synthesize accountForTopGuideline=_accountForTopGuideline - In the implementation block
@property (assign) char accountForBottomGuideline;              //@synthesize accountForBottomGuideline=_accountForBottomGuideline - In the implementation block
-(void)setAccountForBottomGuideline:(char)arg1 ;
-(void)setAccountForTopGuideline:(char)arg1 ;
-(char)accountForTopGuideline;
-(char)accountForBottomGuideline;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
@end

