/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:08 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Podcasts/TKBaseComponent.h>

@class NSString;

@interface TKMultilineLabelComponent : TKBaseComponent {

	float _leftMargin;
	float _rightMargin;
	int _numberOfLines;
	NSString* _text;

}

@property (assign) float leftMargin;               //@synthesize leftMargin=_leftMargin - In the implementation block
@property (assign) float rightMargin;              //@synthesize rightMargin=_rightMargin - In the implementation block
@property (assign) int numberOfLines;              //@synthesize numberOfLines=_numberOfLines - In the implementation block
@property (retain) NSString * text;                //@synthesize text=_text - In the implementation block
-(id)init;
-(void)setNumberOfLines:(int)arg1 ;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(void)setRightMargin:(float)arg1 ;
-(int)numberOfLines;
-(float)rightMargin;
-(float)leftMargin;
-(void)setLeftMargin:(float)arg1 ;
@end

