/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:28 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/iBooks-Structs.h>
#import <UIKit/UIControl.h>

@protocol AEImagePlayControlDelegate;
@class UIButton, UILabel, UIVisualEffectView, CAGradientLayer, UIImageView, UIView, NSTimer, UIImage, NSString, UIFont, UIColor;

@interface AEImagePlayControl : UIControl {

	UIButton* _skipBackwardButton;
	UIButton* _skipForwardButton;
	UILabel* _educationLabel;
	UIVisualEffectView* _educationEffectView;
	CAGradientLayer* _gradientLayer;
	char _didSwipeDuringCurrentTouch;
	id<AEImagePlayControlDelegate> _delegate;
	float _swipeLimit;
	UIImageView* _mainImageView;
	UIImageView* _temporaryImageView;
	UIImageView* _backgroundImageView;
	UIView* _educationView;
	UIView* _scrimView;
	id _overlayObject;
	id _vibrancyFilter;
	UIImageView* _overlayImageView;
	UILabel* _overlayLabel;
	float _swipeOffset;
	int _swipeDirection;
	NSTimer* _overlayDisappearTimer;
	NSTimer* _repeatResetTimer;
	CGPoint _touchStartPosition;

}

@property (assign,nonatomic,__weak) id<AEImagePlayControlDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) float swipeLimit;                                            //@synthesize swipeLimit=_swipeLimit - In the implementation block
@property (nonatomic,retain) UIImageView * mainImageView;                                 //@synthesize mainImageView=_mainImageView - In the implementation block
@property (nonatomic,retain) UIImageView * temporaryImageView;                            //@synthesize temporaryImageView=_temporaryImageView - In the implementation block
@property (nonatomic,retain) UIImageView * backgroundImageView;                           //@synthesize backgroundImageView=_backgroundImageView - In the implementation block
@property (nonatomic,retain) UIView * educationView;                                      //@synthesize educationView=_educationView - In the implementation block
@property (nonatomic,retain) UIImage * image; 
@property (nonatomic,retain) UIView * scrimView;                                          //@synthesize scrimView=_scrimView - In the implementation block
@property (nonatomic,copy) NSString * text; 
@property (nonatomic,retain) UIFont * font; 
@property (nonatomic,retain) UIColor * textColor; 
@property (nonatomic,retain) UIColor * shadowColor; 
@property (assign,nonatomic) CGSize shadowOffset; 
@property (nonatomic,retain) id overlayObject;                                            //@synthesize overlayObject=_overlayObject - In the implementation block
@property (nonatomic,retain) id vibrancyFilter;                                           //@synthesize vibrancyFilter=_vibrancyFilter - In the implementation block
@property (nonatomic,retain) UIImageView * overlayImageView;                              //@synthesize overlayImageView=_overlayImageView - In the implementation block
@property (nonatomic,retain) UILabel * overlayLabel;                                      //@synthesize overlayLabel=_overlayLabel - In the implementation block
@property (assign,nonatomic) float swipeOffset;                                           //@synthesize swipeOffset=_swipeOffset - In the implementation block
@property (assign,nonatomic) CGPoint touchStartPosition;                                  //@synthesize touchStartPosition=_touchStartPosition - In the implementation block
@property (assign,nonatomic) int swipeDirection;                                          //@synthesize swipeDirection=_swipeDirection - In the implementation block
@property (assign,nonatomic) char didSwipeDuringCurrentTouch;                             //@synthesize didSwipeDuringCurrentTouch=_didSwipeDuringCurrentTouch - In the implementation block
@property (nonatomic,retain) NSTimer * overlayDisappearTimer;                             //@synthesize overlayDisappearTimer=_overlayDisappearTimer - In the implementation block
@property (nonatomic,retain) NSTimer * repeatResetTimer;                                  //@synthesize repeatResetTimer=_repeatResetTimer - In the implementation block
-(UIView *)scrimView;
-(void)setScrimView:(UIView *)arg1 ;
-(void)showEducationView:(char)arg1 ;
-(void)setSkipButtonText:(id)arg1 ;
-(UIImageView *)mainImageView;
-(UIImageView *)temporaryImageView;
-(void)setOverlayObject:(id)arg1 ;
-(UILabel *)overlayLabel;
-(void)_showOverlay:(id)arg1 showScrim:(char)arg2 hideAutomatically:(char)arg3 ;
-(UIImageView *)overlayImageView;
-(id)overlayObject;
-(NSTimer *)overlayDisappearTimer;
-(void)_hideOverlay:(id)arg1 ;
-(void)setOverlayDisappearTimer:(NSTimer *)arg1 ;
-(float)swipeOffset;
-(void)pLayoutSubviewsWithOffset:(float)arg1 ;
-(UIView *)educationView;
-(void)setDidSwipeDuringCurrentTouch:(char)arg1 ;
-(void)setTouchStartPosition:(CGPoint)arg1 ;
-(void)_calculateSwipeOffsetForTouch:(id)arg1 ;
-(int)_swipeDirectionForSwipeOffset:(float)arg1 ;
-(unsigned)_updateSwipeDirection:(int)arg1 finished:(char)arg2 ;
-(void)_resetSwipeOffset;
-(void)pAnimateToSwipeOffsetWithDuration:(float)arg1 ;
-(void)_handleEventType:(unsigned)arg1 ;
-(void)setVibrancyFilter:(id)arg1 ;
-(id)vibrancyFilter;
-(void)onTapEducationView:(id)arg1 ;
-(float)swipeLimit;
-(CGPoint)touchStartPosition;
-(float)_swipeLimitInPoints;
-(void)setSwipeOffset:(float)arg1 ;
-(void)_overlayDidStopHiding:(id)arg1 finished:(id)arg2 context:(void*)arg3 ;
-(char)didSwipeDuringCurrentTouch;
-(void)flashOverlayText:(id)arg1 showScrim:(char)arg2 hideAutomatically:(char)arg3 ;
-(void)flashOverlayImage:(id)arg1 showScrim:(char)arg2 hideAutomatically:(char)arg3 ;
-(void)hideOverlayAfterDelay;
-(void)setSwipeLimit:(float)arg1 ;
-(void)setMainImageView:(UIImageView *)arg1 ;
-(void)setTemporaryImageView:(UIImageView *)arg1 ;
-(void)setEducationView:(UIView *)arg1 ;
-(void)setOverlayImageView:(UIImageView *)arg1 ;
-(void)setOverlayLabel:(UILabel *)arg1 ;
-(void)setSwipeDirection:(int)arg1 ;
-(NSTimer *)repeatResetTimer;
-(void)setRepeatResetTimer:(NSTimer *)arg1 ;
-(int)swipeDirection;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setImage:(UIImage *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setDelegate:(id<AEImagePlayControlDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<AEImagePlayControlDelegate>)delegate;
-(void)setContentMode:(int)arg1 ;
-(void)setTextColor:(UIColor *)arg1 ;
-(void)setFont:(UIFont *)arg1 ;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(UIImage *)image;
-(void)setShadowColor:(UIColor *)arg1 ;
-(void)setShadowOffset:(CGSize)arg1 ;
-(void)_commonInit;
-(int)contentMode;
-(CGSize)shadowOffset;
-(UIImageView *)backgroundImageView;
-(UIColor *)shadowColor;
-(UIFont *)font;
-(void)cancelTrackingWithEvent:(id)arg1 ;
-(char)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2 ;
-(char)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2 ;
-(void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2 ;
-(UIColor *)textColor;
-(void)setBackgroundImageView:(UIImageView *)arg1 ;
-(void)_hideOverlay;
@end

