/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:20 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/iBooks-Structs.h>
#import <UIKit/UIView.h>

@interface BKBookshelfCellShadow : UIView
+(id)shadowForSize:(CGSize)arg1 ;
+(void)drawShadowWithMaskForFrame:(CGRect)arg1 scale:(float)arg2 context:(CGContextRef)arg3 ;
+(void)initialize;
+(void)didReceiveMemoryWarning:(id)arg1 ;
@end

