/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:28 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSString, NSNumber;

@interface BKDocumentPageCount : NSManagedObject

@property (nonatomic,retain) NSString * href; 
@property (nonatomic,retain) NSNumber * pageCount; 
@property (nonatomic,retain) NSNumber * pageNumber; 
@property (nonatomic,retain) NSNumber * documentOrdinal; 
@property (nonatomic,retain) NSString * lookupKey; 
@property (nonatomic,retain) NSString * bookDatabaseKey; 
@property (nonatomic,retain) NSString * paginationRevision; 
+(id)newEmptyDocumentPageCount:(id)arg1 ;
@end

