/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:29 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/iBooks-Structs.h>
#import <UIKit/UIView.h>

@class UIView, UIColor, UIImage;

@interface BKLoupeView : UIView {

	UIView* _targetView;
	char _isVertical;
	UIColor* _pageColor;
	UIImage* _loupeMask;
	UIImage* _loupeSheen;

}

@property (nonatomic,readonly) UIView * targetView;               //@synthesize targetView=_targetView - In the implementation block
@property (assign,nonatomic) char isVertical;                     //@synthesize isVertical=_isVertical - In the implementation block
@property (nonatomic,retain) UIColor * pageColor;                 //@synthesize pageColor=_pageColor - In the implementation block
@property (nonatomic,readonly) UIImage * loupeMask;               //@synthesize loupeMask=_loupeMask - In the implementation block
@property (nonatomic,readonly) UIImage * loupeSheen;              //@synthesize loupeSheen=_loupeSheen - In the implementation block
@property (nonatomic,readonly) float loupeWidth; 
@property (nonatomic,readonly) float loupeHeight; 
-(UIColor *)pageColor;
-(void)setPageColor:(UIColor *)arg1 ;
-(void)setIsVertical:(char)arg1 ;
-(id)initWithTargetView:(id)arg1 ;
-(void)presentAtPoint:(CGPoint)arg1 animated:(char)arg2 ;
-(id)p_kitImageWithName:(id)arg1 ;
-(void)resetImages;
-(UIImage *)loupeMask;
-(float)loupeWidth;
-(float)loupeHeight;
-(UIImage *)loupeSheen;
-(CGPoint)loupePointForPoint:(CGPoint)arg1 ;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(void)moveToPoint:(CGPoint)arg1 ;
-(void)dismissAnimated:(char)arg1 ;
-(UIView *)targetView;
-(char)isVertical;
@end

