/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:29 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/iBooks-Structs.h>
#import <UIKit/UISnapshotView.h>

@class CAGradientLayer, CALayer, UIImage;

@interface BKPageBookCurlView : UISnapshotView {

	char _hasGradient;
	char _animate;
	CAGradientLayer* _largeGradientLayer;
	CAGradientLayer* _smallGradientLayer;
	char _left;
	double _duration;
	char _useNightColors;

}

@property (assign,nonatomic) char shouldHaveGradient;                   //@synthesize hasGradient=_hasGradient - In the implementation block
@property (assign,nonatomic) char shouldAnimate;                        //@synthesize animate=_animate - In the implementation block
@property (assign,getter=isLeft,nonatomic) char left;                   //@synthesize left=_left - In the implementation block
@property (nonatomic,retain) CALayer * smallGradientLayer;              //@synthesize smallGradientLayer=_smallGradientLayer - In the implementation block
@property (assign,nonatomic) double duration;                           //@synthesize duration=_duration - In the implementation block
@property (nonatomic,retain) UIImage * image; 
@property (assign,nonatomic) char useNightColors;                       //@synthesize useNightColors=_useNightColors - In the implementation block
-(char)useNightColors;
-(void)setShouldHaveGradient:(char)arg1 ;
-(void)updateCurlPercent:(float)arg1 ;
-(void)pageCurlWillCancel;
-(void)setUseNightColors:(char)arg1 ;
-(char)shouldHaveGradient;
-(id)initWithImage:(id)arg1 borderColor:(id)arg2 isLeft:(char)arg3 ;
-(id)initWithImage:(id)arg1 borderColor:(id)arg2 isLeft:(char)arg3 gutterImage:(id)arg4 ;
-(CALayer *)smallGradientLayer;
-(void)setSmallGradientLayer:(CALayer *)arg1 ;
-(void)setShouldAnimate:(char)arg1 ;
-(void)dealloc;
-(void)setImage:(UIImage *)arg1 ;
-(double)duration;
-(void)setDuration:(double)arg1 ;
-(UIImage *)image;
-(void)captureSnapshotRect:(CGRect)arg1 fromView:(id)arg2 withSnapshotType:(int)arg3 ;
-(char)shouldAnimate;
-(void)setLeft:(char)arg1 ;
-(char)isLeft;
@end

