/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:29 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/iBooks-Structs.h>
#import <iBooks/BKTOCTableViewCell.h>

@class UILabel;

@interface BKTOCAnnotationTableCell : BKTOCTableViewCell {

	UILabel* _dateLabel;
	UILabel* _noteLabel;

}

@property (nonatomic,retain,readonly) UILabel * dateLabel;              //@synthesize dateLabel=_dateLabel - In the implementation block
@property (nonatomic,retain,readonly) UILabel * noteLabel;              //@synthesize noteLabel=_noteLabel - In the implementation block
+(float)pageNumberFontSize;
+(float)dateFontSize;
+(CGRect)pageLabelFrameForString:(id)arg1 font:(id)arg2 bounds:(CGRect)arg3 writingDirection:(int)arg4 ;
+(CGRect)dateLabelFrameForString:(id)arg1 font:(id)arg2 bounds:(CGRect)arg3 minY:(float)arg4 writingDirection:(int)arg5 ;
+(float)titleFontSize;
-(UILabel *)noteLabel;
-(void)layoutSubviewsEditingWithBounds:(CGRect)arg1 ;
-(void)layoutSubviewsNotEditingWithBounds:(CGRect)arg1 ;
-(void)animatedTransitionToState:(unsigned)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(void)prepareForReuse;
-(void)willTransitionToState:(unsigned)arg1 ;
-(UILabel *)dateLabel;
-(void)setWritingDirection:(int)arg1 ;
-(void)setTheme:(id)arg1 ;
@end

