/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:24 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary, IMCloudSyncController, IMCloudSyncError;

@interface IMCloudSyncErrorHandle : NSObject {

	NSMutableDictionary* _userInfo;
	IMCloudSyncController* _controller;
	IMCloudSyncError* _error;
	/*^block*/id _completionBlock;

}

@property (nonatomic,retain) NSMutableDictionary * userInfo;                  //@synthesize userInfo=_userInfo - In the implementation block
@property (nonatomic,retain) IMCloudSyncController * controller;              //@synthesize controller=_controller - In the implementation block
@property (nonatomic,retain) IMCloudSyncError * error;                        //@synthesize error=_error - In the implementation block
@property (nonatomic,copy) id completionBlock;                                //@synthesize completionBlock=_completionBlock - In the implementation block
-(void)handleError:(id)arg1 withController:(id)arg2 ;
-(void)resolveError;
-(id)completionBlock;
-(void)setCompletionBlock:(id)arg1 ;
-(void)setUserInfo:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)userInfo;
-(IMCloudSyncController *)controller;
-(void)setController:(IMCloudSyncController *)arg1 ;
-(void)cleanup;
-(IMCloudSyncError *)error;
-(void)setError:(IMCloudSyncError *)arg1 ;
@end

