/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:24 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, CALayer, NSDictionary, NSMutableDictionary;

@interface IMMicaAnimator : NSObject {

	NSString* m_name;
	CALayer* m_rootLayer;
	NSDictionary* m_publishedObjects;
	NSMutableDictionary* m_preFetchedLayerImages;

}

@property (nonatomic,retain) NSString * name; 
@property (nonatomic,retain) CALayer * rootLayer; 
@property (nonatomic,retain) NSDictionary * publishedObjects; 
-(void)setPublishedObjects:(NSDictionary *)arg1 ;
-(id)_URLForDocumentName:(id)arg1 ;
-(id)_fileDataForURL:(id)arg1 ;
-(id)_fileDataForDocumentName:(id)arg1 ;
-(id)initWithName:(id)arg1 rootLayer:(id)arg2 publishedObjects:(id)arg3 ;
-(id)initWithFileName:(id)arg1 ;
-(void)addToLayer:(id)arg1 ;
-(id)publishedObjectWithKey:(id)arg1 required:(char)arg2 ;
-(void)fetchArtwork;
-(void)updateArtwork;
-(void)generateKeyPathPropertyAnimationKeys;
-(NSDictionary *)publishedObjects;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(void)removeFromSuperlayer;
-(void)setRootLayer:(CALayer *)arg1 ;
-(CALayer *)rootLayer;
@end

