/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:23 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/iBooks.app/iBooks
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBooks/iBooks-Structs.h>
#import <UIKit/UIViewController.h>
#import <iBooks/IMTransitionParent.h>

@class IMTheme, IMViewControllerTransition, NSMutableArray, NSString;

@interface IMViewController : UIViewController <IMTransitionParent> {

	char _visible;
	char _rotating;
	IMTheme* _theme;
	IMViewControllerTransition* _transitionItem;
	NSMutableArray* _pendingTransitions;
	IMViewControllerTransition* _currentTransition;

}

@property (assign,getter=isVisible,nonatomic) char visible;                               //@synthesize visible=_visible - In the implementation block
@property (getter=isRotating,nonatomic,readonly) char rotating;                           //@synthesize rotating=_rotating - In the implementation block
@property (nonatomic,retain) IMViewControllerTransition * transitionItem;                 //@synthesize transitionItem=_transitionItem - In the implementation block
@property (nonatomic,readonly) char definesTransitionContext; 
@property (nonatomic,retain) IMTheme * theme;                                             //@synthesize theme=_theme - In the implementation block
@property (nonatomic,retain) NSMutableArray * pendingTransitions;                         //@synthesize pendingTransitions=_pendingTransitions - In the implementation block
@property (nonatomic,retain) IMViewControllerTransition * currentTransition;              //@synthesize currentTransition=_currentTransition - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)_shouldForwardViewWillTransitionToSize;
-(void)releaseViews;
-(id)_transitionFromViewController:(id)arg1 toViewController:(id)arg2 transition:(id)arg3 reverse:(char)arg4 ;
-(id)transitionFromViewController:(id)arg1 toViewController:(id)arg2 transition:(id)arg3 reverse:(char)arg4 ;
-(void)fireTransition:(id)arg1 ;
-(void)childTransitionDidComplete:(id)arg1 finished:(char)arg2 ;
-(IMViewControllerTransition *)transitionItem;
-(NSMutableArray *)pendingTransitions;
-(void)processPendingTransitions;
-(void)setPendingTransitions:(NSMutableArray *)arg1 ;
-(char)shouldPerformChildTransition:(id)arg1 ;
-(void)childTransitionWillStart:(id)arg1 ;
-(void)childTransitionDidStart:(id)arg1 ;
-(char)definesTransitionContext;
-(void)setTransitionItem:(IMViewControllerTransition *)arg1 ;
-(void)addTransition:(id)arg1 ;
-(void)dealloc;
-(char)shouldAutorotate;
-(char)isRotating;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)setVisible:(char)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidUnload;
-(void)viewDidDisappear:(char)arg1 ;
-(char)isVisible;
-(void)initCommon;
-(void)setCurrentTransition:(IMViewControllerTransition *)arg1 ;
-(IMViewControllerTransition *)currentTransition;
-(IMTheme *)theme;
-(void)setTheme:(IMTheme *)arg1 ;
@end

