/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:34:50 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/sbin/BTLEServer
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class DataInputStream, CBATTRequest, NSInvocation;

@interface ANCRequest : NSObject {

	DataInputStream* _stream;
	CBATTRequest* _master;
	NSInvocation* _action;

}

@property (nonatomic,readonly) DataInputStream * stream;              //@synthesize stream=_stream - In the implementation block
@property (nonatomic,readonly) CBATTRequest * master;                 //@synthesize master=_master - In the implementation block
@property (nonatomic,retain) NSInvocation * action;                   //@synthesize action=_action - In the implementation block
-(id)initWithRequests:(id)arg1 ;
-(void)dealloc;
-(id)action;
-(void)setAction:(id)arg1 ;
-(id)master;
-(id)stream;
@end

