/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:15 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Setup/BuddyTableViewController.h>
#import <Setup/BuddyController.h>

@protocol BuddyControllerDelegate;
@class NSArray, NSMutableIndexSet;

@interface BuddyKeyboardPickerController : BuddyTableViewController <BuddyController> {

	<BuddyControllerDelegate>* _delegate;
	NSArray* _inputModes;
	NSMutableIndexSet* _selectedRowIndexes;
	NSArray* _previousSelectedInputModes;

}
+(BOOL)controllerNeedsToRun;
-(void)startOver;
-(void)controllerWasPopped;
-(void)_restoreSavedInputModes;
-(id)initWithLanguage:(id)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2 ;
-(void)done;
-(id)titleText;
@end

