/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:15 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/StoreKitUIService.app/StoreKitUIService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iTunesStoreUI/SUAccountViewController.h>

@class ServiceAccountPageViewController;

@interface ServiceSUAccountViewController : SUAccountViewController {

	ServiceAccountPageViewController* _hostedViewController;

}

@property (assign,nonatomic,__weak) ServiceAccountPageViewController * hostedViewController;              //@synthesize hostedViewController=_hostedViewController - In the implementation block
-(void)dismissViewControllerAnimated:(char)arg1 completion:(/*^block*/id)arg2 ;
-(void)dismissAnimated:(char)arg1 ;
-(ServiceAccountPageViewController *)hostedViewController;
-(void)setHostedViewController:(ServiceAccountPageViewController *)arg1 ;
@end

