/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:59 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Nike.app/Nike
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class STHistoryController, UIView, UILabel, STHistoryDistanceView, UITouch;

@interface STHistoryHeaderView : UIView {

	STHistoryController* _historyController;
	UIView* _leftView;
	UIView* _rightView;
	UILabel* _bestTimeLabel;
	UILabel* _bestTimeTitleLabel;
	STHistoryDistanceView* _totalDistanceLabel;
	UITouch* _trackingTouch;
	unsigned _touchInsideBestView : 1;
	unsigned _touchInsideTotalsView : 1;

}

@property (assign,nonatomic) STHistoryController * historyController;                   //@synthesize historyController=_historyController - In the implementation block
@property (nonatomic,readonly) UILabel * bestTimeLabel;                                 //@synthesize bestTimeLabel=_bestTimeLabel - In the implementation block
@property (nonatomic,readonly) STHistoryDistanceView * totalDistanceLabel;              //@synthesize totalDistanceLabel=_totalDistanceLabel - In the implementation block
-(void)setHistoryController:(STHistoryController *)arg1 ;
-(UILabel *)bestTimeLabel;
-(STHistoryDistanceView *)totalDistanceLabel;
-(STHistoryController *)historyController;
-(void)dealloc;
-(void)layoutSubviews;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
@end

