/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:32:47 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <gamed/GKInternalRepresentation.h>

@class NSString, NSArray, NSData, GKDispatchGroup, GKMatchRequestInternal, NSDictionary;

@interface GKMatchResponse : GKInternalRepresentation {

	NSString* _rid;
	NSArray* _matches;
	NSData* _sessionToken;
	NSArray* _relayPushes;
	NSData* _cdxTicket;
	GKDispatchGroup* _matchingGroup;
	GKMatchRequestInternal* _matchRequest;
	NSDictionary* _serverRequest;
	int _sequence;
	int _state;

}

@property (retain) NSString * rid;                                     //@synthesize rid=_rid - In the implementation block
@property (retain) NSArray * matches;                                  //@synthesize matches=_matches - In the implementation block
@property (retain) NSData * sessionToken;                              //@synthesize sessionToken=_sessionToken - In the implementation block
@property (retain) NSArray * relayPushes;                              //@synthesize relayPushes=_relayPushes - In the implementation block
@property (retain) NSData * cdxTicket;                                 //@synthesize cdxTicket=_cdxTicket - In the implementation block
@property (assign) GKDispatchGroup * matchingGroup;                    //@synthesize matchingGroup=_matchingGroup - In the implementation block
@property (retain) GKMatchRequestInternal * matchRequest;              //@synthesize matchRequest=_matchRequest - In the implementation block
@property (retain) NSDictionary * serverRequest;                       //@synthesize serverRequest=_serverRequest - In the implementation block
@property (readonly) int sequence;                                     //@synthesize sequence=_sequence - In the implementation block
@property (assign,nonatomic) int state;                                //@synthesize state=_state - In the implementation block
+(id)secureCodedPropertyKeys;
-(int)sequence;
-(id)sessionToken;
-(id)matches;
-(id)cdxTicket;
-(id)relayPushes;
-(int)_incrementSequence;
-(BOOL)transitionToState:(int)arg1 ;
-(void)setMatches:(id)arg1 ;
-(void)setSessionToken:(id)arg1 ;
-(void)setRelayPushes:(id)arg1 ;
-(void)setCdxTicket:(id)arg1 ;
-(id)matchingGroup;
-(void)setMatchingGroup:(id)arg1 ;
-(id)serverRequest;
-(void)setServerRequest:(id)arg1 ;
-(id)matchRequest;
-(void)setMatchRequest:(id)arg1 ;
-(id)rid;
-(void)setRid:(id)arg1 ;
-(void)dealloc;
-(int)state;
-(void)setState:(int)arg1 ;
-(BOOL)isCancelled;
-(BOOL)isFinished;
@end

