/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:32:47 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/libexec/gamed
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <gamed/GKListCacheObject.h>

@class NSDate, GKPlayerProfileCacheObject, NSString;

@interface GKRecentGameListCacheObject : GKListCacheObject

@property (nonatomic,@dynamic,retain) NSDate * sinceDate; 
@property (nonatomic,@dynamic,retain) GKPlayerProfileCacheObject * player; 
@property (nonatomic,@dynamic,retain) GKPlayerProfileCacheObject * otherPlayer; 
@property (nonatomic,@dynamic,retain) NSString * language; 
+(Class)entryClass;
+(id)entityName;
-(void)updateWithServerRepresentation:(id)arg1 expirationDate:(id)arg2 ;
-(id)internalRepresentationForLanguage:(id)arg1 ;
-(id)internalRepresentation;
@end

