/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:31 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Fitness.app/Fitness
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UILabel, UIView;

@interface _PairedLabels : UIView {

	UILabel* _keyLabel;
	UILabel* _valueLabel;
	UIView* _topDivider;

}

@property (nonatomic,readonly) UILabel * keyLabel;                //@synthesize keyLabel=_keyLabel - In the implementation block
@property (nonatomic,readonly) UILabel * valueLabel;              //@synthesize valueLabel=_valueLabel - In the implementation block
@property (nonatomic,readonly) UIView * topDivider;               //@synthesize topDivider=_topDivider - In the implementation block
-(UIView *)topDivider;
-(id)init;
-(void)layoutSubviews;
-(UILabel *)keyLabel;
-(UILabel *)valueLabel;
@end

