/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:31 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Fitness.app/Fitness
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Fitness/Fitness-Structs.h>
#import <UIKit/UIView.h>

@class SplashMessageView, UIActivityIndicatorView;

@interface LoadingView : UIView {

	SplashMessageView* _splashMessageView;
	UIActivityIndicatorView* _indicatorView;

}
-(void)showSplashMessageAnimated;
-(void)showLoadingIndicator;
-(id)initWithFrame:(CGRect)arg1 ;
@end

