/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:31 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Fitness.app/Fitness
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Fitness/Fitness-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UIScrollViewDelegate.h>
#import <Fitness/FitMonthWeekViewDelegate.h>

@protocol FitMonthWeekViewDatasource, MonthScrollViewDelegate;
@class FIUIRingsViewController, NSMutableArray, FIUIRingGroupController, UIScrollView, UIViewController, NSString;

@interface MonthScrollViewController : UIViewController <UIScrollViewDelegate, FitMonthWeekViewDelegate> {

	FIUIRingsViewController* _ringsVC;
	NSMutableArray* _groups;
	CGPoint _panAmount;
	float _incrementAmount;
	float _transitionPercent;
	FIUIRingGroupController* _pressedRingGroup;
	UIScrollView* _scrollView;
	id<FitMonthWeekViewDatasource> _monthWeekDatasource;
	UIViewController*<MonthScrollViewDelegate> _monthScrollDelegate;
	NSMutableArray* _weekViews;

}

@property (nonatomic,retain) UIScrollView * scrollView;                                                          //@synthesize scrollView=_scrollView - In the implementation block
@property (assign,nonatomic,__weak) id<FitMonthWeekViewDatasource> monthWeekDatasource;                          //@synthesize monthWeekDatasource=_monthWeekDatasource - In the implementation block
@property (assign,nonatomic,__weak) UIViewController*<MonthScrollViewDelegate> monthScrollDelegate;              //@synthesize monthScrollDelegate=_monthScrollDelegate - In the implementation block
@property (nonatomic,retain) NSMutableArray * weekViews;                                                         //@synthesize weekViews=_weekViews - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)week:(id)arg1 pressedOnDay:(int)arg2 down:(char)arg3 ;
-(void)week:(id)arg1 cellSelected:(id)arg2 ;
-(void)refreshData;
-(id)earliestDateToTileForMonth:(id)arg1 ;
-(UIViewController*<MonthScrollViewDelegate>)monthScrollDelegate;
-(void)transitionPercent:(float)arg1 final:(char)arg2 ;
-(void)scrollToDate:(id)arg1 windowHeight:(float)arg2 ;
-(void)setMonthScrollDelegate:(UIViewController*<MonthScrollViewDelegate>)arg1 ;
-(void)_activityCacheUpdated:(id)arg1 ;
-(void)_createRingVC;
-(void)updateDataForWeek:(id)arg1 adjacentWeek:(id)arg2 ascending:(char)arg3 ;
-(void)_relayoutRingGroups;
-(id)weekWithStartDate:(id)arg1 ;
-(float)heightOffsetForWeekRow:(int)arg1 ;
-(void)addAndRearrangeWeekviewsAndGroups;
-(void)resetDataToEmptyState:(id)arg1 ;
-(void)animateGroupToStart:(id)arg1 index:(int)arg2 ;
-(void)setUpdatedProperties:(id)arg1 index:(int)arg2 ;
-(float)centerXForRingAt:(int)arg1 percent:(float)arg2 ;
-(void)_animateRingOnTouch:(char)arg1 completion:(/*^block*/id)arg2 ;
-(id<FitMonthWeekViewDatasource>)monthWeekDatasource;
-(void)setMonthWeekDatasource:(id<FitMonthWeekViewDatasource>)arg1 ;
-(void)setWeekViews:(NSMutableArray *)arg1 ;
-(NSMutableArray *)weekViews;
-(void)dealloc;
-(id)init;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)setScrollView:(UIScrollView *)arg1 ;
-(void)viewDidLoad;
-(UIScrollView *)scrollView;
@end

