/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:31 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Fitness.app/Fitness
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Fitness/Fitness-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UIScrollViewDelegate.h>

@protocol PaletteScrollViewDelegate;
@class NSMutableArray, UIScrollView, FIUIRingsViewController, NSDate, NSString;

@interface PaletteScrollViewController : UIViewController <UIScrollViewDelegate> {

	CGPoint _panAmount;
	NSMutableArray* _groups;
	UIScrollView* _scrollView;
	FIUIRingsViewController* _ringsVC;
	char _wasTouched;
	NSMutableArray* _weekStartingDates;
	NSDate* _dateTouched;
	id<PaletteScrollViewDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<PaletteScrollViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)refreshData;
-(void)_activityCacheUpdated:(id)arg1 ;
-(void)_createRingVC;
-(void)_fillRingsInWeek:(id)arg1 startingDate:(id)arg2 ;
-(CGPoint)_centerForRingAtIndex:(unsigned)arg1 withRingDiameter:(float)arg2 ;
-(int)findStartingIndexOfGroupForDate:(id)arg1 ;
-(void)_prepareForScrollAnimationStart;
-(void)_readjustOffsetIfNecessary;
-(void)_scrollAnimationFinished;
-(char)representsOffscreenPage:(float)arg1 ;
-(id)startOfFitnessWeekBeforeWeekStarting:(id)arg1 ;
-(id)startOfFitnessWeekAfterWeekStarting:(id)arg1 ;
-(id)_getDayWithTouches:(id)arg1 ;
-(void)scrollWeekViewToTarget:(CGPoint)arg1 animated:(char)arg2 ;
-(void)reloadViewDataAtDate:(id)arg1 ;
-(id)weekStartingDates;
-(void)dealloc;
-(void)setDelegate:(id<PaletteScrollViewDelegate>)arg1 ;
-(id)init;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewWillBeginDecelerating:(id)arg1 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(void)scrollViewDidEndScrollingAnimation:(id)arg1 ;
-(id<PaletteScrollViewDelegate>)delegate;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(void)add:(char)arg1 ;
@end

