/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:27 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Diagnostics.app/Diagnostics
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Diagnostics/Diagnostics-Structs.h>
#import <Diagnostics/DABasePresenceCheck.h>

@protocol OS_dispatch_queue;
@class NSObject, NSMutableArray;

@interface DABluetoothPresenceCheck : DABasePresenceCheck {

	NSObject*<OS_dispatch_queue> _queue;
	BTSessionImplRef _session;
	BTLocalDeviceImplRef _localDevice;
	BTDiscoveryAgentImplRef _discoveryAgent;
	SCD_Struct_DA23* _attachDetachCallback;
	SCD_Struct_DA24* _discoveryCallbacks;
	SCD_Struct_DA25* _localDeviceCallbacks;
	BOOL _scanStarted;
	BOOL _scanStopped;
	NSMutableArray* _foundDevices;

}

@property (assign,nonatomic) BOOL scanStarted;                           //@synthesize scanStarted=_scanStarted - In the implementation block
@property (assign,nonatomic) BOOL scanStopped;                           //@synthesize scanStopped=_scanStopped - In the implementation block
@property (nonatomic,retain) NSMutableArray * foundDevices;              //@synthesize foundDevices=_foundDevices - In the implementation block
-(id)checkPresence:(id)arg1 ;
-(int)bluetoothPower:(BTLocalDeviceImplRef)arg1 isEnabled:(BOOL*)arg2 ;
-(void)setScanStarted:(BOOL)arg1 ;
-(void)setScanStopped:(BOOL)arg1 ;
-(id)setupBluetoothSessionAndDevice;
-(BOOL)setBluetoothPower:(BTLocalDeviceImplRef)arg1 enabled:(BOOL)arg2 timeout:(double)arg3 ;
-(BOOL)scanStarted;
-(BOOL)scanStopped;
-(void)teardownBluetoothSessionAndDevice;
-(id)performBluetoothScanWithTimeout:(double)arg1 foundDevices:(id)arg2 isPresenceCheck:(char)arg3 ;
-(NSMutableArray *)foundDevices;
-(void)setFoundDevices:(NSMutableArray *)arg1 ;
@end

