/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:26 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Diagnostics.app/Diagnostics
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Diagnostics/DATestOperation.h>

@class DACameraPresenceCheck, DAAccelerometerPresenceCheck, DAGyroPresenceCheck, DACompassPresenceCheck, DAPhosphorousPresenceCheck, DAAmbientLightPresenceCheck, DABluetoothPresenceCheck, DAMultitouchPresenceCheck, DAVibratorPresenceCheck, DADisplayPresenceCheck, DAAudioPresenceCheck, DABasebandPresenceCheck, DAOscarSpuPresenceCheck, DAWiFiPresenceCheck, DAStockholmPresenceCheck, DATouchIDPresenceCheck, DABatteryPresenceCheck;

@interface DAComponentPresenceTest : DATestOperation {

	DACameraPresenceCheck* _camera;
	DAAccelerometerPresenceCheck* _accelerometer;
	DAGyroPresenceCheck* _gyro;
	DACompassPresenceCheck* _compass;
	DAPhosphorousPresenceCheck* _barometer;
	DAAmbientLightPresenceCheck* _als;
	DABluetoothPresenceCheck* _bluetooth;
	DAMultitouchPresenceCheck* _multitouch;
	DAVibratorPresenceCheck* _vibrator;
	DADisplayPresenceCheck* _display;
	DAAudioPresenceCheck* _audio;
	DABasebandPresenceCheck* _baseband;
	DAOscarSpuPresenceCheck* _spu;
	DAWiFiPresenceCheck* _wifi;
	DAStockholmPresenceCheck* _stockholm;
	DATouchIDPresenceCheck* _touchID;
	DABatteryPresenceCheck* _battery;

}

@property (nonatomic,retain) DACameraPresenceCheck * camera;                            //@synthesize camera=_camera - In the implementation block
@property (nonatomic,retain) DAAccelerometerPresenceCheck * accelerometer;              //@synthesize accelerometer=_accelerometer - In the implementation block
@property (nonatomic,retain) DAGyroPresenceCheck * gyro;                                //@synthesize gyro=_gyro - In the implementation block
@property (nonatomic,retain) DACompassPresenceCheck * compass;                          //@synthesize compass=_compass - In the implementation block
@property (nonatomic,retain) DAPhosphorousPresenceCheck * barometer;                    //@synthesize barometer=_barometer - In the implementation block
@property (nonatomic,retain) DAAmbientLightPresenceCheck * als;                         //@synthesize als=_als - In the implementation block
@property (nonatomic,retain) DABluetoothPresenceCheck * bluetooth;                      //@synthesize bluetooth=_bluetooth - In the implementation block
@property (nonatomic,retain) DAMultitouchPresenceCheck * multitouch;                    //@synthesize multitouch=_multitouch - In the implementation block
@property (nonatomic,retain) DAVibratorPresenceCheck * vibrator;                        //@synthesize vibrator=_vibrator - In the implementation block
@property (nonatomic,retain) DADisplayPresenceCheck * display;                          //@synthesize display=_display - In the implementation block
@property (nonatomic,retain) DAAudioPresenceCheck * audio;                              //@synthesize audio=_audio - In the implementation block
@property (nonatomic,retain) DABasebandPresenceCheck * baseband;                        //@synthesize baseband=_baseband - In the implementation block
@property (nonatomic,retain) DAOscarSpuPresenceCheck * spu;                             //@synthesize spu=_spu - In the implementation block
@property (nonatomic,retain) DAWiFiPresenceCheck * wifi;                                //@synthesize wifi=_wifi - In the implementation block
@property (nonatomic,retain) DAStockholmPresenceCheck * stockholm;                      //@synthesize stockholm=_stockholm - In the implementation block
@property (nonatomic,retain) DATouchIDPresenceCheck * touchID;                          //@synthesize touchID=_touchID - In the implementation block
@property (nonatomic,retain) DABatteryPresenceCheck * battery;                          //@synthesize battery=_battery - In the implementation block
-(DABatteryPresenceCheck *)battery;
-(DATouchIDPresenceCheck *)touchID;
-(DAStockholmPresenceCheck *)stockholm;
-(DAAmbientLightPresenceCheck *)als;
-(DAGyroPresenceCheck *)gyro;
-(DACompassPresenceCheck *)compass;
-(DAPhosphorousPresenceCheck *)barometer;
-(DAAccelerometerPresenceCheck *)accelerometer;
-(DABluetoothPresenceCheck *)bluetooth;
-(DAVibratorPresenceCheck *)vibrator;
-(DAMultitouchPresenceCheck *)multitouch;
-(DAOscarSpuPresenceCheck *)spu;
-(id)mapToPresenceFunction;
-(id)pullSerialNumbers;
-(id)localTest;
-(void)setAccelerometer:(DAAccelerometerPresenceCheck *)arg1 ;
-(void)setGyro:(DAGyroPresenceCheck *)arg1 ;
-(void)setCompass:(DACompassPresenceCheck *)arg1 ;
-(void)setBarometer:(DAPhosphorousPresenceCheck *)arg1 ;
-(void)setAls:(DAAmbientLightPresenceCheck *)arg1 ;
-(void)setBluetooth:(DABluetoothPresenceCheck *)arg1 ;
-(void)setMultitouch:(DAMultitouchPresenceCheck *)arg1 ;
-(void)setVibrator:(DAVibratorPresenceCheck *)arg1 ;
-(void)setBaseband:(DABasebandPresenceCheck *)arg1 ;
-(void)setSpu:(DAOscarSpuPresenceCheck *)arg1 ;
-(void)setStockholm:(DAStockholmPresenceCheck *)arg1 ;
-(void)setTouchID:(DATouchIDPresenceCheck *)arg1 ;
-(void)setBattery:(DABatteryPresenceCheck *)arg1 ;
-(DADisplayPresenceCheck *)display;
-(void)main;
-(DAAudioPresenceCheck *)audio;
-(void)setAudio:(DAAudioPresenceCheck *)arg1 ;
-(DABasebandPresenceCheck *)baseband;
-(void)setDisplay:(DADisplayPresenceCheck *)arg1 ;
-(DACameraPresenceCheck *)camera;
-(void)setCamera:(DACameraPresenceCheck *)arg1 ;
-(void)setWifi:(DAWiFiPresenceCheck *)arg1 ;
-(DAWiFiPresenceCheck *)wifi;
@end

