/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:27 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Diagnostics.app/Diagnostics
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol DAMainViewControllerDelegate <NSObject>
@required
-(char)hasMultipleDevices;
-(void)didAgreeToTermsAndConditionsWithMultipleDevices:(char)arg1;
-(void)didPressCloseButton;

@end

