/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:27 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Diagnostics.app/Diagnostics
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface DASignalData : NSObject {

	unsigned _minimumDelay;
	unsigned _maximumDelay;
	float _fileTimeInFrames;
	float* _sourceSignal;
	float* _receivedSignal;
	unsigned _outputID;
	unsigned _inputID;
	NSString* _fileName;

}

@property (assign) unsigned minimumDelay;               //@synthesize minimumDelay=_minimumDelay - In the implementation block
@property (assign) unsigned maximumDelay;               //@synthesize maximumDelay=_maximumDelay - In the implementation block
@property (assign) float fileTimeInFrames;              //@synthesize fileTimeInFrames=_fileTimeInFrames - In the implementation block
@property (assign) float* sourceSignal;                 //@synthesize sourceSignal=_sourceSignal - In the implementation block
@property (assign) float* receivedSignal;               //@synthesize receivedSignal=_receivedSignal - In the implementation block
@property (assign) unsigned outputID;                   //@synthesize outputID=_outputID - In the implementation block
@property (assign) unsigned inputID;                    //@synthesize inputID=_inputID - In the implementation block
@property (retain) NSString * fileName;                 //@synthesize fileName=_fileName - In the implementation block
-(void)setInputID:(unsigned)arg1 ;
-(void)setOutputID:(unsigned)arg1 ;
-(unsigned)outputID;
-(unsigned)inputID;
-(float)fileTimeInFrames;
-(id)initWithSourceSignal:(float*)arg1 receivedSignal:(float*)arg2 minimumDelay:(unsigned)arg3 maximumDelay:(unsigned)arg4 fileTimeInFrames:(float)arg5 outputID:(unsigned)arg6 inputID:(unsigned)arg7 fileName:(id)arg8 ;
-(void)setFileTimeInFrames:(float)arg1 ;
-(float*)sourceSignal;
-(void)setMaximumDelay:(unsigned)arg1 ;
-(void)setSourceSignal:(float*)arg1 ;
-(void)setReceivedSignal:(float*)arg1 ;
-(float*)receivedSignal;
-(void)freeSourceData;
-(void)freeReceivedData;
-(unsigned)maximumDelay;
-(NSString *)fileName;
-(void)setMinimumDelay:(unsigned)arg1 ;
-(unsigned)minimumDelay;
-(void)setFileName:(NSString *)arg1 ;
@end

