/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:09 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UILabel.h>

@class NSArray, NSTimer;

@interface PHTextCycleLabel : UILabel {

	NSArray* _cycleStrings;
	NSTimer* _cycleTimer;
	int _currentCycleStringIndex;

}

@property (retain) NSArray * cycleStrings;                   //@synthesize cycleStrings=_cycleStrings - In the implementation block
@property (retain) NSTimer * cycleTimer;                     //@synthesize cycleTimer=_cycleTimer - In the implementation block
@property (assign) int currentCycleStringIndex;              //@synthesize currentCycleStringIndex=_currentCycleStringIndex - In the implementation block
-(void)startCyclingStrings;
-(void)setCycleStrings:(id)arg1 ;
-(id)cycleStrings;
-(void)setCurrentCycleStringIndex:(int)arg1 ;
-(int)currentCycleStringIndex;
-(id)cycleTimer;
-(void)setCycleTimer:(id)arg1 ;
-(void)cycleToNextString;
-(void)dealloc;
-(void)setText:(id)arg1 ;
@end

