/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:21 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/AccountAuthenticationDialog.app/AccountAuthenticationDialog
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OOPAWebViewControllerDelegate <NSObject>
@required
-(void)webViewController:(id)arg1 didFinishWithSuccess:(char)arg2 response:(id)arg3;

@end

