/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:32:27 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/libexec/BackupAgent2
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <BackupAgent2/MBPlugin.h>

@interface MBDataMigratorPlugin : NSObject <MBPlugin>
-(id)preparingBackupWithEngine:(id)arg1 ;
-(id)endingRestoreWithEngine:(id)arg1 ;
-(id)_setDMContextWithEngine:(id)arg1 ;
-(id)_updateMobileBackupPreferencesWithEngine:(id)arg1 ;
-(id)_restoreDefaultsWithEngine:(id)arg1 ;
@end

