/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:07 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>

@protocol MessageFoldViewDelegate;
@class NSArray, UIView;

@interface MessageFoldView : UIView {

	<MessageFoldViewDelegate>* _delegate;
	NSArray* _foldViews;
	NSArray* _foldShadowViews;
	NSArray* _foldLineViews;
	UIView* _coveredView;
	CGRect _coveredRect;
	float _minHeight;
	unsigned _foldCount;
	int _foldContentsVisibility;
	BOOL _validCoveredSnapshots;

}

@property (assign,nonatomic) <MessageFoldViewDelegate> * delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)initWithFrame:(CGRect)arg1 foldCount:(unsigned)arg2 minHeight:(float)arg3 ;
-(void)setMessageFoldContentsVisibility:(int)arg1 ;
-(void)invalidateFoldSnapshots;
-(void)updateFoldSnapshotsIfNecessary;
-(void)setCoveredRect:(CGRect)arg1 inView:(id)arg2 ;
-(void)setLastQuoteLevel:(unsigned)arg1 ;
-(BOOL)isUnfolded;
-(BOOL)isUnfolding;
-(void)_updateCoveredSnapshots;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(void)layoutSubviews;
-(id)delegate;
@end

