/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:07 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>

@protocol MFArrowControlsViewDelegate;
@class UIButton;

@interface MFArrowControlsView : UIView {

	UIButton* _upButton;
	UIButton* _downButton;
	<MFArrowControlsViewDelegate>* _delegate;
	int _interfaceOrientation;

}

@property (assign,nonatomic) <MFArrowControlsViewDelegate> * delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) UIButton * downButton;                               //@synthesize downButton=_downButton - In the implementation block
@property (nonatomic,readonly) UIButton * upButton;                                 //@synthesize upButton=_upButton - In the implementation block
@property (assign,nonatomic) int interfaceOrientation;                              //@synthesize interfaceOrientation=_interfaceOrientation - In the implementation block
+(float)defaultWidthForOrientation:(int)arg1 ;
+(float)defaultHeightForOrientation:(int)arg1 ;
-(id)upButton;
-(void)_arrowButtonWasTapped:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(id)delegate;
-(int)interfaceOrientation;
-(void)setInterfaceOrientation:(int)arg1 ;
-(id)downButton;
@end

