/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:58:56 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/AppStore.app/AppStore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <StoreKitUI/SKUIViewController.h>

@class SKUIStorePageViewController;

@interface ASExternalURLStorePageViewController : SKUIViewController {

	SKUIStorePageViewController* _storePageViewController;

}
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)loadView;
-(void).cxx_destruct;
-(void)loadURLRequest:(id)arg1 withCompletionBlock:(/*^block*/ id)arg2 ;
-(id)_storePageViewController;
@end

