/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:32:29 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/libexec/backboardd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol BKApplicationDataStoreRepository <NSObject>
@property (assign,nonatomic) <BKApplicationDataStoreRepositoryDelegate> * delegate; 
@required
-(void)objectForKeys:(id)arg1 forAllApplicationsWithResult:(/*^block*/ id)arg2;
-(void)flushSynchronously;
-(id)applicationIdentifiersWithState;
-(void)setObject:(id)arg1 forKey:(id)arg2 forApplication:(id)arg3;
-(void)removeObjectForKey:(id)arg1 forApplication:(id)arg2;
-(void)removeAllObjectsForApplication:(id)arg1;
-(void)beginBatchedUpdate;
-(void)removeObjectsForKeys:(id)arg1 forApplication:(id)arg2;
-(void)endBatchedUpdate;
-(id)objectForKey:(id)arg1 forApplication:(id)arg2;
-(id)keysForApplication:(id)arg1;
-(BOOL)containsKey:(id)arg1 forApplication:(id)arg2;
-(void)setDelegate:(id)arg1;
-(id)delegate;
-(void)objectForKey:(id)arg1 forApplication:(id)arg2 withResult:(/*^block*/ id)arg3;
@end

