/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:32:29 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/libexec/backboardd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface BKHIDServiceMatchingAction : NSObject {

	/*^block*/ id _removalAction;
	/*^block*/ id _additionAction;

}

@property (readonly) id removalAction;               //@synthesize removalAction=_removalAction - In the implementation block
@property (readonly) id additionAction;              //@synthesize additionAction=_additionAction - In the implementation block
-(id)initWithAdditionAction:(/*^block*/ id)arg1 removalAction:(/*^block*/ id)arg2 ;
-(/*^block*/ id)removalAction;
-(/*^block*/ id)additionAction;
-(void)dealloc;
@end

