/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:35 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/InCallService.app/InCallService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <InCallService/PHAudioCallControlsViewDelegate.h>

@protocol PHAudioCallControlsViewControllerDelegate;
@class PHAudioCallControlsView, PHAudioCallControlArrangement, NSString;

@interface PHAudioCallControlsViewController : UIViewController <PHAudioCallControlsViewDelegate> {

	char _enabled;
	id<PHAudioCallControlsViewControllerDelegate> _delegate;
	PHAudioCallControlsView* _controlsView;
	PHAudioCallControlArrangement* _controlArrangement;

}

@property (__weak) id<PHAudioCallControlsViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) char enabled;                                              //@synthesize enabled=_enabled - In the implementation block
@property (retain) PHAudioCallControlsView * controlsView;                              //@synthesize controlsView=_controlsView - In the implementation block
@property (retain) PHAudioCallControlArrangement * controlArrangement;                  //@synthesize controlArrangement=_controlArrangement - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(unsigned)controlTypeAtRow:(unsigned)arg1 column:(unsigned)arg2 ;
-(unsigned)numberOfRowsInControlsView:(id)arg1 ;
-(unsigned)numberOfColumnsInControlsView:(id)arg1 ;
-(char)controlTypeIsEnabled:(unsigned)arg1 ;
-(char)controlTypeIsSelected:(unsigned)arg1 ;
-(id)imageNameForControlType:(unsigned)arg1 ;
-(id)titleForControlType:(unsigned)arg1 ;
-(void)controlTypeTapped:(unsigned)arg1 ;
-(void)controlTypeShortPressed:(unsigned)arg1 ;
-(void)controlTypeLongPressed:(unsigned)arg1 ;
-(void)callStatusChangedNotification:(id)arg1 ;
-(void)faceTimeIDStatusChangedNotification:(id)arg1 ;
-(void)audioRoutesChangedNotification:(id)arg1 ;
-(void)uplinkStateChangedNotification:(id)arg1 ;
-(PHAudioCallControlsView *)controlsView;
-(id)currentArrangement;
-(void)setControlsView:(PHAudioCallControlsView *)arg1 ;
-(PHAudioCallControlArrangement *)controlArrangement;
-(void)setControlArrangement:(PHAudioCallControlArrangement *)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id<PHAudioCallControlsViewControllerDelegate>)arg1 ;
-(id)init;
-(id<PHAudioCallControlsViewControllerDelegate>)delegate;
-(void)setEnabled:(char)arg1 ;
-(char)isEnabled;
-(void)loadView;
-(char)enabled;
-(void)modelStateChangedNotification:(id)arg1 ;
@end

