/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:35 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/InCallService.app/InCallService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSArray;

@interface PHAudioCallControlArrangement : NSObject {

	NSArray* _controlTypes;

}

@property (nonatomic,readonly) unsigned rows; 
@property (nonatomic,readonly) unsigned columns; 
@property (retain) NSArray * controlTypes;                    //@synthesize controlTypes=_controlTypes - In the implementation block
+(id)defaultControlTypes;
+(id)defaultMultipleCallControlTypes;
-(NSArray *)controlTypes;
-(id)_replaceControlsOfType:(unsigned)arg1 withControlOfType:(unsigned)arg2 ;
-(void)setControlTypes:(NSArray *)arg1 ;
-(id)initWithControlTypes:(id)arg1 ;
-(unsigned)controlTypeAtRow:(unsigned)arg1 column:(unsigned)arg2 ;
-(void)replaceControlsOfType:(unsigned)arg1 withControlOfType:(unsigned)arg2 ;
-(unsigned)rows;
-(unsigned)columns;
@end

