/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:23 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Calculator.app/Calculator
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface CalculateUtilities : NSObject
+(id)stringForButton:(unsigned)arg1 ;
+(id)errorStringForResult:(id)arg1 ;
+(id)stringMathResultWithExpression:(id)arg1 ;
+(id)stringMathResultWithOperator:(unsigned)arg1 ;
+(unsigned)shiftedButtonForButton:(unsigned)arg1 ;
+(id)attributedStringForButton:(unsigned)arg1 font:(id)arg2 smallTextFont:(id)arg3 ;
+(unsigned)alternateButtonForButton:(unsigned)arg1 ;
+(id)_displayStringForButton:(unsigned)arg1 ;
+(id)_invertButtonImageForFont:(id)arg1 ;
+(id)_reciprocalImageForFont:(id)arg1 ;
+(id)_imageForRoot:(unsigned)arg1 font:(id)arg2 radixFont:(id)arg3 ;
+(id)stringRoundedToPrecision:(unsigned)arg1 withString:(id)arg2 roundingMode:(unsigned)arg3 ;
@end

