/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:05 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <UIKit/UIView.h>

@class _UINavigationControllerPalette, WeekDayInitialsHeaderView, DayNavigationViewController;

@interface PaletteView : UIView {

	_UINavigationControllerPalette* _containingPalette;
	WeekDayInitialsHeaderView* _dayInitialsHeaderView;
	BOOL _freezeSize;
	BOOL _weekdayHeaderVisible;
	DayNavigationViewController* _dayScrubberController;

}

@property (nonatomic,readonly) BOOL hasContent; 
@property (assign,nonatomic) BOOL freezeSize;                                                  //@synthesize freezeSize=_freezeSize - In the implementation block
@property (assign,nonatomic) BOOL weekdayHeaderVisible;                                        //@synthesize weekdayHeaderVisible=_weekdayHeaderVisible - In the implementation block
@property (nonatomic,retain) DayNavigationViewController * dayScrubberController;              //@synthesize dayScrubberController=_dayScrubberController - In the implementation block
-(void)layoutWithoutResizingPalette;
-(void)setDayHeaderFrames:(id)arg1 ;
-(void)setWeekdayHeaderVisible:(BOOL)arg1 ;
-(void)setDayScrubberController:(id)arg1 ;
-(void)setFreezeSize:(BOOL)arg1 ;
-(id)dayScrubberController;
-(id)initWithNavigationPalette:(id)arg1 ;
-(void)removeAllContent;
-(BOOL)weekdayHeaderVisible;
-(BOOL)freezeSize;
-(id)_generateWeekDayInitialsHeaderView;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(BOOL)hasContent;
-(void).cxx_destruct;
-(void)_localeChanged:(id)arg1 ;
@end

