/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:05 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileCal/RootViewController.h>
#import <MobileCal/WeekViewControllerDelegate.h>
#import <MobileCal/EKEventEditViewDelegate.h>

@class PhoneRootNavigationController, PhoneWeekViewController;

@interface PhoneRootViewController : RootViewController <WeekViewControllerDelegate, EKEventEditViewDelegate> {

	PhoneRootNavigationController* _rootNavigationController;
	int _interfaceOrientationStartingModalEditingSession;
	PhoneWeekViewController* _weekViewController;

}

@property (nonatomic,readonly) PhoneWeekViewController * weekViewController;              //@synthesize weekViewController=_weekViewController - In the implementation block
-(void)landscapeController:(id)arg1 didSelectEvent:(id)arg2 ;
-(void)landscapeController:(id)arg1 didEditEvent:(id)arg2 ;
-(id)weekViewController;
-(id)_weekViewController;
-(void)eventEditViewController:(id)arg1 didCompleteWithAction:(int)arg2 ;
-(unsigned)supportedInterfaceOrientations;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2 ;
-(void).cxx_destruct;
-(id)rootNavigationController;
@end

