/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 8:59:05 PM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileCal/ApplicationTest.h>

@class InboxViewController;

@interface ShowInboxRepliedSectionTest : ApplicationTest {

	InboxViewController* _inboxViewController;

}
-(void)runTest;
-(void)_inboxDidAppear:(id)arg1 ;
-(void).cxx_destruct;
@end

