/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:19 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/WebSheet.app/WebSheet
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <WebSheet/WebSheet-Structs.h>
#import <UIKit/UIApplication.h>
#import <UIKit/UIApplicationDelegate.h>

@class UIWindow, WebSheetViewController, NSString;

@interface WebSheetAppDelegate : UIApplication <UIApplicationDelegate> {

	ShowWebSheetContext _showWebSheetContext;
	char _openWiFiPreferencesOnExit;
	WebSheetViewController* _webSheetCont;

}

@property (nonatomic,retain) WebSheetViewController * webSheetCont;              //@synthesize webSheetCont=_webSheetCont - In the implementation block
@property (assign,nonatomic) char openWiFiPreferencesOnExit;                     //@synthesize openWiFiPreferencesOnExit=_openWiFiPreferencesOnExit - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) UIWindow * window; 
-(void)remoteSheetDidEnd;
-(char)shouldIsolateCookies;
-(WebSheetViewController *)webSheetCont;
-(void)setWebSheetCont:(WebSheetViewController *)arg1 ;
-(char)openWiFiPreferencesOnExit;
-(void)setOpenWiFiPreferencesOnExit:(char)arg1 ;
-(void)dealloc;
-(void)applicationWillTerminate:(id)arg1 ;
-(void)applicationDidFinishLaunching:(id)arg1 ;
-(char)canShowAlerts;
@end

