/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:10 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Reminders.app/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Reminders/Reminders-Structs.h>
#import <UIKit/UIView.h>

@class UIImage;

@interface RemindersScrollingBackgroundView : UIView {

	UIImage* _textureImage;

}

@property (retain) UIImage * textureImage;              //@synthesize textureImage=_textureImage - In the implementation block
+(id)kitPaperTextureImage;
-(void)setTextureImage:(UIImage *)arg1 ;
-(UIImage *)textureImage;
-(void)resizeForRect:(CGRect)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)setContentOffset:(CGPoint)arg1 ;
@end

