/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:10 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Reminders.app/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@interface RemindersListCell : UITableViewCell {

	char _drawsSeparator;

}

@property (assign,nonatomic) char drawsSeparator;              //@synthesize drawsSeparator=_drawsSeparator - In the implementation block
-(void)setDrawsSeparator:(char)arg1 ;
-(float)titleHeight;
-(char)drawsSeparator;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
@end

