/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:10 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Reminders.app/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Reminders/Reminders-Structs.h>
#import <UIKit/UIView.h>

@protocol RemindersCheckboxViewDelegate;
@class UIImageView, UIColor;

@interface RemindersCheckboxView : UIView {

	UIImageView* _buttonImageView;
	char _checked;
	char _overdue;
	char _enabled;
	char _useDarkBGAppearance;
	id<RemindersCheckboxViewDelegate> _delegate;
	UIColor* _buttonColor;

}

@property (assign,nonatomic,__weak) id<RemindersCheckboxViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UIColor * buttonColor;                                          //@synthesize buttonColor=_buttonColor - In the implementation block
@property (assign,getter=isChecked,nonatomic) char checked;                                  //@synthesize checked=_checked - In the implementation block
@property (assign,getter=isOverdue,nonatomic) char overdue;                                  //@synthesize overdue=_overdue - In the implementation block
@property (assign,getter=isEnabled,nonatomic) char enabled;                                  //@synthesize enabled=_enabled - In the implementation block
@property (assign,nonatomic) char useDarkBGAppearance;                                       //@synthesize useDarkBGAppearance=_useDarkBGAppearance - In the implementation block
-(void)setOverdue:(char)arg1 ;
-(void)setUseDarkBGAppearance:(char)arg1 ;
-(char)useDarkBGAppearance;
-(id)flatCompletedImage;
-(id)flatUncompletedImageForColor:(id)arg1 ;
-(void)buttonDown;
-(void)buttonCancelled;
-(char)isOverdue;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<RemindersCheckboxViewDelegate>)arg1 ;
-(void)setChecked:(char)arg1 ;
-(id<RemindersCheckboxViewDelegate>)delegate;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)setEnabled:(char)arg1 ;
-(char)isEnabled;
-(char)isChecked;
-(void)buttonPressed;
-(void)_updateImage;
-(UIColor *)buttonColor;
-(void)setButtonColor:(UIColor *)arg1 ;
@end

