/*
* This header is generated by classdump-dyld 0.2
* on Saturday, June 28, 2014 at 7:34:50 AM Japan Standard Time
* Operating System: Version 7.1.1 (Build 11D201)
* Image Source: /usr/sbin/wirelessproxd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <BTLEServer/CBCentralManagerDelegate.h>
#import <locationd/CBPeripheralManagerDelegate.h>

@class CBCentralManager, CBCentral, CBPeripheralManager, CBMutableService, CBMutableCharacteristic, NSCountedSet;

@interface DaemonBluetooth : NSObject <CBCentralManagerDelegate, CBPeripheralManagerDelegate> {

	BOOL _serviceActive;
	BOOL _transferActive;
	BOOL _currentlyAdvertising;
	BOOL _transferSuccess;
	int _centralState;
	int _peripheralState;
	CBCentralManager* _centralManager;
	CBCentral* _currentlySubscribedCentral;
	CBPeripheralManager* _peripheralManager;
	CBMutableService* _transferService;
	CBMutableCharacteristic* _transferCharacteristic;
	NSCountedSet* _scanningSet;

}

@property (assign) int centralState;                                              //@synthesize centralState=_centralState - In the implementation block
@property (assign) int peripheralState;                                           //@synthesize peripheralState=_peripheralState - In the implementation block
@property (retain) CBCentralManager * centralManager;                             //@synthesize centralManager=_centralManager - In the implementation block
@property (retain) CBCentral * currentlySubscribedCentral;                        //@synthesize currentlySubscribedCentral=_currentlySubscribedCentral - In the implementation block
@property (retain) CBPeripheralManager * peripheralManager;                       //@synthesize peripheralManager=_peripheralManager - In the implementation block
@property (retain) CBMutableService * transferService;                            //@synthesize transferService=_transferService - In the implementation block
@property (retain) CBMutableCharacteristic * transferCharacteristic;              //@synthesize transferCharacteristic=_transferCharacteristic - In the implementation block
@property (retain) NSCountedSet * scanningSet;                                    //@synthesize scanningSet=_scanningSet - In the implementation block
@property (assign) BOOL serviceActive;                                            //@synthesize serviceActive=_serviceActive - In the implementation block
@property (assign) BOOL transferActive;                                           //@synthesize transferActive=_transferActive - In the implementation block
@property (assign) BOOL currentlyAdvertising;                                     //@synthesize currentlyAdvertising=_currentlyAdvertising - In the implementation block
@property (assign) BOOL transferSuccess;                                          //@synthesize transferSuccess=_transferSuccess - In the implementation block
+(id)shared;
-(BOOL)connectPeripheral:(id)arg1 ;
-(int)centralState;
-(id)peripheralManager;
-(BOOL)startDeviceScan:(int)arg1 ;
-(void)stopDeviceScan:(int)arg1 ;
-(void)setPeripheralManager:(id)arg1 ;
-(void)updateScanner;
-(BOOL)startDeviceScan:(int)arg1 rssiCutoff:(id)arg2 ;
-(id)deviceTypeAsString:(int)arg1 ;
-(id)scanningSet;
-(void)updateScannerScreenOff;
-(void)logScanningSet;
-(void)setCentralState:(int)arg1 ;
-(void)setPeripheralState:(int)arg1 ;
-(void)setCurrentlyAdvertising:(BOOL)arg1 ;
-(void)advertiseData:(id)arg1 ;
-(id)transferService;
-(void)setTransferService:(id)arg1 ;
-(void)setTransferCharacteristic:(id)arg1 ;
-(id)transferCharacteristic;
-(BOOL)serviceActive;
-(void)advertiseType:(int)arg1 advertisingInterval:(int)arg2 ;
-(id)currentlySubscribedCentral;
-(void)setCurrentlySubscribedCentral:(id)arg1 ;
-(BOOL)currentlyAdvertising;
-(BOOL)transferSuccess;
-(void)setTransferSuccess:(BOOL)arg1 ;
-(void)disconnectPeripheral:(id)arg1 ;
-(BOOL)startTransferAdvertising;
-(void)stopTransferAdvertising;
-(BOOL)updateValueForCharacteristic:(id)arg1 ;
-(void)cancelConnectionFromPeripheral;
-(void)transferCompletedSuccessfully;
-(int)peripheralState;
-(void)setScanningSet:(id)arg1 ;
-(BOOL)transferActive;
-(void)setTransferActive:(BOOL)arg1 ;
-(void)peripheralManagerDidUpdateState:(id)arg1 ;
-(void)peripheralManager:(id)arg1 didAddService:(id)arg2 error:(id)arg3 ;
-(void)peripheralManager:(id)arg1 didReceiveWriteRequests:(id)arg2 ;
-(void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3 ;
-(void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3 ;
-(void)peripheralManagerDidStartAdvertising:(id)arg1 error:(id)arg2 ;
-(void)peripheralManagerIsReadyToUpdateSubscribers:(id)arg1 ;
-(id)centralManager;
-(void)setCentralManager:(id)arg1 ;
-(void)setServiceActive:(BOOL)arg1 ;
-(void)dealloc;
-(id)init;
-(void).cxx_destruct;
-(void)centralManagerDidUpdateState:(id)arg1 ;
-(void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4 ;
-(void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2 ;
-(void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3 ;
-(void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3 ;
@end

