/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:56 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIActivity.h>
#import <MobileSafari/SingleBookmarkNavigationControllerDelegate.h>

@class SingleBookmarkNavigationController;

@interface AddBookmarkUIActivity : UIActivity <SingleBookmarkNavigationControllerDelegate> {

	SingleBookmarkNavigationController* _bookmarkNavController;

}
-(void)addBookmarkNavController:(id)arg1 didFinishWithResult:(char)arg2 ;
-(id)parentBookmark;
-(id)aggregateDKey;
-(id)activityType;
-(id)activityTitle;
-(void)activityDidFinish:(char)arg1 ;
-(char)canPerformWithActivityItems:(id)arg1 ;
-(id)activityImage;
-(id)activityViewController;
-(void)prepareWithActivityItems:(id)arg1 ;
-(id)_beforeActivity;
-(id)_embeddedActivityViewController;
@end

