/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:57 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileSafari.app/webbookmarksd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <WebUI/WBSCloudHistoryConfiguration.h>

@class NSArray, NSDictionary;

@interface CloudHistoryConfiguration : WBSCloudHistoryConfiguration {

	NSArray* _assetsSortedByVersionNumber;
	NSDictionary* _remoteConfigurationDictionary;
	char _fetchedAssetData;

}
+(id)sharedConfiguration;
-(void)_reloadConfigurationDataIfNecessary;
-(id)_cloudConfigurationAssetsSortedByVersionNumber;
-(id)init;
-(id)remoteConfiguration;
-(id)platformBuiltInConfiguration;
@end

