/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:55 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CloudTabTableDelegate <NSObject>
@required
-(void)cloudTabTable:(id)arg1 didSelectCloudTab:(id)arg2;
-(void)cloudTabTable:(id)arg1 didStartEditingTabItemView:(id)arg2;
-(void)cloudTabTable:(id)arg1 didFinishEditingTabItemView:(id)arg2;
-(void)cloudTabTable:(id)arg1 closeCloudTab:(id)arg2 onDevice:(id)arg3;

@end

