/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:54 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIView.h>
#import <MobileSafari/WBSFluidProgressControllerDelegate.h>

@protocol FluidProgressViewDelegate;
@class UIImageView, UIView, UIColor;

@interface FluidProgressView : UIView <WBSFluidProgressControllerDelegate> {

	UIImageView* _progressBar;
	UIView* _clippingView;
	char _progressAnimationSuppressed;
	float _progress;
	id<FluidProgressViewDelegate> _delegate;
	UIColor* _progressBarFillColor;
	float _cornerRadius;

}

@property (assign,nonatomic) char progressAnimationSuppressed;                             //@synthesize progressAnimationSuppressed=_progressAnimationSuppressed - In the implementation block
@property (assign,nonatomic) float progress;                                               //@synthesize progress=_progress - In the implementation block
@property (assign,nonatomic,__weak) id<FluidProgressViewDelegate> delegate;                //@synthesize delegate=_delegate - In the implementation block
@property (getter=isShowingProgress,nonatomic,readonly) char showingProgress; 
@property (nonatomic,retain) UIColor * progressBarFillColor;                               //@synthesize progressBarFillColor=_progressBarFillColor - In the implementation block
@property (assign,nonatomic) float cornerRadius;                                           //@synthesize cornerRadius=_cornerRadius - In the implementation block
+(float)defaultHeight;
-(void)_updateProgressBarImage;
-(CGRect)_progressBarBoundsForValue:(double)arg1 ;
-(void)_finishProgressBarWithDuration:(double)arg1 ;
-(void)_animateUsingDefaultTiming:(char)arg1 stepAnimationTime:(float)arg2 options:(unsigned)arg3 animations:(/*^block*/id)arg4 completion:(/*^block*/id)arg5 ;
-(void)setProgressBarFillColor:(UIColor *)arg1 ;
-(void)setProgressAnimationSuppressed:(char)arg1 duringFluidProgressState:(id)arg2 ;
-(char)isShowingProgress;
-(char)progressAnimationSuppressed;
-(void)setProgressAnimationSuppressed:(char)arg1 ;
-(UIColor *)progressBarFillColor;
-(void)setDelegate:(id<FluidProgressViewDelegate>)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(id<FluidProgressViewDelegate>)delegate;
-(float)cornerRadius;
-(void)setCornerRadius:(float)arg1 ;
-(void)setProgress:(float)arg1 ;
-(float)progress;
-(void)fluidProgressController:(id)arg1 startFluidProgressBar:(id)arg2 animateFillFade:(char)arg3 ;
-(void)fluidProgressControllerFinishProgressBar:(id)arg1 animateFillFade:(char)arg2 ;
-(void)fluidProgressController:(id)arg1 setProgressToCurrentPosition:(id)arg2 ;
-(void)fluidProgressController:(id)arg1 updateFluidProgressBar:(id)arg2 ;
@end

