/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:54 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIView, UILabel;

@interface TabExplanationView : UIView {

	UIView* _labelsContainer;
	UILabel* _title;
	UILabel* _message;

}
-(id)_basicLabel;
-(void)updateConstraints;
-(id)initWithTitle:(id)arg1 message:(id)arg2 ;
@end

