/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:53 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <MobileSafari/MobileSafari-Structs.h>
@interface TabOverviewInterpolatedLocation : NSObject {

	SCD_Struct_Ta1 _instantaneousTargetLocation;
	CGPoint _interactionFixedPoint;
	char _interactionIncludesScale;
	double _interactionLogScaleVelocity;
	CGPoint _interactionVelocity;
	double _lastInteractionTimestamp;
	double _decelerationFactor;
	SCD_Struct_Ta1 _location;
	SCD_Struct_Ta1 _targetLocation;

}

@property (nonatomic,readonly) SCD_Struct_Ta2 location;                  //@synthesize location=_location - In the implementation block
@property (assign,nonatomic) SCD_Struct_Ta2 targetLocation;              //@synthesize targetLocation=_targetLocation - In the implementation block
@property (assign,nonatomic) double decelerationFactor;                  //@synthesize decelerationFactor=_decelerationFactor - In the implementation block
-(void)_moveBy:(CGPoint)arg1 ;
-(void)moveBy:(CGPoint)arg1 atTime:(double)arg2 ;
-(id)initWithLocation:(SCD_Struct_Ta2)arg1 decelerationFactor:(double)arg2 ;
-(void)resetToLocation:(SCD_Struct_Ta2)arg1 ;
-(void)shiftTargetLocation:(SCD_Struct_Ta2)arg1 ;
-(void)setDecelerationFactor:(double)arg1 ;
-(double)decelerationFactorForTargetLocation:(SCD_Struct_Ta2)arg1 ;
-(char)isInSteadyStateWithConstraints:(/*^block*/id)arg1 ;
-(void)interpolateByTimeInterval:(double)arg1 roundingAtSize:(CGSize)arg2 zScaleFactor:(float)arg3 withHorizontalBounceFactor:(double)arg4 verticalBounceFactor:(double)arg5 constraints:(/*^block*/id)arg6 ;
-(void)beginInteractionAtTime:(double)arg1 ;
-(void)endInteraction;
-(void)moveLogScaleBy:(double)arg1 centeringOffset:(CGPoint)arg2 withLastCenteringOffset:(CGPoint)arg3 atTime:(double)arg4 ;
-(double)decelerationFactor;
-(SCD_Struct_Ta2)location;
-(SCD_Struct_Ta2)targetLocation;
-(void)setTargetLocation:(SCD_Struct_Ta2)arg1 ;
@end

