/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:54 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class NSString;


@protocol WBSURLCompletionMatchData <NSObject>
@property (nonatomic,readonly) NSString * originalURLString; 
@property (nonatomic,readonly) char containsBookmark; 
@property (nonatomic,readonly) double lastVisitedTimeInterval; 
@property (nonatomic,readonly) char lastVisitWasFailure; 
@required
-(char)lastVisitWasFailure;
-(id)pageTitleAtIndex:(unsigned)arg1;
-(id)pageTitleForUserVisibleURLStringAtIndex:(unsigned)arg1;
-(NSString *)originalURLString;
-(char)containsBookmark;
-(id)userVisibleURLStringForPageTitleAtIndex:(unsigned)arg1;
-(id)userVisibleURLStringAtIndex:(unsigned)arg1;
-(double)lastVisitedTimeInterval;
-(void)enumeratePageTitlesUsingBlock:(/*^block*/id)arg1;
-(void)enumerateUserVisibleURLsUsingBlock:(/*^block*/id)arg1;
-(float)topSitesScoreForPageTitleAtIndex:(unsigned)arg1 atTime:(double)arg2;
-(float)topSitesScoreForURLStringAtIndex:(unsigned)arg1 atTime:(double)arg2;
-(id)matchDataByMergingWithMatchData:(id)arg1;
-(char)matchesAutocompleteTrigger:(id)arg1;

@end

