/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:24 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Bridge/Bridge-Structs.h>
#import <Preferences/PSListController.h>
#import <UIKit/UITextFieldDelegate.h>
#import <UIKit/UIAlertViewDelegate.h>
#import <Bridge/RemoteUIControllerDelegate.h>
#import <Bridge/COSAppleIDLinkerDelegate.h>

@protocol NSObject;
@class NSSManager, ACAccountStore, ACAccount, AASetupAssistantService, COSAppleIDLinker, UITextField, RemoteUIController, UINavigationController, NSString;

@interface COSAppleIDController : PSListController <UITextFieldDelegate, UIAlertViewDelegate, RemoteUIControllerDelegate, COSAppleIDLinkerDelegate> {

	char _hasFetchedGizmoiCloudInfo;
	char _errorHasOccuredFetchingGizmoiCloudInfo;
	char _gizmoIsLoggedIn;
	NSSManager* _nssManager;
	ACAccountStore* _accountStore;
	ACAccount* _existingAccount;
	AASetupAssistantService* _aaService;
	COSAppleIDLinker* _appleIDLinker;
	OpaqueCFHTTPCookieStorageRef _cookieStorage;
	UITextField* _passwordTextField;
	id<NSObject> _textFieldTextDidChangeObserver;
	RemoteUIController* _iForgotRemoteController;
	UINavigationController* _iForgotController;

}

@property (nonatomic,retain) NSSManager * nssManager;                                   //@synthesize nssManager=_nssManager - In the implementation block
@property (nonatomic,retain) ACAccountStore * accountStore;                             //@synthesize accountStore=_accountStore - In the implementation block
@property (nonatomic,retain) ACAccount * existingAccount;                               //@synthesize existingAccount=_existingAccount - In the implementation block
@property (nonatomic,retain) AASetupAssistantService * aaService;                       //@synthesize aaService=_aaService - In the implementation block
@property (nonatomic,retain) COSAppleIDLinker * appleIDLinker;                          //@synthesize appleIDLinker=_appleIDLinker - In the implementation block
@property (assign,nonatomic) OpaqueCFHTTPCookieStorageRef cookieStorage;                //@synthesize cookieStorage=_cookieStorage - In the implementation block
@property (nonatomic,retain) UITextField * passwordTextField;                           //@synthesize passwordTextField=_passwordTextField - In the implementation block
@property (nonatomic,retain) id<NSObject> textFieldTextDidChangeObserver;               //@synthesize textFieldTextDidChangeObserver=_textFieldTextDidChangeObserver - In the implementation block
@property (assign,nonatomic) char hasFetchedGizmoiCloudInfo;                            //@synthesize hasFetchedGizmoiCloudInfo=_hasFetchedGizmoiCloudInfo - In the implementation block
@property (assign,nonatomic) char errorHasOccuredFetchingGizmoiCloudInfo;               //@synthesize errorHasOccuredFetchingGizmoiCloudInfo=_errorHasOccuredFetchingGizmoiCloudInfo - In the implementation block
@property (assign,nonatomic) char gizmoIsLoggedIn;                                      //@synthesize gizmoIsLoggedIn=_gizmoIsLoggedIn - In the implementation block
@property (nonatomic,retain) RemoteUIController * iForgotRemoteController;              //@synthesize iForgotRemoteController=_iForgotRemoteController - In the implementation block
@property (nonatomic,retain) UINavigationController * iForgotController;                //@synthesize iForgotController=_iForgotController - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_loadiForgot;
-(void)loggedInSuccessfully;
-(void)stopNetworkRequest;
-(void)startNetworkRequest;
-(void)_presentRemoteiForgotWithURL:(id)arg1 ;
-(void)setIForgotController:(UINavigationController *)arg1 ;
-(void)_dismissiForgot;
-(void)setAppleIDLinker:(COSAppleIDLinker *)arg1 ;
-(COSAppleIDLinker *)appleIDLinker;
-(void)appleIDLinker:(id)arg1 didFinishWithSuccess:(char)arg2 error:(id)arg3 ;
-(id)viewControllerToPresentSecondFactorUIForAppleIDLinker:(id)arg1 ;
-(void)setPasswordTextField:(UITextField *)arg1 ;
-(AASetupAssistantService *)aaService;
-(void)setAaService:(AASetupAssistantService *)arg1 ;
-(RemoteUIController *)iForgotRemoteController;
-(void)setIForgotRemoteController:(RemoteUIController *)arg1 ;
-(UINavigationController *)iForgotController;
-(OpaqueCFHTTPCookieStorageRef)cookieStorage;
-(void)tappedSignIn;
-(void)setHasFetchedGizmoiCloudInfo:(char)arg1 ;
-(void)setErrorHasOccuredFetchingGizmoiCloudInfo:(char)arg1 ;
-(void)enableSignInButton:(char)arg1 ;
-(void)queryGizmoForiCloudInfo;
-(void)tappedForgotButton;
-(id<NSObject>)textFieldTextDidChangeObserver;
-(void)setTextFieldTextDidChangeObserver:(id<NSObject>)arg1 ;
-(char)hasFetchedGizmoiCloudInfo;
-(char)errorHasOccuredFetchingGizmoiCloudInfo;
-(char)gizmoIsLoggedIn;
-(void)setGizmoIsLoggedIn:(char)arg1 ;
-(void)dealloc;
-(id)init;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(UITextField *)passwordTextField;
-(char)textFieldShouldReturn:(id)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewWillDisappear:(char)arg1 ;
-(ACAccount *)existingAccount;
-(void)setExistingAccount:(ACAccount *)arg1 ;
-(NSSManager *)nssManager;
-(void)setNssManager:(NSSManager *)arg1 ;
-(void)remoteUIController:(id)arg1 willLoadRequest:(id)arg2 ;
-(void)remoteUIController:(id)arg1 willPresentObjectModel:(id)arg2 modally:(char)arg3 ;
-(void)remoteUIControllerDidDismiss:(id)arg1 ;
-(id)_usernameForSpecifier:(id)arg1 ;
-(void)_setPassword:(id)arg1 withSpecifier:(id)arg2 ;
-(void)_textFieldValueDidChange:(id)arg1 ;
-(void)setCookieStorage:(OpaqueCFHTTPCookieStorageRef)arg1 ;
-(ACAccountStore *)accountStore;
-(void)setAccountStore:(ACAccountStore *)arg1 ;
-(id)specifiers;
-(void)openSettingsApp;
@end

