/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:25 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Bridge/Bridge-Structs.h>
#import <UIKit/UIView.h>

@protocol COSGetStartedDelegate;
@class NSTimer, UILabel, UIButton, NSMutableArray, UIImageView;

@interface COSGetStartedView : UIView {

	char _pairingInfrastructureIsBusy;
	char _animating;
	char _isFadeAnimationInFlight;
	id<COSGetStartedDelegate> _delegate;
	unsigned _mode;
	unsigned _timeOfDay;
	NSTimer* _welcomeTextUpdater;
	UILabel* _welcomeLabel;
	UILabel* _titleLabel;
	UIButton* _acceptButton;
	UIButton* _automationButton;
	UIButton* _learnMoreButton;
	unsigned _radioState;
	NSMutableArray* _animationImageQueue;
	UIImageView* _animationImageView;

}

@property (assign,nonatomic,__weak) id<COSGetStartedDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) char pairingInfrastructureIsBusy;                       //@synthesize pairingInfrastructureIsBusy=_pairingInfrastructureIsBusy - In the implementation block
@property (assign,nonatomic) unsigned mode;                                          //@synthesize mode=_mode - In the implementation block
@property (assign,nonatomic) unsigned timeOfDay;                                     //@synthesize timeOfDay=_timeOfDay - In the implementation block
@property (nonatomic,retain) NSTimer * welcomeTextUpdater;                           //@synthesize welcomeTextUpdater=_welcomeTextUpdater - In the implementation block
@property (nonatomic,retain) UILabel * welcomeLabel;                                 //@synthesize welcomeLabel=_welcomeLabel - In the implementation block
@property (nonatomic,retain) UILabel * titleLabel;                                   //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) UIButton * acceptButton;                                //@synthesize acceptButton=_acceptButton - In the implementation block
@property (nonatomic,retain) UIButton * automationButton;                            //@synthesize automationButton=_automationButton - In the implementation block
@property (nonatomic,retain) UIButton * learnMoreButton;                             //@synthesize learnMoreButton=_learnMoreButton - In the implementation block
@property (assign,nonatomic) unsigned radioState;                                    //@synthesize radioState=_radioState - In the implementation block
@property (nonatomic,retain) NSMutableArray * animationImageQueue;                   //@synthesize animationImageQueue=_animationImageQueue - In the implementation block
@property (nonatomic,retain) UIImageView * animationImageView;                       //@synthesize animationImageView=_animationImageView - In the implementation block
@property (assign,nonatomic) char animating;                                         //@synthesize animating=_animating - In the implementation block
@property (assign,nonatomic) char isFadeAnimationInFlight;                           //@synthesize isFadeAnimationInFlight=_isFadeAnimationInFlight - In the implementation block
-(void)stopUpdatingWelcomeText;
-(void)updateWelcomeText;
-(void)setPairingInfrastructureIsBusy:(char)arg1 ;
-(void)learnMoreTapped:(id)arg1 ;
-(void)setLearnMoreButton:(UIButton *)arg1 ;
-(void)updateContinueState;
-(void)tappedStart:(id)arg1 ;
-(void)_tappedInternalManualMode:(id)arg1 ;
-(void)updateRadioStateForNotification:(id)arg1 ;
-(void)startUpdatingWelcomeText;
-(void)updateProblemState;
-(void)_startNextAnimation;
-(UIImageView *)animationImageView;
-(void)_logConnectionDescription;
-(float)detailTextSidePadding;
-(void)_prepareForSetupAndDismiss;
-(char)pairingInfrastructureIsBusy;
-(unsigned)timeOfDay;
-(void)setTimeOfDay:(unsigned)arg1 ;
-(NSTimer *)welcomeTextUpdater;
-(void)setWelcomeTextUpdater:(NSTimer *)arg1 ;
-(UILabel *)welcomeLabel;
-(void)setWelcomeLabel:(UILabel *)arg1 ;
-(UIButton *)automationButton;
-(void)setAutomationButton:(UIButton *)arg1 ;
-(unsigned)radioState;
-(void)setRadioState:(unsigned)arg1 ;
-(NSMutableArray *)animationImageQueue;
-(void)setAnimationImageQueue:(NSMutableArray *)arg1 ;
-(void)setAnimationImageView:(UIImageView *)arg1 ;
-(char)isFadeAnimationInFlight;
-(void)setIsFadeAnimationInFlight:(char)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id<COSGetStartedDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<COSGetStartedDelegate>)delegate;
-(UILabel *)titleLabel;
-(void)stopAnimating;
-(void)startAnimating;
-(void)setAnimating:(char)arg1 ;
-(void)setMode:(unsigned)arg1 ;
-(unsigned)mode;
-(char)animating;
-(void)setTitleLabel:(UILabel *)arg1 ;
-(void)_dismiss;
-(UIButton *)learnMoreButton;
-(UIButton *)acceptButton;
-(void)setAcceptButton:(UIButton *)arg1 ;
@end

