/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:25 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SUBManagerDelegate <NSObject>
@optional
-(void)manager:(id)arg1 scanRequestDidLocateUpdate:(id)arg2 error:(id)arg3;
-(void)manager:(id)arg1 didFailDownload:(id)arg2 withError:(id)arg3;
-(void)manager:(id)arg1 didFinishDownload:(id)arg2 willProceedWithInstallation:(char)arg3 waitingForAdmissionControl:(char)arg4 denialReasons:(id)arg5;
-(void)manager:(id)arg1 didFinishDownload:(id)arg2 willProceedWithInstallation:(char)arg3 waitingForAdmissionControl:(char)arg4;
-(void)manager:(id)arg1 didFinishDownload:(id)arg2;
-(void)manager:(id)arg1 didChangeProgressOnDownload:(id)arg2;
-(void)manager:(id)arg1 didFailInstallation:(id)arg2 withError:(id)arg3;
-(void)manager:(id)arg1 didFinishInstallation:(id)arg2;
-(void)manager:(id)arg1 installationOfUpdate:(id)arg2 canProceed:(char)arg3;
-(void)manager:(id)arg1 willProceedWithInstallation:(id)arg2;

@end

