/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:14 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/SiriViewService.app/SiriViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SiriViewService/SVSAceCommandRecordDelegate.h>

@protocol SVSAceCommandRecordsDelegate;
@class NSMutableDictionary, NSString;

@interface SVSAceCommandRecords : NSObject <SVSAceCommandRecordDelegate> {

	id<SVSAceCommandRecordsDelegate> _delegate;
	NSMutableDictionary* _recordsByCommandIdentifier;

}

@property (assign,nonatomic,__weak) id<SVSAceCommandRecordsDelegate> delegate;                                                   //@synthesize delegate=_delegate - In the implementation block
@property (getter=_recordsByCommandIdentifier,nonatomic,readonly) NSMutableDictionary * recordsByCommandIdentifier;              //@synthesize recordsByCommandIdentifier=_recordsByCommandIdentifier - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)aceCommandRecordDidChangeResult:(id)arg1 ;
-(id)aceCommandWithIdentifier:(id)arg1 ;
-(id)_recordsByCommandIdentifier;
-(void)registerAceCommand:(id)arg1 ;
-(id)_recordForAceCommand:(id)arg1 ;
-(void)recordActionStartedForAceCommand:(id)arg1 ;
-(void)recordActionCompletedSuccessfullyForAceCommand:(id)arg1 ;
-(void)recordActionCompletedUnsuccessfullyForAceCommand:(id)arg1 ;
-(int)resultForAceCommand:(id)arg1 ;
-(void)setDelegate:(id<SVSAceCommandRecordsDelegate>)arg1 ;
-(id)init;
-(id<SVSAceCommandRecordsDelegate>)delegate;
@end

