/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:10:14 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/SiriViewService.app/SiriViewService
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SiriViewService/SiriViewService-Structs.h>
#import <UIKit/UIView.h>

@class SVSTranscriptContentView, UICollectionView, UIView;

@interface SVSTranscriptView : UIView {

	SVSTranscriptContentView* _contentView;

}

@property (nonatomic,readonly) UICollectionView * collectionView; 
@property (nonatomic,retain) UIView * suggestionsView; 
@property (assign,nonatomic) float topMargin; 
-(id)initWithFrame:(CGRect)arg1 collectionView:(id)arg2 ;
-(void)setSuggestionsView:(UIView *)arg1 ;
-(void)setKeylineHidden:(char)arg1 ;
-(UIView *)suggestionsView;
-(float)topMargin;
-(void)setTopMargin:(float)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(UICollectionView *)collectionView;
@end

