/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:34 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Health/Health-Structs.h>
#import <Health/WDChartSeries.h>

@class NSArray, UIColor;

@interface WDCenteredHorizontalLineSeries : WDChartSeries {

	NSArray* _dataPoints;
	UIColor* _fillColor;
	float _lineWidth;

}

@property (nonatomic,retain) UIColor * fillColor;              //@synthesize fillColor=_fillColor - In the implementation block
@property (assign,nonatomic) float lineWidth;                  //@synthesize lineWidth=_lineWidth - In the implementation block
-(void)prepareForRenderingWithSize:(CGSize)arg1 minXValue:(id)arg2 maxXValue:(id)arg3 minYValue:(id)arg4 maxYValue:(id)arg5 insets:(UIEdgeInsets)arg6 dataSet:(id)arg7 ;
-(void)renderChartInContext:(CGContextRef)arg1 ;
-(void)renderFillInContext:(CGContextRef)arg1 ;
-(id)_getPointsFromDataSet;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(float)lineWidth;
-(void)setLineWidth:(float)arg1 ;
-(void)setFillColor:(UIColor *)arg1 ;
-(UIColor *)fillColor;
@end

