/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:34 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Health/Health-Structs.h>
#import <Health/NSCopying.h>

@class NSDate, NSNumber, NSArray, WDChartDataSet;

@interface WDChartSeries : NSObject <NSCopying> {

	NSDate* _minXValue;
	NSDate* _maxXValue;
	NSNumber* _minYValue;
	NSNumber* _maxYValue;
	NSArray* _dataPoints;
	CGSize _renderSize;
	UIEdgeInsets _insets;
	WDChartDataSet* _dataSet;
	CGSize _imageSize;

}

@property (nonatomic,readonly) WDChartDataSet * dataSet;              //@synthesize dataSet=_dataSet - In the implementation block
@property (nonatomic,readonly) CGSize imageSize;                      //@synthesize imageSize=_imageSize - In the implementation block
-(void)prepareForRenderingWithSize:(CGSize)arg1 minXValue:(id)arg2 maxXValue:(id)arg3 minYValue:(id)arg4 maxYValue:(id)arg5 insets:(UIEdgeInsets)arg6 dataSet:(id)arg7 ;
-(void)renderChartInContext:(CGContextRef)arg1 ;
-(void)renderFillInContext:(CGContextRef)arg1 ;
-(void)renderSecondaryFillInContext:(CGContextRef)arg1 ;
-(void)selectedPointIndexesUpdated:(id)arg1 ;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(CGSize)imageSize;
-(float)_relativePositionForXPlaneValue:(id)arg1 ;
-(float)_getXValueForPointFromChartPoint:(id)arg1 ;
-(float)_getYValueForPointFromChartPoint:(id)arg1 ;
-(float)_getYValueForPointFromChartPointValue:(id)arg1 ;
-(CGPoint)getPointFromChartPoint:(id)arg1 ;
-(float)_getYValueForPointFromChartPoint:(id)arg1 key:(id)arg2 ;
-(CGPoint)getPointFromChartPoint:(id)arg1 forKey:(id)arg2 ;
-(WDChartDataSet *)dataSet;
@end

