/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:34 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Health.app/Health
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Health/Health-Structs.h>
#import <UIKit/UITableViewCell.h>
#import <Health/WDDashboardChartItemDelegate.h>
#import <Health/WDDateCacheObserver.h>
#import <Health/WDDottedAverageBackgroundViewDataSource.h>

@class UIImageView, UILabel, WDDottedAverageBackgroundView, WDDateCache, HKUnitController, WDDashboardChartItem, WDChart, NSString;

@interface WDDashboardTableViewCell : UITableViewCell <WDDashboardChartItemDelegate, WDDateCacheObserver, WDDottedAverageBackgroundViewDataSource> {

	UIImageView* _backgroundImageView;
	UIImageView* _categoryIcon;
	UILabel* _averageLabel;
	UIImageView* _averageUnitIcon;
	UILabel* _currentValueLabel;
	UILabel* _lastUpdatedLabel;
	UILabel* _titleLabel;
	WDDottedAverageBackgroundView* _chartBackground;
	WDDateCache* _dateCache;
	HKUnitController* _unitController;
	WDDashboardChartItem* _chartItem;
	int _timeScope;
	WDChart* _chartView;

}

@property (nonatomic,retain) WDDashboardChartItem * chartItem;              //@synthesize chartItem=_chartItem - In the implementation block
@property (assign,nonatomic) int timeScope;                                 //@synthesize timeScope=_timeScope - In the implementation block
@property (nonatomic,readonly) WDChart * chartView;                         //@synthesize chartView=_chartView - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(float)preferredCellHeight;
+(id)_yesterdayTodayFormatter;
+(id)_lastUpdatedFormatterWithoutYear;
+(id)_lastUpdatedFormatterWithYear;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 dateCache:(id)arg3 unitController:(id)arg4 timeScope:(int)arg5 ;
-(void)setChartItem:(WDDashboardChartItem *)arg1 ;
-(void)chartItemDidUpdateHistoricalData:(id)arg1 ;
-(void)chartItemDidUpdateCurrentValueData:(id)arg1 ;
-(void)chartItemDidUpdateSecondaryValueData:(id)arg1 ;
-(void)dateCacheDidUpdate:(id)arg1 ;
-(id)_currentValueTextWithValueFontSize:(float)arg1 unitFontSize:(float)arg2 ;
-(void)_updateTimeBasedUI;
-(id)_timeAxisDescriptor;
-(id)_getCategoryIcon;
-(id)_averageLabelText;
-(id)_getLastUpdatedText;
-(id)_getLastUpdatedDate;
-(id)backgroundView:(id)arg1 formattedStringWithValue:(id)arg2 numberFormatter:(id)arg3 ;
-(WDDashboardChartItem *)chartItem;
-(WDChart *)chartView;
-(void)_setupSubviews;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(int)timeScope;
-(void)setTimeScope:(int)arg1 ;
-(void)_updateUI;
@end

