/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:33 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Game Center.app/Game Center
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol GKDaemonProxyDataUpdateDelegate <NSObject>
@optional
-(void)refreshContentsForDataType:(unsigned)arg1 userInfo:(id)arg2;
-(void)setBadgeCount:(unsigned)arg1 forType:(unsigned)arg2;

@end

